#!/bin/bash
    echo Working on $1
    echo "     odd "
    xmllint --xinclude $1 | saxon -o x.odd - ../../Stylesheets2/odds2/odd2odd.xsl \
	useVersionFromTEI=true \
	TEIC=true \
	localsource=`pwd`/../p5subset.xml
    echo "     rng "
    saxon -o x.rng x.odd  ../../Stylesheets2/odds2/odd2relax.xsl  TEIC=true 
    echo "     xsd "
    trang  -o disable-abstract-elements x.rng x.xsd
    echo "     rnc "
    trang x.rng x.rnc
    echo "     dtd "
    saxon -o x.dtd x.odd  ../../Stylesheets2/odds2/odd2dtd.xsl TEIC=true 
    echo "     html "
    saxon -o x.html x.odd ../../Stylesheets2/odds2/odd2html.xsl splitLevel=-1 STDOUT=true
