#!/bin/sh
profile=default
debug=false
header=
conversion=
while test $# -gt 0; do
  case $1 in
    --profile=*)  profile=`echo $1 | sed 's/.*=//'`;;
    --header=*)  header=`echo $1 | sed 's/.*=//'`;;
    --conversion=*)  conversion=`echo $1 | sed 's/.*=//'`;;
    --debug)     debug=true;;
     *) if test "$1" = "${1#--}" ; then 
	   break
	else
	   echo "WARNING: Unrecognized option '$1' ignored"
	   echo "For usage syntax issue $0 --help"
	fi ;;
  esac
  shift
done
test -f "$1" || exit 1
HERE=`pwd`
D=`dirname "$1"`
THERE=`(cd $D; pwd)`
X=`dirname $0`
APPHOME=`(cd $X; pwd)`
N=`basename "$1" .odt`
TEMPLATES=$APPHOME/profiles/$profile/oo
if ! test -d $TEMPLATES 
then
    echo No support for profile $profile: $APPHOME/profiles/$profile/oo does not exist
  exit 1
fi

echo read input file $N from $THERE
echo app home directory is $APPHOME
if test "x$conversion" = "x"
then
  FROMXSL=$APPHOME/profiles/$profile/oo/from.xsl
else
  FROMXSL=$conversion
fi
echo Using $FROMXSL as conversion XSL
TEMPDIR=/tmp/oo$$
mkdir $TEMPDIR
cd $TEMPDIR
unzip -q $THERE/"$N.odt"
saxon -o "$N.xml" content.xml $FROMXSL dir="$TEMPDIR" debug=$debug 
mkdir -p Pictures
if [ "$(ls -q -A Pictures)" ]; then
 echo found graphics files in document, so writing $N.zip in $THERE
 test -f $THERE/"$N.zip" && rm $THERE/"$N.zip"
 zip -q -r $THERE/"$N.zip" "$N.xml" Pictures
else
 echo writing $N.xml in $THERE
 mv "$N.xml" $THERE
fi
cd $HERE
if $debug 
then
    echo Working files in $TEMPDIR
else
    rm -rf $TEMPDIR
fi


