#!/usr/bin/perl

$Type{"teixslHome"}="param";
$Default{"teixslHome"}=qq(http://www.oucs.ox.ac.uk/stylesheets/);

$Type{"masterFile"}="param";
$Default{"masterFile"}=qq(index);

$Type{"inputName"}="param";
$Default{"inputName"}=qq();

$Type{"outputDir"}="param";
$Default{"outputDir"}=qq();

$Type{"splitLevel"}="param";
$Default{"splitLevel"}=qq(-1);

$Type{"splitBackmatter"}="param";
$Default{"splitBackmatter"}=qq(true);

$Type{"splitFrontmatter"}="param";
$Default{"splitFrontmatter"}=qq(true);

$Type{"sectionTopLink"}="param";
$Default{"sectionTopLink"}=qq();

$Type{"useIDs"}="param";
$Default{"useIDs"}=qq(true);

$Type{"makingSlides"}="param";
$Default{"makingSlides"}=qq();

$Type{"autoToc"}="param";
$Default{"autoToc"}=qq(true);

$Type{"tocDepth"}="param";
$Default{"tocDepth"}=qq(5);

$Type{"subTocDepth"}="param";
$Default{"subTocDepth"}=qq(-1);

$Type{"tocFront"}="param";
$Default{"tocFront"}=qq(true);

$Type{"tocBack"}="param";
$Default{"tocBack"}=qq(true);

$Type{"logoPicture"}="template";
$Default{"logoPicture"}=qq(<a target="_top" href="http://www.ox.ac.uk/"><img border="0" width="78" height="94"
    src="http://www.oucs.ox.ac.uk/images/ncrest.gif"
    alt="Oxford University"/></a>);

$Type{"cssFile"}="param";
$Default{"cssFile"}=qq(/stylesheets/tei-oucs.css);

$Type{"feedbackURL"}="param";
$Default{"feedbackURL"}=qq(mailto:feedback);

$Type{"feedbackWords"}="template";
$Default{"feedbackWords"}=qq(Feedback);

$Type{"homeURL"}="param";
$Default{"homeURL"}=qq(http://www.oucs.ox.ac.uk/);

$Type{"homeLabel"}="param";
$Default{"homeLabel"}=qq(Home);

$Type{"noframeWords"}="param";
$Default{"noframeWords"}=qq(No Frames);

$Type{"homeWords"}="param";
$Default{"homeWords"}=qq(OUCS);

$Type{"institution"}="param";
$Default{"institution"}=qq(Oxford University Computing Services);

$Type{"department"}="param";
$Default{"department"}=qq();

$Type{"parentURL"}="param";
$Default{"parentURL"}=qq(http://www.ox.ac.uk/);

$Type{"parentWords"}="param";
$Default{"parentWords"}=qq(Oxford University);

$Type{"searchURL"}="param";
$Default{"searchURL"}=qq(http://wwwsearch.ox.ac.uk/cgi-bin/oxunit?oucs);

$Type{"searchWords"}="template";
$Default{"searchWords"}=qq(Search);

$Type{"topNavigationPanel"}="param";
$Default{"topNavigationPanel"}=qq(true);

$Type{"bottomNavigationPanel"}="param";
$Default{"bottomNavigationPanel"}=qq(true);

$Type{"alignNavigationPanel"}="param";
$Default{"alignNavigationPanel"}=qq(right);

$Type{"linkPanel"}="param";
$Default{"linkPanel"}=qq(true);

$Type{"copyrightStatement"}="template";
$Default{"copyrightStatement"}=qq(<a 
href="/documentation/copyright.html">&#169;</a> Oxford 
University Computing Services.);

$Type{"makePageTable"}="param";
$Default{"makePageTable"}=qq();

$Type{"leftLinks"}="param";
$Default{"leftLinks"}=qq();

$Type{"rightLinks"}="param";
$Default{"rightLinks"}=qq();

$Type{"linksWidth"}="param";
$Default{"linksWidth"}=qq(15%);

$Type{"makeFrames"}="param";
$Default{"makeFrames"}=qq();

$Type{"frameCols"}="param";
$Default{"frameCols"}=qq(200,*);

$Type{"frameAlternateURL"}="param";
$Default{"frameAlternateURL"}=qq();

$Type{"logoFramePicture"}="template";
$Default{"logoFramePicture"}=qq(<a class="framelogo" target="_top" href="http://www.ox.ac.uk">
     <img src="http://www.oucs.ox.ac.uk/images/ncrest.gif"
     vspace="5" width="90" height="107" border="0"
  alt="University Of Oxford"/></a>);

$Type{"sectionUpLink"}="param";
$Default{"sectionUpLink"}=qq();

$Type{"topLink"}="template";
$Default{"topLink"}=qq(<p>[<a href="#TOP">Back to top</a>]</p>);

$Type{"appendixWords"}="param";
$Default{"appendixWords"}=qq(Appendix);

$Type{"tocWords"}="param";
$Default{"tocWords"}=qq(Contents);

$Type{"upWord"}="param";
$Default{"upWord"}=qq(Up);

$Type{"nextWord"}="param";
$Default{"nextWord"}=qq(Next);

$Type{"previousWord"}="param";
$Default{"previousWord"}=qq(Previous);

$Type{"contentsWord"}="template";
$Default{"contentsWord"}=qq(Contents);

$Type{"dateWord"}="param";
$Default{"dateWord"}=qq(Date:);

$Type{"authorWord"}="param";
$Default{"authorWord"}=qq(Author:);

$Type{"divOffset"}="param";
$Default{"divOffset"}=qq(2);

$Type{"numberHeadings"}="param";
$Default{"numberHeadings"}=qq(true);

$Type{"numberFrontHeadings"}="param";
$Default{"numberFrontHeadings"}=qq();

$Type{"numberBackHeadings"}="param";
$Default{"numberBackHeadings"}=qq(true);

$Type{"prenumberedHeadings"}="param";
$Default{"prenumberedHeadings"}=qq();

$Type{"headingNumberSuffix"}="param";
$Default{"headingNumberSuffix"}=qq(.<xsl:value-of select="$numberSpacer"/>);

$Type{"numberSpacer"}="param";
$Default{"numberSpacer"}=qq(<xsl:text> </xsl:text> );

$Type{"numberHeadingsDepth"}="param";
$Default{"numberHeadingsDepth"}=qq(9);

$Type{"fontURL"}="param";
$Default{"fontURL"}=qq(span);

$Type{"tableAlign"}="param";
$Default{"tableAlign"}=qq(left);

$Type{"showTitleAuthor"}="param";
$Default{"showTitleAuthor"}=qq();

$Type{"footnoteFile"}="param";
$Default{"footnoteFile"}=qq();

$Type{"minimalCrossRef"}="param";
$Default{"minimalCrossRef"}=qq();

$Type{"graphicsPrefix"}="param";
$Default{"graphicsPrefix"}=qq();

$Type{"graphicsSuffix"}="param";
$Default{"graphicsSuffix"}=qq(.jpg);

$Type{"showFigures"}="param";
$Default{"showFigures"}=qq(true);

$Type{"bodyHook"}="template";
$Default{"bodyHook"}=qq();

$Type{"bodyJavaScript"}="template";
$Default{"bodyJavaScript"}=qq();

$Type{"headHook"}="template";
$Default{"headHook"}=qq();

$Type{"searchbox"}="template";
$Default{"searchbox"}=qq();

$Type{"rendSeparator"}="template";
$Default{"rendSeparator"}=qq(;);

$Type{"verbose"}="param";
$Default{"verbose"}=qq();

$Type{"downPicture"}="param";
$Default{"downPicture"}=qq(http://www.oucs.ox.ac.uk/images/down.gif);

$Type{"useHeaderFrontMatter"}="param";
$Default{"useHeaderFrontMatter"}=qq();

$Type{"outputEncoding"}="param";
$Default{"outputEncoding"}=qq(iso-8859-1);

$Type{"REQUEST"}="param";
$Default{"REQUEST"}=qq();

$Type{"ID"}="param";
$Default{"ID"}=qq();

$Type{"rawIE"}="param";
$Default{"rawIE"}=qq();

$Type{"numberBodyDiv"}="template";
$Default{"numberBodyDiv"}=qq(<xsl:param name="minimal"/>
     <xsl:if test="not($numberHeadings='')">
         <xsl:number level="multiple"
                     count="div|div0|div1|div2|div3|div4|div5|div6"/>
     </xsl:if>);

$Type{"numberFrontDiv"}="template";
$Default{"numberFrontDiv"}=qq(<xsl:param name="minimal"/>
     <xsl:if test="not($numberFrontHeadings='')">
         <xsl:number level="multiple" 
                     count="div|div0|div1|div2|div3|div4|div5|div6"/>
<xsl:if test="not($minimal)"><xsl:value-of select="$numberSpacer"/></xsl:if>
      </xsl:if>);

$Type{"numberBackDiv"}="template";
$Default{"numberBackDiv"}=qq(<xsl:param name="minimal"/>
     <xsl:if test="not($numberBackHeadings='')">
        <xsl:number format="A.1.1.1.1.1" 
         level="multiple" count="div|div0|div1|div2|div3|div4|div5|div6"/>
      <xsl:if test="not($minimal)"><xsl:value-of select="$numberSpacer"/>
</xsl:if>
    </xsl:if>);


use CGI qw(:standard :html3);
use CGI::Carp;
use CGI::Carp qw(fatalsToBrowser);

$query = new CGI;

$today = (localtime)[3] . " " . (Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec)[(localtime)[4]] . " " . ((localtime)[5] + 1900);

$path_info = $query->path_info;

if ($path_info eq '/mytei.xsl') {
  &Response($query) ;
}
else
  { 
 &Form($query->script_name);
}

sub Response {
$HOME=$query->param('teixslHome');
print "Content-type: text/xsl\n\n";
print "<xsl:stylesheet \n";
print "     xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\" \n";
print "     version=\"1.0\">\n";
print "<!-- XSLT stylesheet to generate HTML version of TEI document\n";
print "Written by the TEI XSL generator (Sebastian Rahtz, sebastian.rahtz\@oucs.ox.ac.uk, October 2000)\n";
print "Created on $today-->\n";
print "<xsl:import href=\"",$HOME,"teihtml.xsl\"/>\n";
foreach $key (keys %Default) {
$Passed=$query->param($key);
$Passed =~ tr/\015//d;
#print "$key: $Passed: $Default{$key}\n";
if ($Passed ne $Default{$key}) {
 if ($Passed eq "false") { $Passed=""; }
 print "<xsl:$Type{$key} name=\"$key\">";
 print $Passed;
 print "</xsl:$Type{$key}>\n";
}
}
print "</xsl:stylesheet>\n";

return "";
}

sub Form {
my ($ME)=@_;
print $query->header;

print <<EOFORM1;
<html><!--THIS FILE IS GENERATED FROM AN XML MASTER. 
   DO NOT EDIT-->
   <head>
      <title>XSL TEI HTML stylesheet parameterization</title>
      <link rel="stylesheet" type="text/css" href="/stylesheets/tei-oucs.css"/>
      <meta name="DC.Title" content="XSL TEI HTML stylesheet parameterization"/>
      <meta name="DC.Author" content="Sebastian Rahtz"/>
      <meta name="DC.Language" content="(SCHEME=iso639) en"/>
      <meta name="DC.Creator" content="Oxford University Computing Services, 13 Banbury Road, Oxford OX2 6NN, United Kingdom"/>
      <meta name="DC.Creator.Address" content="webmaster@oucs.ox.ac.uk"/>
   </head>
   <body>
      <a name="TOP"/>
      <table class="header" width="100%">
         <tr>
            <td rowspan="3">
               <a target="_top" href="http://www.ox.ac.uk/">
                  <img border="0" width="78" height="94" src="/images/ncrest.gif" alt="Oxford University"/>
               </a>
            </td>
            <td align="left">
               <h2 class="institution">Oxford University Computing Services</h2>
            </td>
         </tr>
         <tr>
            <td align="left">
               <h1 class="maintitle">XSL TEI HTML stylesheet parameterization</h1>
            </td>
         </tr>
      </table>
      <hr/>
      <h2>Contents</h2>
      <ul class="toc">
         <li class="toc">1. <a class="toc" href="#body.1_div.1">Introduction</a>
         </li>
         <li class="toc">2. <a class="toc" href="#body.1_div.2">Structuring the output</a>
         </li>
         <li class="toc">3. <a class="toc" href="#body.1_div.3">Table of contents generation</a>
         </li>
         <li class="toc">4. <a class="toc" href="#body.1_div.4">Standard page features</a>
         </li>
         <li class="toc">5. <a class="toc" href="#body.1_div.5">Frames and other navigation aids</a>
         </li>
         <li class="toc">6. <a class="toc" href="#body.1_div.6">Choosing words</a>
         </li>
         <li class="toc">7. <a class="toc" href="#body.1_div.7">Style</a>
         </li>
         <li class="toc">8. <a class="toc" href="#body.1_div.8">Graphics</a>
         </li>
         <li class="toc">9. <a class="toc" href="#body.1_div.9">Hooks</a>
         </li>
         <li class="toc">10. <a class="toc" href="#body.1_div.10">Miscellaneous and advanced</a>
         </li>
      </ul>
      <form method="POST" name="PizzaForm" enctype="multipart/form-data" action="$ME/mytei.xsl">


         <div class="teidiv">
            <h2>
               <a name="body.1_div.1"/>1. Introduction</h2>
 

            <p>
               <a name="d19e62"/>This web page will let you create an XSLT stylesheet
to process your TEI documents. The stylesheet will import
a generalized set of TEI XSLT specifications, and then tailor
various bits of it depending on the answers you give below.</p>

            <p>
               <a name="d19e65"/>You need to start off by specifying where you store your
copies of the general TEI XSLT stylesheets. 
This can be expressed as a local directory specification, or a URL:
<br><input name="teixslHome" type="textbox" value="http://www.oucs.ox.ac.uk/stylesheets/" size="41"/> 
               <em>Location of master files</em><br>
</p>

         </div>



         <div class="teidiv">
            <h2>
               <a name="body.1_div.2"/>2. Structuring the output</h2>
 

            <p>
               <a name="d19e83"/>Now we need to establish the name of the output file(s); if
you ask for multiple output files, this name will be used to create 
unique filenames for each section. Even if you do not want your output
split up, the name is still used for output. Do <em>not</em> put a
<tt>.html</tt> suffix on the end. If you leave this variable
<em>blank</em>, results will go to wherever your XSLT
processor writes by default (usually standard output).
<br><input name="masterFile" type="textbox" value="index" size="9"/> 
               <em>Output file</em><br>
As an alternative, you can pass the name of the input XML file to
the processor using a top-level parameter:
<br><input name="inputName" type="textbox" value="" size="12"/> 
               <em>Input filename</em><br>
If no <strong>masterFile</strong> is specified, but the
<strong>inputName</strong> 
               <em>is</em> provided, then the output file(s)
will be named after the input file.
</p>

            <p>
               <a name="d19e121"/>
You can also pass the name of the directory where the output is to be placed
 using a top-level parameter:
<br><input name="outputDir" type="textbox" value="" size="12"/> 
               <em>Output directory</em><br>
</p>


            <p>
               <a name="d19e132"/>Next, do you want a single output file, or a separate one for each
section of the document? If you want separate files, set this to 0 or greater.
0 is the top level if  you used unnumbered <tt>&lt;div&gt;</tt> elements. 
-1 means no splitting at all.
<br><input name="splitLevel" type="textbox" value="-1" size="4"/> 
               <em>Splitting level</em><br>
You can also decide to have a different splitting policy for front and
	  back matter:
<br><input name="splitBackmatter" type="checkbox" checked="checked" value="true"/> 
               <em>Split back matter</em><br>
<br><input name="splitFrontmatter" type="checkbox" checked="checked" value="true"/> 
               <em>Split front matter</em><br>
</p>

            <p>
               <a name="d19e165"/>Do you want a link back up to the top after the end of each
	  division?
<br><input name="sectionTopLink" type="checkbox" value="true"/> 
               <em>Put link to top after each section</em><br>
</p>


            <p>
               <a name="d19e176"/>Lastly, it is often nice if, when making separate files, their names
correspond to the ID attribute of the <tt>&lt;div&gt;</tt>. Alternatively, you
	  can let the system choose names.
 <br><input name="useIDs" type="checkbox" checked="checked" value="true"/> 
               <em>Use ID attributes to name files</em><br>
</p>

            <p>
               <a name="d19e191"/>A special mode is available for making slides. Tick this
	  if you want to invoke that mode.
<br><input name="makingSlides" type="checkbox" value="true"/> 
               <em>Make slides</em><br>
</p>


         </div>



         <div class="teidiv">
            <h2>
               <a name="body.1_div.3"/>3. Table of contents generation</h2>
 

            <p>
               <a name="d19e210"/>You probably want tables of contents built for your document, using
the <tt>&lt;div&gt;</tt> structure. However, if you have used a <tt>&lt;divGen
	  type="toc"&gt;</tt> explicitly, that will also create a table of
	contents, so you can suppress the automatic one.
<br><input name="autoToc" type="checkbox" checked="checked" value="true"/> 
               <em>Create table of contents</em><br>
When a table of contents is  created, you choose how many levels of
	  headings it will show:
<br><input name="tocDepth" type="textbox" value="5" size="4"/> 
               <em>Table of contents depth</em><br>
You can also have a mini table of contents at the start of each
	  section. The default is only to construct a mini TOC for the
	  top level.
<br><input name="subTocDepth" type="textbox" value="-1" size="4"/> 
               <em>Level of division for mini TOC</em><br>
</p>

            <p>
               <a name="d19e246"/>Finally, you can choose whether or not the front and backmatter appear
in the table of contents:
<br><input name="tocFront" type="checkbox" checked="checked" value="true"/> 
               <em>Whether TOC shows front matter</em><br>
<br><input name="tocBack" type="checkbox" checked="checked" value="true"/> 
               <em>Whether TOC shows back matter</em><br>
</p>

         </div>



         <div class="teidiv">
            <h2>
               <a name="body.1_div.4"/>4. Standard page features</h2>
 

            <p>The default behaviour of the system is to construct each HTML page
in a standard way, with per-page navigation bars top and
bottom, and a standard set of navigation links underneath. 
The top of the page is a table with a logo on the
left spanning the rows, a row containing the name of the institution, an
(optional) row containing a `department' name, and a row containing
the page title. You can either redefine the named templates
<strong>stdheader</strong> and <strong>stdfooter</strong>,
or change any or all of the following variables:
</p>
            <ul>
               <li>
                  <a name="d19e285"/>
<br><textarea name="logoPicture" type="textarea" cols="40" rows="5">&lt;a target="_top" href="http://www.ox.ac.uk/"&gt;&lt;img border="0" width="78" height="94"
    src="http://www.oucs.ox.ac.uk/images/ncrest.gif"
    alt="Oxford University"/&gt;&lt;/a&gt;</textarea> 
                  <em>The HTML which will be placed in the top left corner of
    the page to make a logo </em><br></li>
               <li>
                  <a name="d19e296"/>
<br><input name="cssFile" type="textbox" value="/stylesheets/tei-oucs.css" size="29"/> 
                  <em>The CSS file which is to be used</em><br>

</li>
               <li>
                  <a name="d19e308"/>
<br><input name="feedbackURL" type="textbox" value="mailto:feedback" size="19"/> 
                  <em>An email address for feedback</em><br>

</li>
               <li>
                  <a name="d19e320"/>
<br><input name="feedbackWords" type="textbox" value="Feedback" size="12"/> 
                  <em>The label for feedback link</em><br>

</li>
               <li>
                  <a name="d19e332"/>
<br><input name="homeURL" type="textbox" value="http://www.oucs.ox.ac.uk/" size="29"/> 
                  <em>Site's home page</em><br>

</li>
               <li>
                  <a name="d19e344"/>
<br><input name="homeLabel" type="textbox" value="Home" size="8"/> 
                  <em>Label for link to Home page</em><br>
</li>
               <li>
                  <a name="d19e356"/>
<br><input name="noframeWords" type="textbox" value="No Frames" size="13"/> 
                  <em>Words to use on a page indicating that frames cannot be
  used</em><br>
</li>
               <li>
                  <a name="d19e368"/>
<br><input name="homeWords" type="textbox" value="OUCS" size="8"/> 
                  <em>Label of site home page</em><br>
</li>
               <li>
                  <a name="d19e380"/>
<br><input name="institution" type="textbox" value="Oxford University Computing Services" size="40"/> 
                  <em>The institution</em><br>
</li>
               <li>
                  <a name="d19e392"/>
<br><input name="department" type="textbox" value="" size="12"/> 
                  <em>The department</em><br>

</li>
               <li>
                  <a name="d19e403"/>
<br><input name="parentURL" type="textbox" value="http://www.ox.ac.uk/" size="24"/> 
                  <em>Parent institutional home page</em><br></li>
               <li>
                  <a name="d19e414"/>
<br><input name="parentWords" type="textbox" value="Oxford University" size="21"/> 
                  <em>Label of parent institutional home page</em><br></li>
               <li>
                  <a name="d19e425"/>
<br><input name="searchURL" type="textbox" value="http://wwwsearch.ox.ac.uk/cgi-bin/oxunit?oucs" size="49"/> 
                  <em>Link to search page</em><br>
</li>
               <li>
                  <a name="d19e437"/>

<br><input name="searchWords" type="textbox" value="Search" size="10"/> 
                  <em>Label of search button</em><br>
</li>
               <li>
                  <a name="d19e449"/>

<br><input name="topNavigationPanel" type="checkbox" checked="checked" value="true"/> 
                  <em>Make a navigation panel at the top of the page</em><br>
</li>
               <li>
                  <a name="d19e461"/>

<br><input name="bottomNavigationPanel" type="checkbox" checked="checked" value="true"/> 
                  <em>Make a navigation panel at the bottom of the page</em><br>
</li>
               <li>
                  <a name="d19e473"/>

<br><input name="alignNavigationPanel" type="textbox" value="right" size="9"/> 
                  <em>Alignment of navigation panels</em><br>
</li>
               <li>
                  <a name="d19e485"/>

<br><input name="linkPanel" type="checkbox" checked="checked" value="true"/> 
                  <em>Make a panel of standard links at the bottom of the page</em><br>
</li>
               <li>
                  <a name="d19e497"/>
<br><textarea name="copyrightStatement" type="textarea" cols="40" rows="5">&lt;a 
href="/documentation/copyright.html"&gt;&amp;#169;&lt;/a&gt; Oxford 
University Computing Services.</textarea> 
                  <em>Copyright statement</em><br>
</li>
            </ul>
            <p>

            </p>

         </div>


         <div class="teidiv">
            <h2>
               <a name="body.1_div.5"/>5. Frames and other navigation aids</h2>
 

            <p>
               <a name="d19e517"/>There are three ways to provide a constant navigation aid. You can
either make the whole page into a table, where the first column has a table
of contents, or you can make an HTML frameset, or you can just have 
a table of links on the left or right</p>

            <p>
               <a name="d19e520"/>If you want the full page table, set the variable
<br><input name="makePageTable" type="checkbox" value="true"/> 
               <em>Whether to make each page a full-scale
table, with the first  column  containing links etc</em><br>
    </p>


            <p>If you want the simpler table, set one of the two following variables:
</p>
            <ol>
               <li>
                  <a name="d19e535"/>
<br><input name="leftLinks" type="checkbox" value="true"/> 
                  <em>Whether to make each page a table, with the first
  column  being a set of standard links</em><br>
</li>
               <li>
                  <a name="d19e546"/>
<br><input name="rightLinks" type="checkbox" value="true"/> 
                  <em>Whether to make each page a table, with the last
  column  being a set of standard links</em><br>
</li>
            </ol>
            <p>
In either case the width of the links column is set with
<br><input name="linksWidth" type="textbox" value="15%" size="4"/> 
               <em>Width of links column</em><br>
</p>

            <p>
               <a name="d19e568"/>If you want a frameset, use a top-level parameter:
<br><input name="makeFrames" type="checkbox" value="true"/> 
               <em>Whether to construct a frames 
  version of the document</em><br>
If this is set to `true', a frame on the left-hand side will contain a
table of contents for the document. The width of the frames is set by
<br><input name="frameCols" type="textbox" value="200,*" size="9"/> 
               <em>Width of frames</em><br>
You can define an alternate URL to which non-frames browsers will
be directed:
<br><input name="frameAlternateURL" type="textbox" value="" size="12"/> 
               <em>alternate URL for noframes</em><br>If this is not set, the normal name will be used. In addition,
  you need to specify an alternate logo for the `menu' frame
<br><textarea name="logoFramePicture" type="textarea">&lt;a class="framelogo" target="_top" href="http://www.ox.ac.uk"&gt;
     &lt;img src="http://www.oucs.ox.ac.uk/images/ncrest.gif"
     vspace="5" width="90" height="107" border="0"
  alt="University Of Oxford"/&gt;&lt;/a&gt;</textarea> 
               <em>Logo for menu frame</em><br>
</p>

            <p>Links from frames present special problems, as we have to choose
whether they should start a new window, occupy all of the current
window, or stay within the frame. These stylesheets implement the
following rules:
</p>
            <ol>
               <li>
                  <a name="d19e611"/>Any <tt>&lt;ref&gt;</tt> or <tt>&lt;ptr&gt;</tt> link stays within the frame</li>
               <li>
                  <a name="d19e620"/>Any link containing `://' uses the whole browser window</li>
               <li>
                  <a name="d19e623"/>Any link starting `.' uses the whole browser window</li>
               <li>
                  <a name="d19e626"/>If the stylesheet sets no splitting of the document,
any <tt>&lt;xref&gt;</tt> or <tt>&lt;xptr&gt;</tt> link  uses the whole browser
window</li>
               <li>
                  <a name="d19e635"/>If a <tt>&lt;xref&gt;</tt> or <tt>&lt;xptr&gt;</tt> link has a
<strong>rend</strong> attribute value of `noframe', the whole browser
window is used</li>
               <li>
                  <a name="d19e647"/>If a <tt>&lt;xref&gt;</tt> or <tt>&lt;xptr&gt;</tt> link has a
<strong>rend</strong> attribute value of `new', a new browser window
is started</li>
            </ol>
            <p>

            </p>

            <p>
               <a name="d19e661"/>Lastly, you can add a reminder link at the end of every top-level
section, which points back to the top of the document:
<br><input name="sectionUpLink" type="checkbox" value="true"/> 
               <em>Add link after each section to the top of the document</em><br>
What that link consists of is determined by a named template:
<br><input name="topLink" type="textbox" value="&lt;p&gt;[&lt;a href=&#34;#TOP&#34;&gt;Back to top&lt;/a&gt;]&lt;/p&gt;" size="43"/> 
               <em>Link to top of document</em><br>
The stylesheets always make an anchor called `TOP' at the start of the
document. 
     </p>

         </div>



         <div class="teidiv">
            <h2>
               <a name="body.1_div.6"/>6. Choosing words</h2>
 

            <p>At various places, the system has to create text. You can choose
the words it uses (eg translate them to another language):
</p>
            <ul>
               <li>
                  <a name="d19e691"/><br><input name="appendixWords" type="textbox" value="Appendix" size="12"/> 
                  <em>The word for appendix</em><br></li>
               <li>
                  <a name="d19e701"/><br><input name="tocWords" type="textbox" value="Contents" size="12"/> 
                  <em>Title of a table of contents</em><br></li>
               <li>
                  <a name="d19e711"/><br><input name="upWord" type="textbox" value="Up" size="6"/> 
                  <em>How to label an up link</em><br></li>
               <li>
                  <a name="d19e721"/><br><input name="nextWord" type="textbox" value="Next" size="8"/> 
                  <em>How to label a `next' link</em><br></li>
               <li>
                  <a name="d19e731"/><br><input name="previousWord" type="textbox" value="Previous" size="12"/> 
                  <em>How to label a `previous' link</em><br></li>
               <li>
                  <a name="d19e741"/><br><input name="contentsWord" type="textbox" value="Contents" size="12"/> 
                  <em>How to label a `contents' link</em><br>
</li>
               <li>
                  <a name="d19e752"/><br><input name="dateWord" type="textbox" value="Date:" size="9"/> 
                  <em>How to label the date</em><br></li>
               <li>
                  <a name="d19e762"/><br><input name="authorWord" type="textbox" value="Author:" size="11"/> 
                  <em>How to label the author</em><br></li>
            </ul>
            <p>

            </p>

         </div>



         <div class="teidiv">
            <h2>
               <a name="body.1_div.7"/>7. Style</h2>
 

            <p>
               <a name="d19e782"/>When we turn a TEI  <tt>&lt;div&gt;</tt> into HTML, we have to decide
what  <tt>&lt;h*&gt;</tt> tags to use. The number you give is
added to the depth of the <tt>&lt;div&gt;</tt> nesting, and used to
	  make 
<tt>&lt;h1&gt;</tt>,
<tt>&lt;h2&gt;</tt>, <tt>&lt;h3&gt;</tt> etc. 
So a <tt>&lt;div0&gt;</tt> maps to <tt>&lt;h2&gt;</tt> with the default
offset value of 2.
<br><input name="divOffset" type="textbox" value="2" size="4"/> 
               <em>The mapping between div and h*</em><br>
</p>


            <p>
               <a name="d19e823"/>Section headings can be numbered.
If this variable is set to be empty,
no numbering is done; if set to `true', numbering is arabic;
otherwise the numbering is determined by
using the value for the `format' attribute of <tt>&lt;xsl:number&gt;</tt>
<br><input name="numberHeadings" type="textbox" value="true" size="8"/> 
               <em>Number headings</em><br>
Similarly, we can set the numbering of front matter
<br><input name="numberFrontHeadings" type="textbox" value="" size="12"/> 
               <em>Number headings in front matter</em><br>
and back matter
<br><input name="numberBackHeadings" type="textbox" value="true" size="8"/> 
               <em>Number headings in back matter</em><br>
</p>

            <p>
               <a name="d19e855"/>If you prefer to supply your own numbering, using the
	  <tt>n</tt>
attribute, you can choose this over automatic numbering:
<br><input name="prenumberedHeadings" type="checkbox" value="true"/> 
               <em>Use supplied numbering in n attribute</em><br>
</p>

            <p>
               <a name="d19e869"/>Normally, heading numbers are followed by `. ', but you can
vary this: 
<br><input name="headingNumberSuffix" type="textbox" value=".&lt;xsl:value-of select=&#34;$numberSpacer&#34;/&gt;" size="43"/> 
               <em>Suffix for section numbers</em><br>. To let you use eg fixed spaces, you could
redefine the variable:
<br><input name="numberSpacer" type="textbox" value="&lt;xsl:text&gt; &lt;/xsl:text&gt; " size="27"/> 
               <em>Suffix for section numbers</em><br>
</p>

            <p>
               <a name="d19e888"/>If want to suppress section numbering below a certain depth:
<br><input name="numberHeadingsDepth" type="textbox" value="9" size="5"/> 
               <em>lowest depth at which sections are numbered</em><br></p>

            <p>You can also choose
</p>
            <ul>
               <li>
                  <a name="d19e903"/>What font to use for URLs:
<br><input name="fontURL" type="textbox" value="span" size="8"/> 
                  <em>Font used for URLs</em><br></li>
               <li>
                  <a name="d19e914"/>How to align tables:
<br><input name="tableAlign" type="textbox" value="left" size="8"/> 
                  <em>Table alignment</em><br></li>
               <li>
                  <a name="d19e925"/>Whether titles, dates and authors are shown:
<br><input name="showTitleAuthor" type="checkbox" value="true"/> 
                  <em>Show titles, dates and authors</em><br></li>
               <li>
                  <a name="d19e935"/>Whether footnotes should be put in a separate file:
<br><input name="footnoteFile" type="checkbox" value="true"/> 
                  <em>Make footnote file</em><br></li>
               <li>
                  <a name="d19e945"/>Whether headings of objects 
   are included in cross-references:
<br><input name="minimalCrossRef" type="checkbox" value="true"/> 
                  <em>Include headings in cross-refs</em><br></li>
            </ul>
            <p>

            </p>

         </div>



         <div class="teidiv">
            <h2>
               <a name="body.1_div.8"/>8. Graphics</h2>
 

            <p>
               <a name="d19e965"/>Sometimes you need to prefix the names of all graphics files with 
a directory name or a URL:
<br><input name="graphicsPrefix" type="textbox" value="" size="12"/> 
               <em>Graphics file prefix</em><br>
or provide a default suffix
<br><input name="graphicsSuffix" type="textbox" value=".jpg" size="8"/> 
               <em>Graphics file suffix</em><br>
You can also tell <tt>&lt;figure&gt;</tt> elements whether or not to
produce anything
<br><input name="showFigures" type="checkbox" checked="checked" value="true"/> 
               <em>Show figures</em><br>
</p>

         </div>


         <div class="teidiv">
            <h2>
               <a name="body.1_div.9"/>9. Hooks</h2>


            <p>A set of templates which are empty by default; they can be used
to add code at strategic points. The content must be valid XSLT.
</p>
            <ul>
               <li>
                  <a name="d19e1007"/>Actions taken just after the HTML <tt>&lt;body&gt;</tt>:
<br><input name="bodyHook" type="textbox" value="" size="12"/> 
                  <em>Hook at start of body</em><br>
</li>
               <li>
                  <a name="d19e1021"/>Place to insert some JavaScript funtions at the start of
the <tt>&lt;body&gt;</tt> just after the last hook:
<br><input name="bodyJavaScript" type="textbox" value="" size="12"/> 
                  <em>Hook to specify JScript functions</em><br>
</li>
               <li>
                  <a name="d19e1035"/>Place to insert some code (eg <tt>&lt;meta&gt;</tt> tags) which
will appear in the <tt>&lt;head&gt;</tt>:
<br><input name="headHook" type="textbox" value="" size="12"/> 
                  <em>Hook to add code to the HTML head</em><br>
</li>
               <li>
                  <a name="d19e1052"/>Insertion of a form to link to a search function:
<br><input name="searchbox" type="textbox" value="" size="12"/> 
                  <em>Hook to add code to the HTML head</em><br>
</li>
            </ul>
            <p>
    
            </p>
         </div>



         <div class="teidiv">
            <h2>
               <a name="body.1_div.10"/>10. Miscellaneous and advanced</h2>


            <p>Finally, some miscellaneous or advanced features which you probably won't
use much.
</p>
            <ul>
               <li>
                  <a name="d19e1074"/>Some projects use multiple values in <tt>rend</tt>
attributes. These are handled, but the separator character must
be specified
<br><input name="rendSeparator" type="textbox" value=";" size="5"/> 
                  <em>Separator for multi-valued rend attributes</em><br>
</li>
               <li>
                  <a name="d19e1089"/>Whether chatty messages are produced; note that this is a
parameter which you can change on the command line:
<br><input name="verbose" type="checkbox" value="true"/> 
                  <em>Be verbose</em><br>
</li>
               <li>
                  <a name="d19e1100"/>An image file used to space out slides (not used in normal mode):
<br><input name="downPicture" type="textbox" value="http://www.oucs.ox.ac.uk/images/down.gif" size="44"/> 
                  <em>Slide spacing image</em><br>
</li>
               <li>
                  <a name="d19e1112"/>Whether title, author and date is taken from the <tt>&lt;teiHeader&gt;</tt>, 
      or is looked for in the front matter
<br><input name="useHeaderFrontMatter" type="checkbox" value="true"/> 
                  <em>Take front matter from teiHeader</em><br>
</li>
               <li>
                  <a name="d19e1128"/>Which encoding is to be used for output
<br><input name="outputEncoding" type="textbox" value="iso-8859-1" size="14"/> 
                  <em>Output encoding</em><br>
</li>
               <li>
                  <a name="d19e1140"/>The full URL of the XML file being processed; this would
       normally be set by the processor calling the stylesheet.
<br><input name="REQUEST" type="textbox" value="" size="12"/> 
                  <em>URL of current file</em><br>
</li>
               <li>
                  <a name="d19e1151"/>The ID of a <em>subset</em> of the document which should be
delivered. This needs some specialized work by the application calling
the XSLT processor.
<br><input name="ID" type="textbox" value="" size="12"/> 
                  <em>Document ID subset</em><br>
</li>
               <li>
                  <a name="d19e1165"/>If we know the processor can process XML directly, we
ay need variations on the stylesheet.
<br><input name="rawIE" type="checkbox" value="true"/> 
                  <em>Whether delivering raw XML to IE 5/6</em><br>
</li>
               <li>
                  <a name="d19e1176"/>How exactly is section numbering done?
<br><textarea name="numberBodyDiv" type="textarea" cols="40" rows="5">&lt;xsl:param name="minimal"/&gt;
     &lt;xsl:if test="not($numberHeadings='')"&gt;
         &lt;xsl:number level="multiple"
                     count="div|div0|div1|div2|div3|div4|div5|div6"/&gt;
     &lt;/xsl:if&gt;</textarea> 
                  <em>How to number body divisions</em><br>
<br><textarea name="numberFrontDiv" type="textarea" cols="40" rows="5">&lt;xsl:param name="minimal"/&gt;
     &lt;xsl:if test="not($numberFrontHeadings='')"&gt;
         &lt;xsl:number level="multiple" 
                     count="div|div0|div1|div2|div3|div4|div5|div6"/&gt;
&lt;xsl:if test="not($minimal)"&gt;&lt;xsl:value-of select="$numberSpacer"/&gt;&lt;/xsl:if&gt;
      &lt;/xsl:if&gt;</textarea> 
                  <em>How to number front matter divisions</em><br>
<br><textarea name="numberBackDiv" type="textarea" cols="40" rows="5">&lt;xsl:param name="minimal"/&gt;
     &lt;xsl:if test="not($numberBackHeadings='')"&gt;
        &lt;xsl:number format="A.1.1.1.1.1" 
         level="multiple" count="div|div0|div1|div2|div3|div4|div5|div6"/&gt;
      &lt;xsl:if test="not($minimal)"&gt;&lt;xsl:value-of select="$numberSpacer"/&gt;
&lt;/xsl:if&gt;
    &lt;/xsl:if&gt;</textarea> 
                  <em>How to number back matter divisions</em><br>

      </li>
            </ul>
            <p>

            </p>

         </div>

         <h3>Time to work!</h3>
         <ul>
            <li>
               <input value="Submit" type="submit"/>
            </li>
            <li>
               <input value="Reset" type="reset"/>
            </li>
         </ul>
      </form>
      <hr/>
      <div class="footer">
         <a class="plain" target="_top" href="http://www.ox.ac.uk/">Oxford University</a>
| <a class="plain" target="_top" href="http://www.oucs.ox.ac.uk/">OUCS</a>
| <a class="plain" target="_top" href="http://wwwsearch.ox.ac.uk/cgi-bin/oxunit?oucs">Search</a>
| <a class="plain" target="_top" href="mailto:feedback\@oucs.ox.ac.uk">Feedback</a>
      </div>
      <hr/>
      <address>Date: 
 (revised 20/11/2001)
  Author: Sebastian Rahtz
 (revised rahtz).
 <br/>
         <a href="/documentation/copyright.html">©</a> Oxford 
University Computing Services.<!--
Generated from  using an XSLT version 1 stylesheet
based on http://www.oucs.ox.ac.uk/stylesheets/teihtml.xsl
processed using SAXON 6.3 from Michael Kay on Fri Feb 01 11:23:08 GMT 2002-->
      </address>
   </body>
</html>

EOFORM1

return "";
}