#!/bin/sh 

# convert TEI file $1 into epub

profile=default
odd=false
debug=false
while test $# -gt 0; do
  case $1 in
    --profile=*)  profile=`echo $1 | sed 's/.*=//'`;;
    --odd)       odd=true;;
    --debug)     debug=true;;
    *) if test "$1" = "${1#--}" ; then 
	   break
	else
	   echo "WARNING: Unrecognized option '$1' ignored"
	   echo "For usage syntax issue $0 --help"
	fi ;;
  esac
  shift
done
test -f $1 || exit 1
HERE=`pwd`
D=`dirname $1`
F=`basename $1`
THERE=`(cd $D; pwd)`
X=`dirname $0`
APPHOME=`(cd $X; pwd)`
TEMPDIR=/tmp/epub$$
TEMPLATES=$APPHOME/profiles/$profile/epub
XSL=$APPHOME
mkdir -p $TEMPDIR
echo read $THERE/$F
case $THERE/$F in 
       *.zip)  (cd $TEMPDIR; unzip -q $THERE/$F ); F=`basename $F .zip`.xml;; 
       *) cp $THERE/$F $TEMPDIR/$F  ;; 
esac
cd $TEMPDIR
if $odd
then
    saxon -o $TEMPDIR/tmp1.xml $F $XSL/odds2/odd2odd.xsl localsource=/usr/share/xml/tei/odd/p5subset.xml TEIC=true
    saxon -o $TEMPDIR/tmp2.xml $TEMPDIR/tmp1.xml $XSL/odds2/odd2lite.xsl displayMode=rnc 
else
   mv  $F tmp2.xml
fi
saxon  tmp2.xml $APPHOME/profiles/$profile/epub/to.xsl  
if $debug 
then
    echo leaving tmp[123].xml alone
else
    rm -f tmp1.xml tmp2.xml
fi
rm -f $THERE/$F.epub
zip -q0X  $THERE/$F.epub mimetype
zip -qXr9D  $THERE/$F.epub   META-INF OEBPS
cd $HERE
if $debug 
then
    echo Working files in $TEMPDIR
else
    rm -rf $TEMPDIR
fi
echo wrote $F.epub in $THERE

