#!/bin/sh 

# convert TEI file $1 into XHTML
# Sebastian Rahtz, January 2010
# copyright: TEI Consortium
# license: GPL
# $Id$


die()
{
    echo; echo
    echo "ERROR: $@."
    D=`date "+%Y-%m-%d %H:%M:%S.%N"`
    echo "This was a fatal error. $D"
    exit 1
}

usageMsg()
{
echo "teitohtml -- reads in a TEI XML file and creates a LaTeX file"
echo "  Usage: teitohtml [options] file"
echo "  options, shown with defaults:"

echo " --profile=default      profile family"
echo " --odd                        perform ODD pre-processing"
echo " --debug                    emit some diagnostics" 
echo " --verbose                 be verbose"
}

conversion=
profile=default
odd=false
verbose=false
debug=false
splitLevel=
while test $# -gt 0; do
  case $1 in
    --profile=*)  profile=`echo $1 | sed 's/.*=//'`;;
    --odd)       odd=true;;
    --debug)     debug=true;;
    --verbose)     verbose=true;;
    --help)          usageMsg;;
    *) if test "$1" = "${1#--}" ; then 
	   break
	else
	   echo "WARNING: Unrecognized option '$1' ignored"
	   echo "For usage syntax issue $0 --help"
	fi ;;
  esac
  shift
done
HERE=`pwd`
FILE=${1:?"no TEI file supplied; for usage syntax $0 --help"}
if test -f $FILLE
then 
     echo Read file $FILE
else
  echo File $FILE does not exist
  die
fi
D=`dirname $1`
F=`basename $1`
B=`basename $1 .xml`
DOCHOME=`(cd $D; pwd)`
X=`dirname $0`
APPHOME=/usr/share/xml/tei/stylesheet
TEMPDIR=/tmp/html$$
TEMPLATES=$APPHOME/profiles/$profile/html
if ! test -d $TEMPLATES 
then
  echo No support for profile $profile: $PROFILEDIR/$profile/html does not exist
  exit 1
fi

XSL=$APPHOME
if test "x$conversion" = "x"
then
  TOXSL=$APPHOME/profiles/$profile/html/to.xsl
else
  TOXSL=$conversion
fi
mkdir -p $TEMPDIR/media
case $DOCHOME/$F in 
       *.zip)  (cd $TEMPDIR; unzip -q $DOCHOME/$F ); F=`basename $F .zip`.xml;; 
       *) cp $DOCHOME/$F $TEMPDIR/$F  ;; 
esac
cd $TEMPDIR

if $odd
then
    saxon -o:$TEMPDIR/tmp1.xml $F $XSL/odds2/odd2odd.xsl localsource=/usr/share/xml/tei/odd/p5subset.xml TEIC=true
    saxon -o:$TEMPDIR/tmp2.xml $TEMPDIR/tmp1.xml $XSL/odds2/odd2lite.xsl displayMode=rnc  summaryDoc=true
else
    ln -s $F tmp2.xml
fi
if $debug 
then
 echo $TOXSL  odd=$odd debug=$debug verbose=$verbose 
fi
saxon  -o:$DOCHOME/$B.html tmp2.xml $TOXSL odd=$odd debug=$debug verbose=$verbose 
if $debug 
then
    echo leaving tmp[123].xml alone
else
    rm -f tmp1.xml tmp2.xml
fi
cd $HERE
if $debug 
then
    echo Working files left in $TEMPDIR
else
    rm -rf $TEMPDIR
fi
echo Wrote $B.html in $DOCHOME
