#!/bin/sh 
profile=default
odd=false
debug=false
X=`dirname $0`
APPHOME=`(cd $X; pwd)`
PROFILEDIR=$APPHOME/profiles
while test $# -gt 0; do
  case $1 in
    --profile=*)  profile=`echo $1 | sed 's/.*=//'`;;
    --odd)       odd=true;;
    --profiledir=*) PROFILEDIR=`echo $1 | sed 's/.*=//'`;;
    --debug)     debug=true;;
     *) if test "$1" = "${1#--}" ; then 
	   break
	else
	   echo "WARNING: Unrecognized option '$1' ignored"
	fi ;;
  esac
  shift
done
FILE=${1:?"no TEI file supplied; for usage syntax $0 --help"}
if test -f $FILLE
then 
     echo Read file $FILE
else
  echo File $FILE does not exist
  die
fi

HERE=`pwd`
D=`dirname "$1"`
F=`basename "$1"`
THERE=`(cd $D; pwd)`
TEMPLATES=
if ! test -f $PROFILEDIR/$profile/oo/to.xsl
then
  echo No support for profile $profile: $PROFILEDIR/$profile/oo/to.xsl does not exist
  exit 1
fi

echo read $THERE/$F
ant -q -f $APPHOME/oo/build.xml \
	-lib /usr/share/saxon/saxon9he.jar \
        -Dodd=$odd \
        -Ddebug=$debug  \
	-DoutputFile="$THERE/$F.odt" \
	-DinputFile="$THERE/$F" \
        -Dprofile=$profile

echo wrote $F.odt in $THERE

