#!/bin/sh 

# convert TEI file $1 into latex
# Sebastian Rahtz, January 2010
# copyright: TEI Consortium
# license: GPL
# $Id$


die()
{
    echo; echo
    echo "ERROR: $@."
    D=`date "+%Y-%m-%d %H:%M:%S.%N"`
    echo "This was a fatal error. $D"
    exit 1
}

usageMsg()
{
echo "teitolatex -- reads in a TEI XML file and creates a LaTeX file"
echo "  Usage: teitoepub[options] file"
echo "  options, shown with defaults:"

echo " --profile=default      profile family"
echo " --odd                        perform ODD pre-processing"
echo " --uid=XXX                supply unique URN for ebook"
echo " --debug                    emit some diagnostics" 
echo " --verbose                 be verbose"
echo " --conversion=XXX                supply name of XSL conversion script"
}

conversion=
profile=default
odd=false
verbose=false
debug=false
splitLevel=
while test $# -gt 0; do
  case $1 in
    --profile=*)  profile=`echo $1 | sed 's/.*=//'`;;
    --conversion=*)  conversion=`echo $1 | sed 's/.*=//'`;;
    --odd)       odd=true;;
    --debug)     debug=true;;
    --verbose)     verbose=true;;
    --help)          usageMsg;;
    *) if test "$1" = "${1#--}" ; then 
	   break
	else
	   echo "WARNING: Unrecognized option '$1' ignored"
	   echo "For usage syntax issue $0 --help"
	fi ;;
  esac
  shift
done
HERE=`pwd`
FILE=${1:?"no TEI file supplied; for usage syntax $0 --help"}
if test -f "$FILE"
then 
     echo Read file $FILE
else
  echo File $FILE does not exist
  die
fi
D=`dirname "$1"`
F=`basename "$1"`
B=`basename "$1" .xml`
DOCHOME=`(cd $D; pwd)`
X=`dirname $0`
APPHOME=`(cd $X; pwd)`
TEMPDIR=/tmp/latex$$
TEMPLATES=$APPHOME/profiles/$profile/latex
XSL=$APPHOME
if [ $# -eq 1 ]
then
   outfile=`basename "$1" .xml`.tex
   outdir=$DOCHOME
else
   outfile=`basename $2`
   O=`dirname $2`
   outdir=`(cd $O; pwd)`
fi

if test "x$conversion" = "x"
then
  TOXSL=$APPHOME/profiles/$profile/latex/to.xsl
else
  TOXSL=$conversion
fi
mkdir -p $TEMPDIR/media
case $DOCHOME/$F in 
       *.zip)  (cd $TEMPDIR; unzip -q $DOCHOME/$F ); F=`basename $F .zip`.xml;; 
       *) cp "$DOCHOME/$F" "$TEMPDIR/$F"  ;; 
esac
cd $TEMPDIR

# images
saxon "$F" $XSL/docx/utils/graphics/listgraphics.xsl ORIG="$DOCHOME" DIR=$TEMPDIR/media > fetch
sh $TEMPDIR/fetch
if $debug 
then
cat $TEMPDIR/fetch
else
rm $TEMPDIR/fetch
fi
if $odd
then
    saxon -o:$TEMPDIR/tmp1.xml "$F" $XSL/odds/odd2odd.xsl localsource=/usr/share/xml/tei/odd/p5subset.xml TEIC=true
    saxon -o:$TEMPDIR/tmp2.xml $TEMPDIR/tmp1.xml $XSL/odds/odd2lite.xsl displayMode=rnc  summaryDoc=true
else
    ln -s "$F" tmp2.xml
fi
if $debug 
then
 echo $TOXSL  odd=$odd debug=$debug verbose=$verbose 
fi
saxon  -o:"$outdir/$outfile" tmp2.xml $TOXSL odd=$odd debug=$debug verbose=$verbose fixgraphicsurl=true
if $debug 
then
    echo leaving tmp[123].xml alone
else
    rm -f tmp1.xml tmp2.xml
fi
cd "$HERE"
if $debug 
then
    echo Working files left in $TEMPDIR
else
    rm -rf $TEMPDIR
fi
echo Wrote $outdir/$outfile
