<script language="php">
// ######################################################################
//
// Path: /usr/local/includes/php/roma/romadom.php
//
// ######################################################################

define( 'romadom_templateDir', 'roma/templates' );

/**
 * This class is responsible for Romas customization file. 
 *
 * @author: Arno Mittelbach <arno@mittelbach-online.de>
 * @version: 0.9
 * @access:  public
 * @package: roma
 */
class romaDom extends domDocument
  {
    function __construct( $szXML = '')
      {
	parent::__construct();

	if ( $szXML == '' )
	  {
 	    $this->constructDocument();
          }
	else
	  {
	    $this->loadXML( $szXML );
          }
      }

    private function constructDocument()
      {
        $oTemp = new domDocument();
	$oTEI = $oTemp->createElementNS( 'http://www.tei-c.org/ns/1.0', 'TEI' );
	$oTemp->appendChild( $oTEI );

	$oTeiHeader = $oTEI->appendChild( new domElement( 'teiHeader' ) );

	$oFileDesc = $oTeiHeader->appendChild( new domElement( 'fileDesc' ) );

	$oTitleStmt = $oFileDesc->appendChild( new domElement( 'titleStmt' ) );
	$oTitle = $oTitleStmt->appendChild( new domElement( 'title' ) );
	$oTitle->appendChild( new domText( 'My TEI Extension' ) );
	$oAuthor = $oTitleStmt->appendChild( new domElement( 'author' ) );
	$oAuthor->appendChild( new domText( 'generated by Roma' ) );

	$oPublicationStmt = $oFileDesc->appendChild( new domElement( 'publicationStmt' ) );
	$oP = $oPublicationStmt->appendChild( new domElement( 'p' ) );
	$oP->appendChild( new domText( 'for use by whoever wants it' ) );

	$oSourceDesc = $oFileDesc->appendChild( new domElement( 'sourceDesc' ) );
	$oP = $oSourceDesc->appendChild( new domElement( 'p' ) );
	$oP->appendChild( new domText( 'created on ' . date( "l dS of F Y h:i:s A" ) . ' by the form at http://www.tei-c.org.uk/Roma' ) );

	$oText = $oTEI->appendChild( new domElement( 'text' ) );
	$oBody = $oText->appendChild( new domElement( 'body' ) );
	$oP = $oBody->appendChild( new domElement( 'p' ) );

	$oSchema = $oP->appendChild( new domElement( 'schema' ) );
	$oSchema->setAttribute( 'ident', 'mytei' );

	$this->loadXML( $oTemp->SaveXML() );
      }

    // #####################################################################
    // --- Little Helper functions
    // #####################################################################

    /**
     * Creates an XPath Object with the current customization
     * and registers the namespace tei
     */
    public function getXPath( &$oXPath )
      {
        $oXPath = new domxpath( $this );
	$oXPath->registerNamespace( 'tei', 'http://www.tei-c.org/ns/1.0' );
      }


    // #####################################################################
    // --- Get Information out of the Customization
    // #####################################################################

    /**
     * returns a numbered array with all those modules the user selected
     */
    public function getSelectedModules( &$aszModules )
      {
	$this->getXPath( $oXPath );
        $aoModules = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@mode='change']/@ident" );

	$aszModules = array();
	foreach( $aoModules as $oModule )
	  {
	    $aszModules[] = $oModule->nodeValue;
          }
      }

    /**
     * returns a dom
     */
    public function getSelectedModulesDom( &$oDom )
      {
	$this->getSelectedModules( $aszModules );
	$oDom = new domDocument();
	$oDom->appendChild( new domElement( 'selectedModules' ) );
	
	foreach( $aszModules as $szModule )
	  {
	    $oDom->documentElement->appendChild( new domElement( 'module', $szModule ) );
	  } 
      }


    /**
     * returns a numberd array with all those modules the user changed
     */
    public function getChangedModules( &$aszModules )
      {
	$this->getXPath( $oXPath );
        $aoModules = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[child::tei:elementSpec]/@ident" );

	$aszModules = array();
	foreach( $aoModules as $oModule )
	  {
	    $aszModules[] = $oModule->nodeValue;
          }
      }

    /**
     * returns a dom
     */
    public function getChangedModulesDom( &$oDom )
      {
	$this->getChangedModules( $aszModules );
	$oDom = new domDocument();
	$oDom->appendChild( new domElement( 'changedModules' ) );

	foreach( $aszModules as $szModule )
	  {
	    $oDom->documentElement->appendChild( new domElement( 'module', $szModule ) );
	  }
      }


    /**
     * returns a numbered array with all excluded Elements inside a module
     * the module has to be specified with the first parameter.
     */
    public function getExcludedElementsInModule( $szModule, &$aszElements )
      {
	$this->getXPath( $oXPath );
        $aoElements = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@mode='delete']/@ident" );
	
	$aszElements = array();
	foreach( $aoElements as $oElement )
	  {
	    $aszElements[] = $oElement->nodeValue;
	  }
      }

    /**
     */
    public function getExcludedElementsInModuleDom( $szModule, &$oDom )
      {
	$oDom = new domDocument();
	$oDom->appendChild( new domElement( 'excludedElements' ) );

	$this->getExcludedElementsInModule( $szModule, $aszElements );
	foreach( $aszElements as $szElement )
	  {
	    $oDom->documentElement->appendChild( new domElement( 'element', $szElement ) );
	  }
      }



    /**
     * returns a numbered array with all included Elements inside a module
     * the module has to be specified with the first parameter.
     */
    public function getIncludedElementsInModule( $szModule, &$aszElements )
      {
	$oListDom = new domDocument();
	$oListDom->loadXML( join( '', file( 'http://' . roma_exist_server . ':8080/exist/tei/elemsbymod.xq?module=' . $szModule ) ) );
	$aoElements = $oListDom->getElementsByTagname( 'elementName' );
	$this->getExcludedElementsInModule( $szModule, $aszExcluded );

	$aszElements = array();
	foreach( $aoElements as $oElement )
	  {
	    if( ! in_array( $oElement->nodeValue, $aszExcluded ) )
	      {
		$aszElements[] = $oElement->nodeValue;
	      }
	  }
      }


    /**
     * returns a domDocument with all added Elements.
     * returns true if the user did not yet create any new Elements.
     * The structure of the domDocument:
     *
     *   <addedElements>
     *    <Element>
     *     <elementName>Name</elementName>
     *     <include>change|delete</include>
     *     <desc>Description</desc>
     *    </Element>
     *   </addedElements>
     *
     * There might be some more tags inside the Element-tag like <classes> but since
     * they are not of interest here, they were omitted. There is also just one level of
     * Elements beyond the Element-tag. So <classes> might be there, but there would be
     * no <memberOf> inside the <classes>
     */     
    public function getAddedElements( &$oElementDom )
      {
	$errResult = false;

        $oElementDom = new domDocument;
        $oRoot = $oElementDom->appendChild( new domElement( 'addedElements' ) );

	$this->getXPath( $oXPath );
        $aoElements = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec" );

	if ( ! is_object( $aoElements->item(0) ) )
	  {
	    $errResult = true;
	  }

        foreach( $aoElements as $oElement )
          {
	    $oElem = $oRoot->appendChild( new domElement( 'Element' ) );
	    $oName = $oElem->appendChild( new domElement( 'elementName' ) );	    
            $oName->appendChild( new domText( $oElement->getAttribute( 'ident' ) ) );
	    
	    $oInclude = $oElem->appendChild( new domElement( 'include' ) );
	    $oInclude->appendChild( new domText( $oElement->getAttribute( 'mode' ) ) );
	      
	    
	    foreach( $oElement->childNodes as $oChild )
	      {
		$oElemDesc = $oElem->appendChild( new domElement( $oChild->nodeName ) );
		$oElemDesc->appendChild( new domText( $oChild->nodeValue ) );
	      }
          }

	return $errResult;
      }

    public function getAddedElementsDescription( $szIdent, &$szDescription )
      {
	$this->getXPath( $oXPath );
        $oDesc = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='$szIdent']/tei:desc" )->item(0);

        if ( is_object( $oDesc ) )
          {
            $szDescription = $oDesc->nodeValue;
          }
      }

    public function getAddedElementsContents( $szIdent, &$szContents )
      {
	$this->getXPath( $oXPath );
        $oContent = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='$szIdent']/tei:content" )->item(0);

        if ( is_object( $oContent ) )
          {
	    $oRNG = $oContent->childNodes->item(0);
            switch( $oRNG->nodeName ) 
              {
                case 'rng:empty':
                  $szContents = 'empty';
                  break;
                case 'rng:text':
                  $szContents = 'text';
                  break;
                default:
		  if ( is_object( $oRNG ) )
		    {
		      $szContents = $oRNG->getAttribute( 'name' );
		    }
                  break;
              }
          }
      }

    public function getAddedElementsClasses( $szIdent, &$aszClasses )
      {
        $aszClasses = array();

	$this->getXPath( $oXPath );
        $aoClasses = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='$szIdent']/tei:classes/tei:memberOf/@key" );
   
        foreach( $aoClasses as $oClass )
          {
            $aszClasses[] = $oClass->nodeValue;
          }        
      }

    public function getElementsWithChangedNameInModule( $szModule, &$aszElements )
      {
	$aszElements = array();

	$this->getXPath( $oXPath );
	$aoElements = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@mode='change']/tei:altIdent" );

	foreach( $aoElements as $oElement )
	  {
	    $aszElements[ $oElement->parentNode->getAttribute( 'ident' ) ] =  $oElement->firstChild->nodeValue;
	  }
      }

    public function getElementsWithChangedNameInModuleDom( $szModule, &$oDom )
      {
	$oDom = new domDocument;
	$oDom->appendChild( new domElement( 'changedNames' ) );

	$this->getElementsWithChangedNameInModule( $szModule, $aszElements );
	foreach ( $aszElements as $szOld => $szNew )
	  {
	    $oElement = $oDom->documentElement->appendChild( new domElement( 'element' ) );
	    $oElement->setAttribute( 'ident', $szOld );
	    $oElement->appendChild( new domElement( 'altIdent', $szNew ) );
	  }
      }


    public function getElementsChangedNameInModule( $szModule, $szElement, &$szElementNew )
      {
	$this->getXPath( $oXPath );
	$oElement = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@mode='change' and @ident='$szElement']/tei:altIdent" )->item(0);

	$szElementNew = ( is_object ( $oElement ) ) ? $oElement->nodeValue : $szElement;
      }

    public function getClassesByElementNameInModule( $szElement, $szModule, &$aszClasses )
      {
        $aszClasses = array();

	$this->getXPath( $oXPath );
	$oClasses = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@mode='change' and @ident='$szElement']/tei:classes" )->item(0);

	if ( is_object( $oClasses ) )
	  {
	    foreach ( $oClasses->childNodes as $oMember )
	      {
		$aszClasses[] = $oMember->getAttribute( 'key' );
	      }
	  }
	else
	  {
	    $oElementDom = new domDocument();
	    $oElementDom->loadXML( join( '', file( 'http://' . roma_exist_server . ':8080/exist/tei/element.xq?name=' . $szElement ) ) );
	    
	    $oXPath = new domxpath( $oElementDom );
	    $aoClasses = $oXPath->query( "/Element/elementClasses/class" );
	    
	    foreach( $aoClasses as $oClass )
	      {
		$aszClasses[] = $oClass->nodeValue;
	      }
	  }
      } 

    public function getDescriptionByElementNameInModule( $szElement, $szModule, &$szDesc )
      {
	$this->getXPath( $oXPath );
	$oDesc = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@mode='change' and @ident='$szElement']/tei:desc" )->item(0);

        if ( is_object( $oDesc ) ) 
          {
  	    $szDesc = $oDesc->nodeValue;
          }
	else
	  {
	    $this->getDescriptionByElementName( $szElement, $szDesc );
	  }
      }

    public function getDescriptionByElementName( $szElement, &$szDesc )
      {
	$oElementDom = new domDocument();
	$oElementDom->loadXML( join( '', file( 'http://' . roma_exist_server . ':8080/exist/tei/element.xq?name=' . $szElement ) ) );
	
	$oXPath = new domxpath( $oElementDom );
	$oDesc = $oXPath->query( "/Element/elementDesc" )->item(0);
	
	if ( is_object( $oDesc ) )
	  {
	    $szDesc = $oDesc->nodeValue;
	  }
      } 

    public function getContentsByElementNameInModuleDom( $szElement, $szModule, &$oContents )
      {
	$this->getXPath( $oXPath );
	$oContent = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@mode='change' and @ident='$szElement']/tei:content" )->item(0);

        if ( is_object( $oContent ) ) 
          {
	    $oContents = new domDocument();
	    $oContent = $oContents->importNode( $oContent, true );
	    $oContents->appendChild( $oContent );
          }
	else
	  {
	    $oElementDom = new domDocument();
	    $oElementDom->loadXML( join( '', file( 'http://' . roma_exist_server . ':8080/exist/tei/element.xq?name=' . $szElement ) ) );
	    
	    $oXPath = new domxpath( $oElementDom );
	    $oXPath->registerNamespace( 'rng', 'http://relaxng.org/ns/structure/1.0' );
	    $oContent = $oXPath->query( "/Element/elementContent/child::*" )->item(0);
	    
	    if ( is_object( $oContent ) )
	      {
		$oContents = new domDocument();

                $theCon = $oContents->createElementNS( 'http://www.tei-c.org/ns/1.0', 'content' );
		$oCon = $oContents->appendChild( $theCon );
		$oContent = $oContents->importNode( $oContent, true );
		$oCon->appendChild( $oContent );
	      }
	  } 
      }
 
    public function getContentsByElementNameInModule( $szElement, $szModule, &$szContents )
      {
	$this->getXPath( $oXPath );
	$oContent = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@mode='change' and @ident='$szElement']/tei:content" )->item(0);

        if ( is_object( $oContent ) ) 
          {
	    $oConDom = new domDocument();
	    $oContent = $oConDom->importNode( $oContent, true );
	    $oConDom->appendChild( $oContent );
	    $szContents = $oConDom->SaveHTML();
          }
	else
	  {
	    $oElementDom = new domDocument();
	    $oElementDom->loadXML( join( '', file( 'http://' . roma_exist_server . ':8080/exist/tei/element.xq?name=' . $szElement ) ) );
	    
	    $oXPath = new domxpath( $oElementDom );
	    $oXPath->registerNamespace( 'rng', 'http://relaxng.org/ns/structure/1.0' );
	    $oContent = $oXPath->query( "/Element/elementContent/child::*" )->item(0);
	    
	    if ( is_object( $oContent ) )
	      {
		$oDom = new domDocument();

                $theCon = $oDom->createElementNS( 'http://www.tei-c.org/ns/1.0', 'content' );
		$oCon = $oDom->appendChild( $theCon );
		$oContent = $oDom->importNode( $oContent, true );
		$oCon->appendChild( $oContent );
		
		$szContents = $oDom->SaveHTML();
	      }
	  } 
      }

    public function getAttributesByElement( $szElement, &$aszAttributes )
      {
	$aszAttributes = array();

	$oAttributesDom = new domDocument();
	$oAttributesDom->loadXML( join( '', file( 'http://' . roma_exist_server . ':8080/exist/tei/attsbyelem.xq?name=' . $szElement ) ) );
	
	$oElement = $oAttributesDom->documentElement;
	foreach( $oElement->childNodes as $oChild )
	  {
	    $aszAttributes[] = $oChild->nodeValue;
	  }
      }

    public function getAttributeDomByElementInModule( $szElement, $szModule, $szClass, &$oAttDom )
      {
	$errResult = false;

	$oAttDom = new domDocument;
	$this->getXPath( $oXPath );

	if ( $szModule != '' && $szClass == '')
	  {
	    $oAttDom->loadXML( join( '', file( 'http://' . roma_exist_server . ':8080/exist/tei/attsbyelem.xq?name=' . $szElement ) ) );
	    $oElement = $oAttDom->documentElement;
	    
	    if ( ! is_object( $oElement->getElementsByTagname( 'att' )->item(0) ) )
	      {
		$errResult = true;
	      }

	    $oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@mode='change' and @ident='$szElement']/tei:attList" )->item(0);
	  }
	elseif( $szClass == '' )
	  {
	    $oAttDom->appendChild( new domElement( 'Element' ) );
	    $oElement = $oAttDom->documentElement;

	    $oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='$szElement']/tei:attList" )->item(0);
	    $errResult = true;
	  }
	else
	  {
	    $oAttDom->appendChild( new domElement( 'Element' ) );
	    $oElement = $oAttDom->documentElement;

	    $oAttClassDom = new domDocument;
	    $oAttClassDom->loadXML( join( '', file( 'http://' . roma_exist_server . ':8080/exist/tei/attclassbyname.xq?class=' . $szClass ) ) );
	    $oRoot = $oAttClassDom->documentElement;
	    $oAttributes = $oAttClassDom->getElementsByTagName( 'attributes' )->item(0);

	    foreach( $oAttributes->childNodes as $oChild )
	      {
		$oNode = $oAttDom->importNode( $oChild, true );
		$oElement->appendChild( $oNode );
	      }
	    $oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:classSpec[@mode='change' and @ident='$szClass']/tei:attList" )->item(0);
	  }

	if ( is_object( $oAttList ) )
	  {
	    if ( $errResult && count( $oAttList->childNodes ) > 0 )
	      {
		$errResult = false;
	      }

	    $oAttXPath = new domxpath( $oAttDom );

	    foreach ( $oAttList->childNodes as $oChild )
	      {
		$oAtt = $oAttXPath->query( "/Element/att[child::name[node()='" . $oChild->getAttribute( 'ident' ) . "']]" )->item(0);
		if ( ( $szModule != '' && ! is_object( $oAtt ) ) || $szModule == '' ) //if attribute was added
		  { 
		    $oAtt = $oElement->appendChild( new domElement ( 'att' ) );
		    $oAtt->setAttribute( 'added', 'true' );

		    $oAttName = $oAtt->appendChild( new domElement( 'name' ) );
		    $oAttName->appendChild( new domText( $oChild->getAttribute( 'ident' ) ) );
		    $oAttName->setAttribute( 'usage', $oChild->getAttribute( 'usage' ) );
		    
		    $oDesc = $oChild->getElementsByTagName( 'desc' )->item(0);
		    $oAttDesc = $oAtt->appendChild( new domElement( 'desc' ) );
		    $oAttDesc->appendChild( new domText( $oDesc->nodeValue ) );
		    
		    $oDefault = $oChild->getElementsByTagName( 'default' )->item(0);
		    $oAttDef = $oAtt->appendChild( new domElement( 'default' ) );
		    $oAttDef->appendChild( new domText( $oDefault->nodeValue ) );
		  }
		else
		  {
		    $oName = $oAtt->getElementsByTagName( 'name' )->item(0);
		    if( is_object( $oName ) && $oAtt->getAttribute( 'ident' ) != $oChild->getAttribute( 'ident' ) )
		      {
			$oName->setAttribute( 'ident', $oChild->getAttribute( 'ident' )  );
			$oAltIdent = $oChild->getElementsByTagName( 'altIdent' )->item(0);
			if ( is_object( $oAltIdent ) )
			  {
			    $oAlt = $oAtt->appendChild( new domElement( 'altName' ) );
			    $oAlt->appendChild( new domText( $oAltIdent->nodeValue ) );
			  }
		      }
		    if( is_object( $oName ) && $oAtt->getAttribute( 'usage' ) != $oChild->getAttribute( 'usage' ) )
		      {
			$oName->setAttribute( 'usage', $oChild->getAttribute( 'usage' )  );
		      }
		    
		    $oDesc = $oAtt->getElementsByTagName( 'desc' )->item(0);
		    $oChildDesc = $oChild->getElementsByTagName( 'desc' )->item(0);
		    if ( is_object( $oDesc ) && is_object( $oChildDesc ) &&  $oDesc->nodeValue != $oChildDesc->nodeValue )
		      {
			$oAtt->removeChild( $oDesc );
		      }
		    if ( is_object( $oChildDesc ) )
		      {
			$oAttDesc = $oAtt->appendChild( new domElement( 'desc' ) );
			$oAttDesc->appendChild( new domText( $oChildDesc->nodeValue ) );
		      }
		    
		    
		    $oChildDefault = $oChild->getElementsByTagName( 'default' )->item(0);
		    $oDefault = $oAtt->getElementsByTagName( 'default' )->item(0);
		    if ( is_object( $oDefault ) && is_object( $oChildDefault ) && $oDefault->nodeValue != $oChildDefault->nodeValue )
		      { 
			$oAtt->removeChild( $oDefault );
		      }
		    if ( is_object( $oChildDefault ) )
		      {
			$oAttDef = $oAtt->appendChild( new domElement( 'default' ) );
			$oAttDef->appendChild( new domText( $oChildDefault->nodeValue ) );
		      }

		    $oChildDat = $oChild->getElementsByTagName( 'datatype' )->item(0);
		    $oDat = $oAtt->getElementsByTagName( 'datatype' )->item(0);
		    if ( is_object( $oDat ) && is_object( $oChildDat ) )
		      {
			$oAtt->removeChild( $oDat );
		      }
		  }

		$oInclude = $oAtt->getElementsByTagName( 'include' )->item(0);
		if( is_object( $oInclude ) )
		  {
		    $oAtt->removeChild( $oInclude );
		  }
		$oAtt->appendChild( new domElement( 'include', $oChild->getAttribute( 'mode' ) ) );

		$oAttDat = $oChild->getElementsByTagName( 'datatype' )->item(0);
		if ( is_object( $oAttDat ) )
		  {
		    $oDataType = $oAtt->appendChild( new domElement( 'datatype' ) );

		    if ( $oAttDat->firstChild->nodeName == 'rng:text' )
		      {
			$oDataType->appendChild( new domText( 'text' ) );
		      }
	       	    elseif( $oAttDat->firstChild->nodeName == 'rng:data' )
		      {
			$theNode = $oAttDom->createElementNS( 'http://www.relaxng/ns/structure/1.0', 'rng:data' );
			$oNode = $oDataType->appendChild( $theNode );
			$oNode->setAttribute( 'type', $oAttDat->firstChild->getAttribute( 'type' ) );
		      }
		    else
		      { 
			$theNode = $oAttDom->createElementNS( 'http://www.relaxng/ns/structure/1.0', 'rng:ref' );
			$oNode = $oDataType->appendChild( $theNode );
			$oNode->setAttribute( 'name', $oAttDat->firstChild->getAttribute( 'name' ) );
		      }
		  }
	      }
	  }

	return $errResult;
      }

    public function getAttributeDefinition( $szAttribute, $szElement, $szModule, $szClass, &$oDef )
      {
	$this->getXPath( $oXPath );
	
	$oDef = new domDocument;
	$oRoot = $oDef->appendChild( new domElement( 'attDef' ) );
	
	$this->getAttributeDomByElementInModule( $szElement, $szModule, $szClass, $oAtts );

	$oXPath = new domxpath( $oAtts );
	$oAttDef = $oXPath->query( "/Element/att[child::name[node()='$szAttribute']]" )->item(0);

	$oAdd = $oRoot->appendChild( new domElement( 'added' ) );
	$oAdd->appendChild( new domText( $oAttDef->getAttribute( 'added' ) ) );

	foreach( $oAttDef->childNodes as $oChild )
	  {
	    switch( $oChild->nodeName )
	      {
	      case 'name':
		$oName = $oRoot->appendChild( new domElement( 'attName' ) );
		$oName->appendChild( new domText( $oChild->nodeValue ) );
		$oOpt = $oRoot->appendChild( new domElement( 'optional' ) );
		$oOpt->appendChild( new domText( $oChild->getAttribute( 'usage' ) ) );
		break;
	      case 'datatype':
		$oNode = $oRoot->appendChild( new domElement( 'datatype' ) );
		if ( $oChild->firstChild->nodeName == 'rng:text' )
		  {
		    $oNode->appendChild( new domText( 'text' ) );
		  }
		elseif( $oChild->firstChild->nodeName == 'rng:data' )
		  {
		    $oNode->appendChild( new domText( $oChild->firstChild->getAttribute( 'type' ) ) );
		  }
		elseif( $oChild->firstChild->nodeName == 'rng:ref' )
		  {
		    $oNode->appendChild( new domText( $oChild->firstChild->getAttribute( 'name' ) ) );
		  }
		break;
	      default:
		$oNode = $oRoot->appendChild( new domElement( $oChild->nodeName ) );
		$oNode->appendChild( new domText( $oChild->nodeValue ) );
		break;		      
	      }
	  }
      }


    public function getChangedAttributeClasses( &$aszClasses )
      {
	$this->getXPath( $oXPath );
        $aoClasses = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[child::tei:classSpec]/tei:classSpec/@ident" );

	$aszClasses = array();
	foreach( $aoClasses as $oClass )
	  {
	    $aszClasses[] = $oClass->nodeValue;
          }
      }

     public function getAttributeClassChanges( $szClass, &$oDom )
      {
	$oDom = new domDocument();
	$oClass = $oDom->appendChild( new domElement( 'class' ) );
	$oClass->setAttribute( 'ident', $szClass );

	$this->getXPath( $oXPath );
        $szModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[child::tei:classSpec[@ident='{$szClass}']]/@ident" )->item(0)->nodeValue;

	$oClass->appendChild( new domElement( 'module', $szModule ) );
	$oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[child::tei:classSpec[@ident='{$szClass}']]/tei:classSpec/tei:attList" )->item(0);

	$oAttList = $oDom->importNode( $oAttList, true );
	$oClass->appendChild( $oAttList );
      }


    public function getCustomizationTitle( &$szTitle )
      {
	$this->getXPath( $oXPath );
	$szTitle = $oXPath->query( "/tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:title" )->item(0)->nodeValue;
      }

    public function getCustomizationAuthor( &$szAuthor )
      {
	$this->getXPath( $oXPath );
	$szAuthor = $oXPath->query( "/tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:author" )->item(0)->nodeValue;
      }

    public function getCustomizationFilename( &$szFilename )
      {
	$this->getXPath( $oXPath );
	$szFilename = $oXPath->query( "/tei:TEI/@n" )->item(0)->nodeValue;
      }

    public function getCustomizationLanguage( &$szLanguage )
      {
	$this->getXPath( $oXPath );
	$szLanguage = $oXPath->query( "/tei:TEI/@lang" )->item(0)->nodeValue;
      }

    public function getCustomizationDescription( &$szDesc )
      {
	$this->getXPath( $oXPath );
	$szDesc = $oXPath->query( "/tei:TEI/tei:teiHeader/tei:fileDesc/tei:publicationStmt/tei:p" )->item(0)->nodeValue;
      }
    

    // #####################################################################
    // --- Change the Customization
    // #####################################################################

    public function addModule( $szModule, $bInclude = true )
      {
	$errResult = false;

	$this->getXPath( $oXPath );

        $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']" )->item(0);
        $oModuleRef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:moduleRef[@key='$szModule']" )->item(0);
        
        if (! is_object( $oModuleRef ) )
          {
            $oSchema = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']" )->item(0);
	    if ( is_object( $oSchema ) )
              {
                $theModRef = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'moduleRef' );
                $oModuleRef = $oSchema->appendChild( $theModRef );
		$oModuleRef->setAttribute( 'key', $szModule );
              }
          }

	if (! is_object( $oModule ) )
	  {
            $oP = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p" )->item(0);
            $theMod = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'module' );
            $oModule = $oP->appendChild( $theMod );

            if ( $bInclude )
              {
                $oModule->setAttribute( 'mode', 'change' );
              }
            else
              {
                $oModule->setAttribute( 'mode', 'delete' );
              }
	    $oModule->setAttribute( 'ident', $szModule );
          }
	else
          {
	    if ( $bInclude )
              {
                $oModule->setAttribute( 'mode', 'change' );
              }
          }

	return $errResult;
      }

    public function removeModule( $szModule )
      {
	$errResult = false;

	$this->getXPath( $oXPath );

        $oP = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p" )->item(0);
        $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']" )->item(0);
        $oModuleRef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:moduleRef[@key='$szModule']" )->item(0);
        $oSchema = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']" )->item(0);

	$oP->removeChild( $oModule );
        $oSchema->removeChild( $oModuleRef );

	return $errResult;
      }
	

    public function addElement( $aszConfig )
      {
	if (! preg_match( '/^[\w\d]+$/', $aszConfig[ 'name' ] ) )
	  {
	    throw new falseTagnameException( '', $aszConfig[ 'name' ] );
	  }


	$this->getXPath( $oXPath );
        $oSchema = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']" )->item(0);

        if ( is_object( $oSchema ) )
          {
            //check whether element already exists
            $oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='" . $aszConfig[ 'name' ] . "']" )->item(0);

	    if ( ! is_object( $oElementSpec ) )
	      {
		$theElementSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'elementSpec' );
		$oElementSpec = $oSchema->appendChild( $theElementSpec );
		$oElementSpec->setAttribute( 'ident', $aszConfig[ 'name' ] );
		$oElementSpec->setAttribute( 'mode', ( ( $aszConfig[ 'added' ] == 'true' ) ? 'add' : 'change' ) );
	      }

	    $oClasses = $oElementSpec->getElementsByTagname( 'classes' )->item(0);
	    if ( is_object( $oClasses ) )
	      {
		$oElementSpec->removeChild( $oClasses );
	      }
            $theClasses = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'classes' );
            $oClasses = $oElementSpec->appendChild( $theClasses );
	    
	    foreach( $aszConfig[ 'classes' ] as $szClass )
              {
		$theMemberOf = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'memberOf' );
		$oMember = $oClasses->appendChild( $theMemberOf );
		$oMember->setAttribute( 'key', $szClass );
              }

	    $oContent = $oElementSpec->getElementsByTagname( 'content' )->item(0);
	    if ( is_object( $oContent ) )
	      {
		$oElementSpec->removeChild( $oContent );
	      }
            $theContent = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'content' );
            $oContent = $oElementSpec->appendChild( $theContent );
	 
            switch( $aszConfig[ 'content' ] )
              {
                case 'empty':
                case 'text':
                  $oRNG = $this->createElementNS( 'http://www.relaxng/ns/structure/1.0', 'rng:' . $aszConfig[ 'content' ] );
                  $oContent->appendChild( $oRNG );
                  break; 
                default:
                  $oRNG = $this->createElementNS( 'http://www.relaxng/ns/structure/1.0', 'rng:ref' );
                  $oRef = $oContent->appendChild( $oRNG );
	          $oRef->setAttribute( 'name', $aszConfig[ 'content' ] );
                  break;
              }

	    $oDesc = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='{$aszConfig[ 'name' ]}']/tei:desc" )->item(0);

	    if ( is_object( $oDesc ) )
	      {
		$oElementSpec->removeChild( $oDesc );
	      }
            $theDesc = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'desc' );
            $oDesc = $oElementSpec->appendChild( $theDesc );
	    $oDesc->appendChild( new domText( $aszConfig[ 'description' ] ) );
          }
      }

    public function removeElementFromModule( $szElement, $szModule )
      {
	$this->getXPath( $oXPath );
        $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']" )->item(0);
	$oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@ident='$szElement']" )->item(0);
	
        if ( ! is_object( $oModule ) ) 
	  {
            $this->addModule( $szModule, false );
          }

	if (! is_object( $oElementSpec ) )
	  {
	    $theElementSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'elementSpec' );
 	    $oElementSpec = $oModule->appendChild( $theElementSpec );
	    $oElementSpec->setAttribute( 'ident', $szElement );
	    $oElementSpec->setAttribute( 'mode', 'delete' );
	  }
	else
	  {
	    $aoChildren = $oElementSpec->childNodes;
	    foreach( $aoChildren as $oChild )
	      {
		$oElementSpec->removeChild( $oChild );
	      }
	    $oElementSpec->setAttribute( 'mode', 'delete' );
	  }
	
      }

    public function includeElementInModule( $szElement, $szModule )
      {
	$this->getXPath( $oXPath );
        $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']" )->item(0);
	$oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@ident='$szElement']" )->item(0);

        if ( ! is_object( $oModule ) ) 
	  {
            $this->addModule( $szModule, false );
          }
	
	if ( is_object( $oElementSpec ) )
	  {
	    $oModule->removeChild( $oElementSpec );
	  }
      }

    public function changeElementNameInModule( $szOldName, $szNewName, $szModule )
      {
	$errResult = false;

	if ( preg_match( '/^[\w\d]+$/', $szNewName ) )
	  {
	    $this->getXPath( $oXPath );
            $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']" )->item(0);
	    $oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@ident='$szOldName']" )->item(0);
	
            if ( ! is_object( $oModule ) ) 
	      {
                $this->addModule( $szModule, false );
                $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']" )->item(0);
              }

  	    if (! is_object( $oElementSpec ) )
 	      {
                $theElementSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'elementSpec' );
 	        $oElementSpec = $oModule->appendChild( $theElementSpec );
	        $oElementSpec->setAttribute( 'ident', $szOldName );
	        $oElementSpec->setAttribute( 'mode', 'change' );
		
                $theAltIdent = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'altIdent' );
   	        $oAltIdent = $oElementSpec->appendChild( $theAltIdent );
	        $oAltIdent->appendChild( new domText( $szNewName ) );
	      }
  	    else
  	      {
	        $oElementSpec->setAttribute( 'mode', 'change' );

		$oAltIdent = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@ident='$szOldName']/tei:altIdent" )->item(0);
		
		if ( is_object( $oAltIdent ) )
		  {
		    $oElementSpec->removeChild( $oAltIdent );
		  }
	      
                $theAltIdent = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'altIdent' );
	        $oAltIdent = $oElementSpec->appendChild( $theAltIdent );
  	        $oAltIdent->appendChild( new domText( $szNewName ) );
 	     }
          }
	else
	  {
	    throw new falseTagnameException( $szOldName, $szNewName );
	    $errResult = $szOldName;
	  }
	
	return $errResult;
      }

    public function changeElementDescInModule( $szName, $szModule, $szDescription )
      {
	$this->getXPath( $oXPath );
	$oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']" )->item(0);
	$oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@ident='$szName']" )->item(0);
	
	if ( ! is_object( $oModule ) ) 
	  {
	    $this->addModule( $szModule, false );
	    $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']" )->item(0);
	  }
	
	if (! is_object( $oElementSpec ) )
	  {
	    $theElementSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'elementSpec' );
	    $oElementSpec = $oModule->appendChild( $theElementSpec );
	    $oElementSpec->setAttribute( 'ident', $szName );
	    $oElementSpec->setAttribute( 'mode', 'change' );
	    
	    $theDesc = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'desc' );
	    $oDesc = $oElementSpec->appendChild( $theDesc );
	    $oDesc->appendChild( new domText( $szDescription ) );
	  }
	else
	  {
	    $oElementSpec->setAttribute( 'mode', 'change' );

	    $oDesc = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@ident='$szName']/tei:desc" )->item(0);

	    if ( is_object( $oDesc ) )
	      {
		$oElementSpec->removeChild( $oDesc );
	      }
	    
	    $theDesc = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'desc' );
	    $oDesc = $oElementSpec->appendChild( $theDesc );
	    $oDesc->appendChild( new domText( $szDescription ) );
	  }
      }

    public function changeElementContentsInModule( $szElement, $szModule, $szContents )
      {
	$errResult = false;

	$szContents = preg_replace( '%\\\\"%', '"', $szContents );

	$this->getXPath( $oXPath );
	$oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']" )->item(0);
	$oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@ident='$szElement']" )->item(0);
	$oContent = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']/tei:elementSpec[@ident='$szElement']/tei:content" )->item(0);
	if ( ! is_object( $oModule ) ) 
	  {
	    $this->addModule( $szModule, false );
	    $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='$szModule']" )->item(0);
	  }

	if (! is_object( $oElementSpec ) )
	  {
       	    $theElementSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'elementSpec' );
	    $oElementSpec = $oModule->appendChild( $theElementSpec );
	    $oElementSpec->setAttribute( 'ident', $szElement );
	    $oElementSpec->setAttribute( 'mode', 'change' );
	  }


	if ( is_object( $oContent ) )
          {
	    $oElementSpec->removeChild( $oContent );
          }

	$oElementSpec->setAttribute( 'mode', 'change' );
	
	//Load Content
	$oConDom = new domDocument();
	if( @$oConDom->LoadXML( $szContents ) )
	  {
	    $oRoot = $oConDom->documentElement;
	    
	    $oRoot = $this->importNode( $oRoot, true );
	    $oElementSpec->appendChild( $oRoot );
	  }
	else
	  {
	    throw new falseContentsException( $szContents );
	    $errResult = true;
	  }

	return $errResult;
      }

    private function clearLanguageCustomization()
      {
	$this->getXPath( $oXPath );
	$oElements = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module/descendant::*[@type='lang']" );
	foreach( $oElements as $oElement )
	  { 
	    $oParent = $oElement->parentNode;
	    $oParent->removeChild( $oElement );
	  }
      }

    public function customizeLanguage( $szLanguage )
      {
        switch ( $szLanguage )
	  {
	    case  'clear':
	      $this->clearLanguageCustomization();
 	      break;
	    default:
	      $this->clearLanguageCustomization();
	      
              $oXSL = new domDocument();
              $oXSL->load( roma_schemaStylesheetDir . '/translate-odd.xsl' );
	    
              $oProc = new XsltProcessor();
              $oProc->importStylesheet( $oXSL );
              $oProc->setParameter( null, 'lang', $szLanguage );

              $oTmpDom = $oProc->transformToDoc( $this );
  	      $this->loadXML( $oTmpDom->SaveXML() );
	    break;
          }
      }
 
    public function replaceElementsClassesInModule( $szElement, $szModule, $aszClasses )
      {
	$this->getXPath( $oXPath );

	$oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
	$oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']" )->item(0);
	if ( ! is_object( $oModule ) ) 
	  {
	    $this->addModule( $szModule, false );
	    $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
	  }

	if (! is_object( $oElementSpec ) )
	  {
       	    $theElementSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'elementSpec' );
	    $oElementSpec = $oModule->appendChild( $theElementSpec );
	    $oElementSpec->setAttribute( 'ident', $szElement );
	    $oElementSpec->setAttribute( 'mode', 'change' );
	  }

	//check weather there are any classes yet
	$oClasses = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']/tei:classes" )->item(0);
	
	if ( is_object( $oClasses ) )
	  {
	    $oElementSpec->removeChild( $oClasses );
	  }

	$theClasses = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'classes' );
	$oClasses = $oElementSpec->appendChild( $theClasses );
	
	foreach ( $aszClasses as $szClass )
	  {
	    $theMemberOf = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'memberOf' );
	    $oMember = $oClasses->appendChild( $theMemberOf );
	    $oMember->setAttribute( 'key', $szClass );
	  }

      }  

    public function addAttribute( $aszConfig )
      {
	$errResult = false;
	if (! preg_match( '/^[\w\d]+$/', $aszConfig[ 'name' ] ) )
	  {
	    $errResult = true;
	    throw new falseTagnameException( '', $aszConfig[ 'name' ] );
	  }

	if ( ! $errResult )
	  {
	    $this->getXPath( $oXPath );

	    if ( $aszConfig[ 'module' ] != '' && $aszConfig[ 'class' ] == '' )
	      {
		$oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$aszConfig[ 'module' ]}']" )->item(0);

		$oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$aszConfig[ 'module' ]}']/tei:elementSpec[@ident='{$aszConfig[ 'element' ]}']" )->item(0);

		if ( ! is_object( $oModule ) ) 
		  {
		    $this->addModule( $aszConfig[ 'module' ], false );
		    $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$aszConfig[ 'module' ]}']" )->item(0);
		  }
		
		if (! is_object( $oElementSpec ) )
		  {
		    $theElementSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'elementSpec' );
		    $oElementSpec = $oModule->appendChild( $theElementSpec );
		    $oElementSpec->setAttribute( 'ident', $aszConfig[ 'element' ] );
		  }
		$oElementSpec->setAttribute( 'mode', 'change' );
	    
		$oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$aszConfig[ 'module' ]}']/tei:elementSpec[@ident='{$aszConfig[ 'element' ]}']/tei:attList" )->item(0);
	    
		if (! is_object( $oAttList ) )
		  {
		    $theAttList = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attList' );
		    $oAttList = $oElementSpec->appendChild( $theAttList );
		  }

		$oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$aszConfig[ 'module' ]}']/tei:elementSpec[@ident='{$aszConfig[ 'element' ]}']/tei:attList/tei:attDef[@ident='{$aszConfig[ 'name' ]}']" )->item(0);
	      }
	    elseif( $aszConfig[ 'class' ] == '' )
	      {
		$oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='" . $aszConfig[ 'element' ] . "']" )->item(0);

		$oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='{$aszConfig[ 'element' ]}']/tei:attList" )->item(0);
	    
		if (! is_object( $oAttList ) )
		  {
		    $theAttList = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attList' );
		    $oAttList = $oElementSpec->appendChild( $theAttList );
		  }

		$oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='{$aszConfig[ 'element' ]}']/tei:attList/tei:attDef[@ident='{$aszConfig[ 'name' ]}']" )->item(0);

	      }
	    else
	      {
		$oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$aszConfig[ 'module' ]}']" )->item(0);
		$oClassSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$aszConfig[ 'module' ]}']/tei:classSpec[@ident='{$aszConfig[ 'class' ]}']" )->item(0);
		
		if ( ! is_object( $oModule ) ) 
		  {
		    $this->addModule( $aszConfig[ 'module' ], false );
		    $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$aszConfig[ 'module' ]}']" )->item(0);
		  }
		
		if (! is_object( $oClassSpec ) )
		  {
		    $theClassSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'classSpec' );
		    $oClassSpec = $oModule->appendChild( $theClassSpec );
		    $oClassSpec->setAttribute( 'ident', $aszConfig[ 'class' ] );
		    $oClassSpec->setAttribute( 'mode', 'change' );
		  }
		
		
		$oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$aszConfig[ 'module' ]}']/tei:classSpec[@ident='{$aszConfig[ 'class' ]}']/tei:attList" )->item(0);
		
		if (! is_object( $oAttList ) )
		  {
		    $theAttList = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attList' );
		    $oAttList = $oClassSpec->appendChild( $theAttList );
		  }

		$oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$aszConfig[ 'module' ]}']/tei:classSpec[@ident='{$aszConfig[ 'class' ]}']/tei:attList/tei:attDef[@ident='{$aszConfig[ 'name' ]}']" )->item(0);
	      }

	    //attdef
	    if (! is_object( $oAttDef ) )
	      {
		$theAttDef = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attDef' );
		$oAttDef = $oAttList->appendChild( $theAttDef );
		$oAttDef->setAttribute( 'ident', $aszConfig[ 'name' ] );

		if ( $aszConfig[ 'added' ] == 'true' )
		  {
		    $oAttDef->setAttribute( 'mode', 'add' );
		  }
		else
		  {
		    $oAttDef->setAttribute( 'mode', 'change' );
		  }
	      }

	    //optional
	    $oAttDef->setAttribute( 'usage', ($aszConfig[ 'optional' ] == 'true' ) ? 'opt' : 'req' );


	    //content
	    $oContent = $oAttDef->getElementsByTagname( 'datatype' )->item(0);
	    if ( is_object( $oContent ) )
	      {
		$oAttDef->removeChild( $oContent );
	      }
	    $theContent = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'datatype' );
	    $oContent = $oAttDef->appendChild( $theContent );

	    switch ( $aszConfig[ 'content' ] )
	      {
	      case 'text':
		$oRNG = $this->createElementNS( 'http://www.relaxng/ns/structure/1.0', 'rng:' . $aszConfig[ 'content' ] );
		$oContent->appendChild( $oRNG );
		break; 
	      default:
		if( substr( $aszConfig[ 'content' ], 0, 9 ) == 'datatype.' )
		  {
		    $oRNG = $this->createElementNS( 'http://www.relaxng/ns/structure/1.0', 'rng:ref' );
		    $oRef = $oContent->appendChild( $oRNG );
		    $oRef->setAttribute( 'name', $aszConfig[ 'content' ] );
		  }
		else
		  {
		    $oRNG = $this->createElementNS( 'http://www.relaxng/ns/structure/1.0', 'rng:data' );
		    $oRef = $oContent->appendChild( $oRNG );
		    $oRef->setAttribute( 'type', $aszConfig[ 'content' ] );
		  }
		break;
	      }
	    
	    //default
	    $oDefault = $oAttDef->getElementsByTagname( 'default' )->item(0);
	    if ( is_object( $oDefault ) )
	      {
		$oAttDef->removeChild( $oDefault );
	      }
	    $theDefault = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'default' );
	    $oDefault = $oAttDef->appendChild( $theDefault );
	    $oDefault->appendChild( new domText( $aszConfig[ 'defaultValue' ] ) );

	    //desc
	    $oDesc = $oAttDef->getElementsByTagname( 'desc' )->item(0);
	    if ( is_object( $oDesc ) )
	      {
		$oAttDef->removeChild( $oDesc );
	      }
	    $theDesc = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'desc' );
	    $oDesc = $oAttDef->appendChild( $theDesc );
	    $oDesc->appendChild( new domText( $aszConfig[ 'description' ] ) );
	  }
	return $errResult;

      }

    public function includeAttributeInElement( $szAttribute, $szClass, $szModule, $szElement )
      {
	$this->getXPath( $oXPath );

	if ( $szModule != '' && $szClass == '')
	  {
	    $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
	    $oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']" )->item(0);
	    
	    if ( ! is_object( $oModule ) ) 
	      {
		$this->addModule( $szModule, false );
		$oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
	      }
	    
	    if (! is_object( $oElementSpec ) )
	      {
		$theElementSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'elementSpec' );
		$oElementSpec = $oModule->appendChild( $theElementSpec );
		$oElementSpec->setAttribute( 'ident', $szElement );
		$oElementSpec->setAttribute( 'mode', 'change' );
	      }
	    
	    $oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']/tei:attList" )->item(0);
	    
	    if (! is_object( $oAttList ) )
	      {
		$theAttList = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attList' );
		$oAttList = $oElementSpec->appendChild( $theAttList );
	      }
	    
	    $oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']/tei:attList/tei:attDef[@ident='$szAttribute']" )->item(0);
	  }
	elseif ( $szModule == '' && $szClass == '' )
	  {
	    $oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='" . $szElement . "']" )->item(0);
	    
	    $oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='{$szElement}']/tei:attList" )->item(0);
	    
	    if (! is_object( $oAttList ) )
	      {
		$theAttList = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attList' );
		$oAttList = $oElementSpec->appendChild( $theAttList );
	      }
	    
	    $oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='{$szElement}']/tei:attList/tei:attDef[@ident='{$szAttribute}']" )->item(0);
	  }
	else
	  {
	    $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
	    $oClassSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:classSpec[@ident='{$szClass}']" )->item(0);
	    
	    if ( ! is_object( $oModule ) ) 
	      {
		$this->addModule( $szModule, false );
		$oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
	      }
	    
	    if (! is_object( $oClassSpec ) )
	      {
		$theClassSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'classSpec' );
		$oClassSpec = $oModule->appendChild( $theClassSpec );
		$oClassSpec->setAttribute( 'ident', $szClass );
		$oClassSpec->setAttribute( 'mode', 'change' );
	      }

	
	    $oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:classSpec[@ident='{$szClass}']/tei:attList" )->item(0);
	    
	    if (! is_object( $oAttList ) )
	      {
		$theAttList = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attList' );
		$oAttList = $oClassSpec->appendChild( $theAttList );
	      }
	    
	    $oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:classSpec[@ident='{$szClass}']/tei:attList/tei:attDef[@ident='$szAttribute']" )->item(0);
	  }


	if ( ! is_object( $oAttDef ) )
	  {
	    //attdef
	    $theAttDef = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attDef' );
	    $oAttDef = $oAttList->appendChild( $theAttDef );
	    $oAttDef->setAttribute( 'ident', $szAttribute );
	  }

	$oAttDef->setAttribute( 'mode', 'change' );
      }
    


    public function excludeAttributeInElement( $szAttribute, $szClass, $szModule, $szElement )
      {
	$this->getXPath( $oXPath );

	if ( $szModule != '' && $szClass == '' )
	  {
	    $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
	    $oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']" )->item(0);
	    
	    if ( ! is_object( $oModule ) ) 
	      {
		$this->addModule( $szModule, false );
		$oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
	      }
	    
	    if (! is_object( $oElementSpec ) )
	      {
		$theElementSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'elementSpec' );
		$oElementSpec = $oModule->appendChild( $theElementSpec );
		$oElementSpec->setAttribute( 'ident', $szElement );
		$oElementSpec->setAttribute( 'mode', 'change' );
	      }
	
	    $oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']/tei:attList" )->item(0);
	    
	    if (! is_object( $oAttList ) )
	      {
		$theAttList = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attList' );
		$oAttList = $oElementSpec->appendChild( $theAttList );
	      }
	    
	    $oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']/tei:attList/tei:attDef[@ident='$szAttribute']" )->item(0);
	  }
	elseif ( $szModule == '' && $szClass == '' )
	  {
	    $oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='" . $szElement . "']" )->item(0);
	    
	    $oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='{$szElement}']/tei:attList" )->item(0);
	    
	    if (! is_object( $oAttList ) )
	      {
		$theAttList = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attList' );
		$oAttList = $oElementSpec->appendChild( $theAttList );
	      }
	    
	    $oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='{$szElement}']/tei:attList/tei:attDef[@ident='{$szAttribute}']" )->item(0);
	  }
	else
	  {
	    $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
	    $oClassSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:classSpec[@ident='{$szClass}']" )->item(0);
	    
	    if ( ! is_object( $oModule ) ) 
	      {
		$this->addModule( $szModule, false );
		$oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
	      }
	    
	    if (! is_object( $oClassSpec ) )
	      {
		$theClassSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'classSpec' );
		$oClassSpec = $oModule->appendChild( $theClassSpec );
		$oClassSpec->setAttribute( 'ident', $szClass );
		$oClassSpec->setAttribute( 'mode', 'change' );
	      }

	
	    $oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:classSpec[@ident='{$szClass}']/tei:attList" )->item(0);
	    
	    if (! is_object( $oAttList ) )
	      {
		$theAttList = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attList' );
		$oAttList = $oClassSpec->appendChild( $theAttList );
	      }
	    
	    $oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:classSpec[@ident='{$szClass}']/tei:attList/tei:attDef[@ident='$szAttribute']" )->item(0);
	  }

	if ( ! is_object( $oAttDef ) )
	  {
	    //attdef
	    $theAttDef = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attDef' );
	    $oAttDef = $oAttList->appendChild( $theAttDef );
	    $oAttDef->setAttribute( 'ident', $szAttribute );
	  }

	$oAttDef->setAttribute( 'mode', 'delete' );
      }

    public function changeAttributesName( $szOldName, $szNewName, $szClass, $szModule, $szElement )
      {
	$errResult = false;

	if ( preg_match( '/^[\w\d]+$/', $szNewName ) )
	  {
	    $this->getXPath( $oXPath );
	    
	    if ( $szModule != '' && $szClass == '' )
	      {
		$oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
		$oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']" )->item(0);
	    
		if ( ! is_object( $oModule ) ) 
		  {
		    $this->addModule( $szModule, false );
		    $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
		  }
		
		if (! is_object( $oElementSpec ) )
		  {
		    $theElementSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'elementSpec' );
		    $oElementSpec = $oModule->appendChild( $theElementSpec );
		    $oElementSpec->setAttribute( 'ident', $szElement );
		    $oElementSpec->setAttribute( 'mode', 'change' );
		  }
		
		$oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']/tei:attList" )->item(0);
	    
		if (! is_object( $oAttList ) )
		  {
		    $theAttList = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attList' );
		    $oAttList = $oElementSpec->appendChild( $theAttList );
		  }
		
		$oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']/tei:attList/tei:attDef[@ident='$szOldName']" )->item(0);
	      }
	    elseif ( $szClass != '' )
	      {
		$oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
		$oClassSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:classSpec[@ident='{$szClass}']" )->item(0);
		
		if ( ! is_object( $oModule ) ) 
		  {
		    $this->addModule( $szModule, false );
		    $oModule = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']" )->item(0);
		  }
		
		if (! is_object( $oClassSpec ) )
		  {
		    $theClassSpec = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'classSpec' );
		    $oClassSpec = $oModule->appendChild( $theClassSpec );
		    $oClassSpec->setAttribute( 'ident', $szClass );
		    $oClassSpec->setAttribute( 'mode', 'change' );
		  }
		
		
		$oAttList = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:classSpec[@ident='{$szClass}']/tei:attList" )->item(0);
		
		if (! is_object( $oAttList ) )
		  {
		    $theAttList = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attList' );
		    $oAttList = $oClassSpec->appendChild( $theAttList );
		  }
		
		$oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:classSpec[@ident='{$szClass}']/tei:attList/tei:attDef[@ident='$szOldName']" )->item(0);
	      }
	    
	    if ( ! is_object( $oAttDef ) )
	      {
		//attdef
		$theAttDef = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'attDef' );
		$oAttDef = $oAttList->appendChild( $theAttDef );
		$oAttDef->setAttribute( 'ident', $szOldName );
	      }
	    
	    $oAltIdent = $oAttDef->getElementsByTagName( 'altIdent' )->item(0);
	    if( is_object( $oAltIdent ) )
	      {
		$oAttDef->removeChild( $oAltIdent );
	      }
	    
	    $theAltIdent = $this->createElementNS( 'http://www.tei-c.org/ns/1.0', 'altIdent' );
	    $oAltIdent = $oAttDef->appendChild( $theAltIdent );
	    $oAltIdent->appendChild( new domText( $szNewName ) );
	  }
	else
	  {
	    $_SESSION[ 'addAttribute_ERROR' ] = roma_message_attributeNameError;	
	    $errResult = true;
	  }

	return $errResult;
      }

    public function deleteAttribute( $szAttribute, $szClass, $szModule, $szElement )
      {
	$this->getXPath( $oXPath );

	if ( $szModule != '' && $szClass == '' )
	  {
	    $oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:elementSpec[@ident='{$szElement}']/tei:attList/tei:attDef[@ident='{$szAttribute}']" )->item(0);
	  }
	elseif( $szClass == '' )
	  {
	    $oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='{$szElement}']/tei:attList/tei:attDef[@ident='{$szAttribute}']" )->item(0);
	  }
	else
	  {
	    $oAttDef = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:module[@ident='{$szModule}']/tei:classSpec[@ident='{$szClass}']/tei:attList/tei:attDef[@ident='{$szAttribute}']" )->item(0);
	  }

	$oAttDef->parentNode->removeChild( $oAttDef );
      }  


    public function includeAddedElement( $szElement )
      {
	$this->getXPath( $oXPath );
	
	$oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='{$szElement}']" )->item(0);

	$oElementSpec->setAttribute( 'mode', 'change' );
      }

    public function excludeAddedElement( $szElement )
      {
	$this->getXPath( $oXPath );
	
	$oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='{$szElement}']" )->item(0);

	$oElementSpec->setAttribute( 'mode', 'delete' );
      }

    public function deleteAddedElement( $szElement )
      {
	$errResult = false;

	$this->getXPath( $oXPath );
	$oElementSpec = $oXPath->query( "/tei:TEI/tei:text/tei:body/tei:p/tei:schema[@ident='mytei']/tei:elementSpec[@ident='{$szElement}']" )->item(0);
	if ( is_object( $oElementSpec ) )
	  {
	    $oElementSpec->parentNode->removeChild( $oElementSpec );
	  }
	else
	  {
	    $errResult = true;
	  }

	return $errResult;
      }


    public function setCustomizationTitle( $szTitle )
      {
	$this->getXPath( $oXPath );
	$oTitle = $oXPath->query( "/tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:title" )->item(0);
	if ( $oTitle->hasChildNodes() )
	  $oTitle->removeChild( $oTitle->firstChild );
	$oTitle->appendChild( new domText ( $szTitle ) );
      }

    public function setCustomizationDescription( $szDescription )
      {
	$this->getXPath( $oXPath );
	$oP = $oXPath->query( "/tei:TEI/tei:teiHeader/tei:fileDesc/tei:publicationStmt/tei:p" )->item(0);
	if ( $oP->hasChildNodes() )
	  $oP->removeChild( $oP->firstChild );
	$oP->appendChild( new domText ( $szDescription ) );
      }

    public function setCustomizationAuthor( $szAuthor )
      {
	$this->getXPath( $oXPath );
	$oAuthor = $oXPath->query( "/tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:author" )->item(0);
	if ( $oAuthor->hasChildNodes() )
	  $oAuthor->removeChild( $oAuthor->firstChild );
	$oAuthor->appendChild( new domText ( $szAuthor ) );
      }

    public function setCustomizationFilename( $szFilename )
      {
	$this->getXPath( $oXPath );
	$oTEI = $oXPath->query( "/tei:TEI" )->item(0);
	$oTEI->setAttribute( 'n', $szFilename );
      }

    public function setCustomizationLanguage( $szLanguage )
      {
	$this->getXPath( $oXPath );
	$oTEI = $oXPath->query( "/tei:TEI" )->item(0);
	$oTEI->setAttribute( 'lang', $szLanguage );
      }


    // #####################################################################
    // --- Little Helpers
    // #####################################################################

    protected function getSchemaRNGDom( &$oRNG )
      {
	$oXSL = new domDocument();
	$oXSL->load( roma_schemaStylesheetDir . '/odd2relax.xsl' );
	
	$oProc = new XsltProcessor();
	$oProc->importStylesheet( $oXSL );
	$oProc->setParameter( null, 'RNGDIR', '-' );

	$oRNG = $oProc->transformToDoc( $this );
      } 

    public function loadProgressBar()
      {
	echo '<script>';
	echo "showPgb();";
	echo '</script>';
	flush();
      }

    public function updateProgressBar( $nPercentage, $bIncrease = false, $nMax = 0 )
      {
	static $nLast = 0;
	if ( $bIncrease )
	  {
	    if ( $nMax > ( $nPercentage + $nLast ) )
	      {
		$nPercentage += $nLast;
	      }
	    else
	      {
		$nPercentage = $nLast;
	      }
	  }
	
	echo '<script>';
	echo "setPgb('pgbMain', '{$nPercentage}');";
	echo '</script>';
	flush();

	$nLast = $nPercentage;
      }

    // #####################################################################
    // --- Creating some Schema
    // #####################################################################

    public function createSchemaCompiledRNG( &$szRNG, $bBar = false )
      {
	if ( $bBar )
	  {
	    $this->loadProgressBar();
	    $this->updateProgressBar( '30' );
	  }
	$this->getSchemaRNGDom( $oRNG );
	if ( $bBar )
	    $this->updateProgressBar( '50' );

	
	$oXSL = new domDocument();
	$oXSL->load( roma_schemaStylesheetDir . '/P5/odds/expandincludes.xsl' );

	if ( $bBar )
	    $this->updateProgressBar( '60' );
	
	$oProc = new XsltProcessor();
	$oProc->importStylesheet( $oXSL );
	$oProc->setParameter( null, 'RNGDIR', '-' );

	$oCompRNG = $oProc->transformToDoc( $oRNG );

	if ( $bBar )
	    $this->updateProgressBar( '80' );
	    
	$szRNG = $oCompRNG->SaveXML();

	if ( $bBar )
	    $this->updateProgressBar( '100' );
      }

    public function createSchemaRNG( &$szRNG, $bBar = false )
      {
	if ( $bBar )
	  {
	    $this->loadProgressBar();
	    $this->updateProgressBar( '30' );
	  }
	$this->getSchemaRNGDom( $oRNG );
	if ( $bBar )
	    $this->updateProgressBar( '80' );

	$szRNG = $oRNG->SaveXML();

	if ( $bBar )
	    $this->updateProgressBar( '100' );
      }

    public function createSchemaRNC( &$szRNC, $bBar = false )
      {
	if ( $bBar )
	  {
	    $this->loadProgressBar();
	    $this->updateProgressBar( '30' );
	  }
	$this->getSchemaRNGDom( $oRNG );
	if ( $bBar )
	    $this->updateProgressBar( '50' );

	$oXSL = new domDocument();
	$oXSL->load( roma_schemaStylesheetDir . '/P5/odds/expandincludes.xsl' );
	
	$oProc = new XsltProcessor();
	$oProc->importStylesheet( $oXSL );
	$oProc->setParameter( null, 'RNGDIR', '-' );
	
	//Save File
	$szID = md5( uniqid(rand(), true ) );
	
	$szInputFile = roma_temporaryFilesDir . '/' . $szID . '.tmp';    
	$szOutputFile = roma_temporaryFilesDir . '/' . $szID . '.rnc';    
	file_put_contents( $szInputFile , $oProc->transformToDoc( $oRNG )->SaveXML() );

	if ( $bBar )
	    $this->updateProgressBar( '70' );

	ob_start();
	System( roma_trang . ' -I rng -O rnc ' . $szInputFile . ' ' . $szOutputFile  . ' 2>&1');
	$szError = ob_get_clean();
	ob_end_clean();

	if ( $bBar )
	    $this->updateProgressBar( '90' );


	if ( file_exists( $szOutputFile ) )
	  {
	    $szRNC = join( '', file( $szOutputFile ) );
	    unlink( $szOutputFile );
	  }
	unlink( $szInputFile );

	if ( $bBar )
	    $this->updateProgressBar( '100' );

	return $szError;
      }

    public function createSchemaXSD( &$szXSD, $bBar = false )
      {
	if ( $bBar )
	  {
	    $this->loadProgressBar();
	    $this->updateProgressBar( '30' );
	  }
	$this->getSchemaRNGDom( $oRNG );
	if ( $bBar )
	    $this->updateProgressBar( '50' );

	$oXSL = new domDocument();
	$oXSL->load( roma_schemaStylesheetDir . '/P5/odds/expandincludes.xsl' );
	
	$oProc = new XsltProcessor();
	$oProc->importStylesheet( $oXSL );
	$oProc->setParameter( null, 'RNGDIR', '-' );

	//Save File
	$szID = md5( uniqid(rand(), true ) );
	
	$szInputFile = roma_temporaryFilesDir . '/' . $szID . '.tmp';    
	$szOutputFile = roma_temporaryFilesDir . '/' . $szID . '.xsd';    
	file_put_contents( $szInputFile , $oProc->transformToDoc( $oRNG )->SaveXML() );
	

	if ( $bBar )
	    $this->updateProgressBar( '70' );
	
	ob_start();
	System( roma_trang . ' -I rng -O xsd -o disable-abstract-elements ' . $szInputFile . ' ' . $szOutputFile  . ' 2>&1');
	$szError = ob_get_clean();
	ob_end_clean();

	if ( $bBar )
	    $this->updateProgressBar( '90' );

	if ( file_exists( $szOutputFile ) )
	  {
	    $szXSD = join( '', file( $szOutputFile ) );
	    unlink( $szOutputFile );
	  }

	unlink( $szInputFile );

	if ( $bBar )
	    $this->updateProgressBar( '100' );

	return $szError;
      }

    public function createSchemaDTD( &$szDTD, $bBar = false )
      {
	if ( $bBar )
	  {
	    $this->loadProgressBar();
	    $this->updateProgressBar( '30' );
	  }
	$this->getSchemaRNGDom( $oRNG );
	if ( $bBar )
	    $this->updateProgressBar( '50' );


	$oXSL = new domDocument();
	$oXSL->load( roma_schemaStylesheetDir . '/P5/odds/expandincludes.xsl' );

	if ( $bBar )
	    $this->updateProgressBar( '60' );

	$oXSL2 = new domDocument();
	$oXSL2->load( roma_schemaStylesheetDir . '/P5/odds/nomorechoice.xsl' );

	if ( $bBar )
	    $this->updateProgressBar( '70' );
	
	$oProc = new XsltProcessor();
	$oProc->importStylesheet( $oXSL );
	$oProc->setParameter( null, 'RNGDIR', '-' );
	
	$oProc2 = new XsltProcessor();
	$oProc2->importStylesheet( $oXSL2 );
	$oProc2->setParameter( null, 'RNGDIR', '-' );
	
	//Save File
	$szID = md5( uniqid(rand(), true ) );
	
	$szInputFile = roma_temporaryFilesDir . '/' . $szID . '.tmp';    
	$szOutputFile = roma_temporaryFilesDir . '/' . $szID . '.dtd';    
	file_put_contents( $szInputFile , $oProc2->transformToDoc( $oProc->transformToDoc( $oRNG ) )->SaveXML() );

	if ( $bBar )
	    $this->updateProgressBar( '80' );
	
	ob_start();
	System( roma_trang . ' -I rng -O dtd ' . $szInputFile . ' ' . $szOutputFile  . ' 2>&1');
	$szError = ob_get_clean();
	ob_end_clean();

	if ( $bBar )
	    $this->updateProgressBar( '90' );
	
	if ( file_exists( $szOutputFile ) )
	  {
	    $szDTD = join( '', file( $szOutputFile ) );
	    unlink( $szOutputFile );
	  }	
       	unlink( $szInputFile );

	if ( $bBar )
	    $this->updateProgressBar( '100' );

	return $szError;
      }

  }

</script>
