.TH ROMA 1 "25th July 2012" "TEI .."
.SH NAME
roma \- compile a TEI ODD specification into schemas and dtd
.SH SYNOPSIS
.B roma
.RI [ options ]
.I oddfile
.I outputdir
.\"=====================================================================
.SH DESCRIPTION
This manual page is not meant to be exhaustive.  There
is some more information in the help files for the web version
of Roma, and plenty of
background data about ODDs in the TEI Guidelines.
.PP
.B roma
is used to generate XML RelaxNG or W3C schemas and DTDs 
from the the ODD source in
.IR oddfile
and (optionally) some documentation to go with them.
.\"=====================================================================
.SH OPTIONS
.B roma
accepts the following options:
.TP
.BI --xsl= \ URL
location of TEI XSLT stylesheets, defaulting to /usr/share/xml/tei/stylesheet
.TP
.BI --teiserver= \ URL
location of TEI eXist database server, defaulting to http://tei.oucs.ox.ac.uk/Query/
.TP
.BI --doc         
create expanded documented ODD
.TP
.BI --nodtd       
suppress DTD creation
.TP
.BI --norelax     
suppress RelaxNG creation
.TP
.BI --noxsd       
suppress W3C XML Schema creation
.TP
.BI --debug       
leave temporary files, etc.
.TP
.BI --localsource=
local copy of P5 sources
.TP
.BI --compile         
create compiled file odd
.TP
.BI --doc             
create expanded documented ODD (TEI Lite XML)
.TP
.BI --dochtml         
create HTML version of doc
.TP
.BI --doclang=LANG    
language for documentation
.TP
.BI --docpdf          
create PDF version of doc
.TP
.BI --lang=LANG       
language for names of attributes and elements
.TP
.BI --autoglobal      
adds global attribute class to all elements
.TP
.BI --schematron      
extract Schematron rules
.TP
.BI --isoschematron   
extract ISO Schematron rules
.TP
.BI --useteiversion   
use version data from TEI P5
.TP
.BI --parameterize    
create parameterized DTD
.TP
.BI --patternprefix=STRING
prefix RELAX NG patterns with STRING
.TP
.BI --schema=NAME     
select named schema spec
.TP
.BI --version         
which version of Roma is this

.\"=====================================================================
.SH BUGS
If the ODD specification is internally inconsistent (eg some element has
been deleted on which another element depends), then you may get
a Relax NG schema which is apparently OK, but which cannot be
translated into W3C schema. Because the conversions to DTD and Relax
are maintained separately, some constructs may cause one to fail but
not the other.
No attempt is made to trap error messages from 
.I trang
which is used to make W3C schemas.
.\"=====================================================================
.SH "SEE ALSO"
.BR trang (1)
