#!/bin/sh
R=/usr/share/xml/tei
T=$R/stylesheet
S=$R/schema/relaxng/p5/
simple=false
while test $# -gt 0; do
  case $1 in
    --xsl=*)    T=`echo $1 | sed 's/.*=//'`;;
    --simple)   simple=true;;
    --schema=*) S=`echo $1 | sed 's/.*=//'`;;
     *) break;;
  esac
  shift
done
N=`grep "<schemaSpec ident" $1 | sed 's/.*ident=\"\([^\"]*\)\".*/\1/'`
if test "x$1" = "x"; then
    echo Usage: Roma schemaspec [output directory]
    exit 1
fi
if test "x$2" = "x"; then
    export RESULTS=RomaResults
else
    export RESULTS=$2
fi
H=`pwd`
echo Roma starts
echo Process $1 to create $N.\{rng,rnc,dtd\} in $Results
mkdir -p $RESULTS
echo 1. make Relax NG from ODD
xsltproc  --stringparam verbose true --stringparam RNGDIR $RESULTS --stringparam schemaBaseURL $S $T/base/p5/odds/odd2relax.xsl $1
cd $RESULTS
xmllint --format $N.rng > x; mv x $N.rng
echo 2. make Relax NG compact from XML
trang $N.rng $N.rnc
echo 3. expand includes in Relax NG
xsltproc -o $N.compiled.rng $T/base/p5/odds/expandincludes.xsl $N.rng 
echo 4. convert expanded form to compact syntax
trang $N.compiled.rng $N.compiled.rnc
$simple && exit 
echo 5. simplify expanded form, convert to XSD and then mangle XSD
xsltproc -o $N.temp.rng $T/base/p5/odds/simplifyforxsd.xsl $N.compiled.rng 
trang  -o disable-abstract-elements $N.temp.rng $N.compiled.xsd && rm $N.temp.rng
xsltproc -o $N.xsd $T/base/p5/odds/manglexsd.xsl $N.compiled.xsd
rm $N.compiled.xsd
echo 6. simplify schema before attempting DTD conversion
xsltproc $T/base/p5/odds/nomorechoice.xsl $N.compiled.rng | \
xsltproc $T/base/p5/odds/simplifyfordtd.xsl - | \
xsltproc $T/base/p5/odds/simplifyfordtd.xsl - | \
xsltproc -o $N.temp2.rng $T/base/p5/odds/simplifyfordtd.xsl - 
echo 7. convert simplified form to DTD
trang $N.temp2.rng $N.dtd && rm $N.temp2.rng
perl -p -i -e 's/ns1://;s/xmlns:ns1/xmlns/' $N.dtd
echo 8. make expanded documented ODD
xsltproc $T/base/p5/odds/subsetGuidelines.xsl $H/$1 | xmllint --format - > $N.doc.xml 
