#!/bin/bash 
#
# Roma: transform TEI ODD files to schema and documentation
#
# Sebastian Rahtz, April 2005
# copyright: TEI Consortium
# license: GPL

makeRelax()
{
    echo "1. make Relax NG from ODD"
    xsltproc -o $N.compiled.odd \
    --stringparam TEISERVER $TEISERVER  \
    $TEIDIR/p5/odds/odd2odd.xsl $ODD 
    xsltproc  \
             --stringparam Method byvalue         \
             --stringparam RNGDIR $RESULTS       \
             $TEIDIR/p5/odds/odd2relax.xsl $N.compiled.odd
    cd $RESULTS
    xmllint --format $N.rng > $$.xml; mv $$.xml $N.rng
    echo "2. make Relax NG compact from XML"
    trang $N.rng $N.rnc  || die " trang fails"
    $doc && makeDOC
    $debug || rm  $N.compiled.odd
}

makeXSD()
{
    echo "3. make XSD from Relax NG and then mangle XSD"
    trang  -o disable-abstract-elements $N.rng $N.xsd || die " trang fails"
#    xsltproc -o $N.xsd $TEIDIR/p5/odds/manglexsd.xsl $N.temp.xsd
#    $debug || rm $N.temp.xsd
#    $debug || rm $N.temp1.rng  
    test -f xml.xsd && perl -p -i -e 's/<xs:import.*//' xml.xsd
}

makeDTD()
{
    echo "4. make DTD from Relax NG"
    trang $N.rng $N.dtd || die " trang fails"
    perl -p -i -e 's/ns1://;s/xmlns:ns1/xmlns/;s/xml:id CDATA/xml:id ID/' $N.dtd

}

makeDOC() 
{
    echo "5. make expanded documented ODD"
    xsltproc --stringparam TEISERVER $TEISERVER $TEIDIR/p5/odds/subsetGuidelines.xsl $H/$ODD \
    | xmllint --format - > $N.doc.xml 
}

die()
{
    echo; echo
    echo "ERROR: $@."
    D=`date "+%Y-%m-%d %H:%M:%S.%N"`
    echo "This was a fatal error. $D"
    exit 1
}

usageMsg()
{
echo "Roma -- reads in a TEI ODD file that specifies a schema, and tangles it"
echo "into RelaxNG schema, DTD, and W3C XML Schema, and can weave it into an"
echo "expanded, self-documented single ODD file. Note that only the first"
echo "<schemaSpec> encountered in the input ODD file is processed; all others"
echo "are ignored."
echo "  Usage: Roma [options] schemaspec [output_directory]"
echo "  options, shown with defaults:"
echo "  --xsl=$TEIDIR"
echo "  --teiserver=$TEISERVER"
echo "  options, binary switches:"
echo "  --doc         # create expanded documented ODD"
echo "  --nodtd       # suppress DTD creation"
echo "  --norelax     # suppress RelaxNG creation"
echo "  --noxsd       # suppress W3C XML Schema creation"
echo "  --debug       # leave temporary files, etc."
exit 1
}

# --------- main routine starts here --------- #
MYPATH=${0%/*}
R=/usr/share/xml/tei
TEISERVER=http://tei.oucs.ox.ac.uk/Query/
TEIDIR=$R/stylesheet/base
debug=false
dtd=true
relax=true
xsd=true
doc=false
while test $# -gt 0; do
  case $1 in
    --xsl=*)    TEIDIR=`echo $1 | sed 's/.*=//'`;;
    --doc)      doc=true;;
    --teiserver=*) TEISERVER=`echo $1 | sed 's/.*=//'`;;
    --nodtd)    dtd=false;;
    --norelax)  relax=false;;
    --noxsd)    xsd=false;;
    --debug)    debug=true;;
    --help)     usageMsg;;
    --schema=*) tempS=`echo $1 | sed 's/.*=//'`;S=`cd $tempS && /bin/pwd` || die "cannot change directory to $tempS" ;;
     *) if test "$1" = "${1#--}" ; then 
	   break
	else
	   echo "WARNING: Unrecognized option '$1' ignored"
	   echo "For usage syntax issue $0 --help"
	fi ;;
  esac
  shift
done
ODD=${1:?"no schemaspec (i.e., ODD file) supplied; for usage syntax issue $0 --help"}
test -f $ODD || die "file $ODD does not exist"
N=$(xsltproc $MYPATH/extract-schemaSpec-ident.xsl $1 | head -1)
N=${N:?"Unable to ascertain ident= of <schemaSpec>"}
RESULTS=${2:-RomaResults}
H=`pwd`
D=`date "+%Y-%m-%d %H:%M:%S.%N"`
echo "========= $D Roma starts, info:"
echo "Test for software: xmllint, xsltproc, trang, and perl"
which xmllint || die "you do not have xmllint"
which xsltproc || die "you do not have xsltproc"
which trang || die "you do not have trang"
which perl || die "you do not have perl"
echo "TEI stylesheet tree: $TEIDIR"
echo "Results to: $RESULTS"
test -d $S || die "schema dir $S does not exist"
test -d $TEIDIR || die "tei dir $TEIDIR does not exist"
mkdir -p $RESULTS || die "cannot make directory $RESULTS"
D=`date "+%Y-%m-%d %H:%M:%S.%N"`
echo "Process $ODD to create $N{.dtd|.xsd|.doc.xml|.rng|.rnc} in $RESULTS"
echo "========= $D Roma starts, execution:"
$relax && makeRelax
$xsd && makeXSD
$dtd && makeDTD
D=`date "+%Y-%m-%d %H:%M:%S.%N"`
echo "========= $D Roma ends"
