#!/bin/sh
cd ..
touch changed
/usr/bin/svn -q update P5 Stylesheets
find P5 Stylesheets -newer changed > /tmp/changed.files
if test -s /tmp/changed.files 
then 
 touch P5/Utilities/guidelines-web.xsl
fi
rm /tmp/changed.files