#!/bin/sh
profile=iso
while test $# -gt 0; do
  case $1 in
    --profile=*)  profile=`echo $1 | sed 's/.*=//'`;;
     *) if test "$1" = "${1#--}" ; then 
	   break
	else
	   echo "WARNING: Unrecognized option '$1' ignored"
	   echo "For usage syntax issue $0 --help"
	fi ;;
  esac
  shift
done

HERE=`pwd`
D=`dirname $1`
F=`basename $1 .xml`
THERE=`(cd $D; pwd)`
X=`dirname $0`
APPHOME=`(cd $X; pwd)`
TEMPDIR=/tmp/docx$$
TEMPLATES=$APPHOME/applications/$profile/docx-templates
XSL=$APPHOME/docx
mkdir -p $TEMPDIR/word/media
echo read $THERE/$F.xml
saxon $THERE/$F.xml $XSL/listgraphics.xsl DIR=$TEMPDIR/word/media > $TEMPDIR/fetch
cat $TEMPDIR/fetch
sh $TEMPDIR/fetch
rm $TEMPDIR/fetch
(cd $TEMPDIR/word/media; for i in *; do  exiftool -q -o $i.xmp $i; done)
cd $TEMPDIR
saxon -o $TEMPDIR/tmp.xml  $THERE/$F.xml $XSL/fixgraphics.xsl DIR=`pwd`/word
unzip -o -q $TEMPLATES/template.docx
saxon -o word/document.xml tmp.xml $APPHOME/applications/$profile/tei-docx.xsl  \
    debug=true styleDoc=$TEMPDIR/word/styles.xml word-directory=$TEMPDIR
rm -f tmp.xml word/media/*.xmp
test -f newContent_Types.xml && mv newContent_Types.xml \[Content_Types\].xml
mv docProps/newcore.xml docProps/core.xml 
rm -f $THERE/$F.docx
zip -q -r $THERE/$F.docx word _rels docProps customXml \[Content_Types\].xml
cd $HERE
rm -rf $TEMPDIR
echo wrote $F.docx in $THERE

