#!/bin/sh
#for i in Guidelines/en/*
#do
# X=`basename $i`
# (cd Guidelines/fr; ln -s ../en/$X $X)
#done
#rm Guidelines/fr/HD.xml
#mv french/hd.odd Guidelines/fr/HD.xml
#for i in Guidelines/fr/HD.xml
#do
# sed -f ents.sed $i > tmp
# mv tmp $i
#done

for i in french/*.odd
do
 N=`xsltproc getident.xsl $i`
 echo french for $i to $N
    xsltproc --stringparam newLang fr --stringparam newFile $i \
    mergeLang.xsl Guidelines/Odds/$N.xml \
	| xmllint --format --encode utf-8 - > tmp
    mv tmp Guidelines/Odds/$N.xml
done

for i in chinese/*.odd
do
 N=`xsltproc getident.xsl $i`
 echo chinese for $i to $N
    xsltproc --stringparam newLang zh-tw --stringparam newFile $i \
    mergeLang.xsl Guidelines/Odds/$N.xml | xmllint --format --encode utf-8 - > tmp
    mv tmp Guidelines/Odds/$N.xml
done