#!/bin/sh
rm -rf Guidelines/fr
mkdir Guidelines/fr
for i in Guidelines/en/*
do
 X=`basename $i`
 (cd Guidelines/fr; ln -s ../en/$X $X)
done
rm Guidelines/fr/HD.xml
cp ../french/hd.odd Guidelines/fr/HD.xml
for i in Guidelines/fr/HD.xml
do
 sed -f ents.sed $i > tmp
 mv tmp $i
done

for i in `ls HD/*.odd | sed 's/HD.hd.odd//'`
do
 X=`basename $i`
 N=`xsltproc getident.xsl $i`
 if test -f ../french/$X
 then
 echo french for $i
    xsltproc --stringparam newLang fr --stringparam newFile ../french/$X \
    mergeLang.xsl $i | xmllint --format --encode utf-8 - > Guidelines/Odds/$N.xml
 fi
 if test -f ../chinese/$X
 then
 echo chinese for $i
    xsltproc --stringparam newLang zh-tw --stringparam newFile ../chinese/$X \
    mergeLang.xsl Guidelines/Odds/$N.xml | xmllint --format --encode utf-8 - > tmp
    mv tmp Guidelines/Odds/$N.xml
 fi
done