#!/bin/sh
# Rebuild TEI eXist database
# Sebastian Rahtz
# 2005-04-22
# License: GPL

X=/usr/share/xml/tei/xquery
S=/usr/share/xml/tei/odd

cd /tmp
perl $X/addtoexist.pl --remove=/db/TEI
perl $X/addtoexist.pl --remove=/db/system/config/db/TEI/index.xconf
xsltproc -o tei.xml $X/simplify.xsl  $S/Source/guidelines-en.xml
perl $X/addtoexist.pl -c /db/system/config/db/TEI -s $X/index.xconf
perl $X/addtoexist.pl -c /db/TEI -s tei.xml
rm tei.xml