; -*- coding: iso-2022-7bit  -*-
;;; x0213-char.el -- JIS X 0213 character name utility.

;; Copyright (C) 2000 KAWABATA, Taichi

;; Keywords: mule, multilingual, Mule-UCS, JIS X 0213

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; if not, write to the Free Software
;; Foundation, Inc., 59 Temple Place - Suite 330,
;; Boston, MA 02111-1307, USA.

(require 'x0213-util)

(let 
 ((jisx0213-charnames
   '((?　 . "IDEOGRAPHIC SPACE")
     (?、 . "IDEOGRAPHIC COMMA")
     (?。 . "IDEOGRAPHIC FULL STOP")
     (?， . "COMMA")
     (?． . "FULL STOP")
     (?・ . "KATAKANA MIDDLE DOT")
     (?： . "COLON")
     (?； . "SEMICOLON")
     (?？ . "QUESTION MARK")
     (?！ . "EXCLAMATION MARK")
     (?゛ . "KATAKANA-HIRAGANA VOICED SOUND MARK")
     (?゜ . "KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK")
     (?´ . "ACUTE ACCENT")
     (?｀ . "GRAVE ACCENT")
     (?¨ . "DIAERESIS")
     (?＾ . "CIRCUMFLEX ACCENT")
     (?￣ . "OVERLINE")
     (?＿ . "LOW LINE")
     (?ヽ . "KATAKANA ITERATION MARK")
     (?ヾ . "KATAKANA VOICED ITERATION MARK")
     (?ゝ . "HIRAGANA ITERATION MARK")
     (?ゞ . "HIRAGANA VOICED ITERATION MARK")
     (?〃 . "DITTO MARK")
     (?仝 . "CJK UNIFIED IDEOGRAPH-4EDD")
     (?々 . "IDEOGRAPHIC ITERATION MARK")
     (?〆 . "IDEOGRAPHIC CLOSING MARK")
     (?〇 . "IDEOGRAPHIC NUMBER ZERO")
     (?ー . "KATAKANA-HIRAGANA PROLONGED SOUND MARK")
     (?― . "EM DASH")
     (?‐ . "HYPHEN")
     (?／ . "SOLIDUS")
     (?＼ . "REVERSE SOLIDUS")
     (?〜 . "WAVE DASH")
     (?‖ . "DOUBLE VERTICAL LINE")
     (?｜ . "VERTICAL LINE")
     (?… . "HORIZONTAL ELLIPSIS")
     (?‥ . "TWO DOT LEADER")
     (?‘ . "LEFT SINGLE QUOTATION MARK")
     (?’ . "RIGHT SINGLE QUOTATION MARK")
     (?“ . "LEFT DOUBLE QUOTATION MARK")
     (?” . "RIGHT DOUBLE QUOTATION MARK")
     (?（ . "LEFT PARENTHESIS")
     (?） . "RIGHT PARENTHESIS")
     (?〔 . "LEFT TORTOISE SHELL BRACKET")
     (?〕 . "RIGHT TORTOISE SHELL BRACKET")
     (?［ . "LEFT SQUARE BRACKET")
     (?］ . "RIGHT SQUARE BRACKET")
     (?｛ . "LEFT CURLY BRACKET")
     (?｝ . "RIGHT CURLY BRACKET")
     (?〈 . "LEFT ANGLE BRACKET")
     (?〉 . "RIGHT ANGLE BRACKET")
     (?《 . "LEFT DOUBLE ANGLE BRACKET")
     (?》 . "RIGHT DOUBLE ANGLE BRACKET")
     (?「 . "LEFT CORNER BRACKET")
     (?」 . "RIGHT CORNER BRACKET")
     (?『 . "LEFT WHITE CORNER BRACKET")
     (?』 . "RIGHT WHITE CORNER BRACKET")
     (?【 . "LEFT BLACK LENTICULAR BRACKET")
     (?】 . "RIGHT BLACK LENTICULAR BRACKET")
     (?＋ . "PLUS SIGN")
     (?− . "MINUS SIGN")
     (?± . "PLUS-MINUS SIGN")
     (?× . "MULTIPLICATION SIGN")
     (?÷ . "DIVISION SIGN")
     (?＝ . "EQUALS SIGN")
     (?≠ . "NOT EQUAL TO")
     (?＜ . "LESS-THAN SIGN")
     (?＞ . "GREATER-THAN SIGN")
     (?≦ . "LESS-THAN OVER EQUAL TO")
     (?≧ . "GREATER-THAN OVER EQUAL TO")
     (?∞ . "INFINITY")
     (?∴ . "THEREFORE")
     (?♂ . "MALE SIGN")
     (?♀ . "FEMALE SIGN")
     (?° . "DEGREE SIGN")
     (?′ . "PRIME")
     (?″ . "DOUBLE PRIME")
     (?℃ . "DEGREE CELSIUS")
     (?￥ . "YEN SIGN")
     (?＄ . "DOLLAR SIGN")
     (?¢ . "CENT SIGN")
     (?£ . "POUND SIGN")
     (?％ . "PERCENT SIGN")
     (?＃ . "NUMBER SIGN")
     (?＆ . "AMPERSAND")
     (?＊ . "ASTERISK")
     (?＠ . "COMMERCIAL AT")
     (?§ . "SECTION SIGN")
     (?☆ . "WHITE STAR")
     (?★ . "BLACK STAR")
     (?○ . "WHITE CIRCLE")
     (?● . "BLACK CIRCLE")
     (?◎ . "BULLSEYE")
     (?◇ . "WHITE DIAMOND")
     (?◆ . "BLACK DIAMOND")
     (?□ . "WHITE SQUARE")
     (?■ . "BLACK SQUARE")
     (?△ . "WHITE UP-POINTING TRIANGLE")
     (?▲ . "BLACK UP-POINTING TRIANGLE")
     (?▽ . "WHITE DOWN-POINTING TRIANGLE")
     (?▼ . "BLACK DOWN-POINTING TRIANGLE")
     (?※ . "REFERENCE MARK")
     (?〒 . "POSTAL MARK")
     (?→ . "RIGHTWARDS ARROW")
     (?← . "LEFTWARDS ARROW")
     (?↑ . "UPWARDS ARROW")
     (?↓ . "DOWNWARDS ARROW")
     (?〓 . "GETA MARK")
     (?＇ . "APOSTROPHE")
     (?＂ . "QUOTATION MARK")
     (?－ . "HYPHEN-MINUS")
     (?~ . "TILDE")
     (?〳 . "VERTICAL KANA REPEAT MARK UPPER HALF")
     (?〴 . "VERTICAL KANA REPEAT WITH VOICED SOUND MARK UPPER HALF")
     (?〵 . "VERTICAL KANA REPEAT MARK LOWER HALF")
     (?〻 . "ITERATION MARK") ; tentative
     (?〼 . "MASU MARK") ; tentative
     (?ヿ . "KATAKANA DIGRAPH KOTO") ; tentative
     (?ゟ . "HIRAGANA DIGRAPH YORI") ; tentative
     (?∈ . "ELEMENT OF")
     (?∋ . "CONTAINS AS MEMBER")
     (?⊆ . "SUBSET OF OR EQUAL TO")
     (?⊇ . "SUPERSET OF OR EQUAL TO")
     (?⊂ . "SUBSET OF")
     (?⊃ . "SUPERSET OF")
     (?∪ . "UNION")
     (?∩ . "INTERSECTION")
     (?⊄ . "NOT A SUBSET OF")
     (?⊅ . "NOT A SUPERSET OF")
     (?⊊ . "SUBSET OF WITH NOT EQUAL TO")
     (?⊋ . "SUPERSET OF WITH NOT EQUAL TO")
     (?∉ . "NOT AN ELEMENT OF")
     (?∅ . "EMPTY SET")
     (?⌅ . "PROJECTIVE")
     (?⌆ . "PERSPECTIVE")
     (?∧ . "LOGICAL AND")
     (?∨ . "LOGICAL OR")
     (?¬ . "NOT SIGN")
     (?⇒ . "RIGHTWARDS DOUBLE ARROW")
     (?⇔ . "LEFT RIGHT DOUBLE ARROW")
     (?∀ . "FOR ALL")
     (?∃ . "THERE EXISTS")
     (?⊕ . "CIRCLED PLUS")
     (?⊖ . "CIRCLED MINUS")
     (?⊗ . "CIRCLED TIMES")
     (?∥ . "PARALLEL TO")
     (?∦ . "NOT PARALLEL TO")
     (?⦅ . "LEFT WHITE PARENTHESIS") ; tentative
     (?⦆ . "RIGHT WHITE PARENTHESIS") ; tentative
     (?〘 . "LEFT WHITE TORTOISE SHELL BRACKET")
     (?〙 . "RIGHT WHITE TORTOISE SHELL BRACKET")
     (?〖 . "LEFT WHITE LENTICULAR BRACKET")
     (?〗 . "RIGHT WHITE LENTICULAR BRACKET")
     (?∠ . "ANGLE")
     (?⊥ . "UP TACK")
     (?⌒ . "ARC")
     (?∂ . "PARTIAL DIFFERENTIAL")
     (?∇ . "NABLA")
     (?≡ . "IDENTICAL TO")
     (?≒ . "APPROXIMATELY EQUAL TO OR THE IMAGE OF")
     (?≪ . "MUCH LESS-THAN")
     (?≫ . "MUCH GREATER-THAN")
     (?√ . "SQUARE ROOT")
     (?∽ . "REVERSED TILDE")
     (?∝ . "PROPORTIONAL TO")
     (?∵ . "BECAUSE")
     (?∫ . "INTEGRAL")
     (?∬ . "DOUBLE INTEGRAL")
     (?≢ . "NOT IDENTICAL TO")
     (?≃ . "ASYMPTOTICALLY EQUAL TO")
     (?≅ . "APPROXIMATELY EQUAL TO")
     (?≈ . "ALMOST EQUAL TO")
     (?≶ . "LESS-THAN OR GREATER-THAN")
     (?≷ . "GREATER-THAN OR LESS-THAN")
     (?↔ . "LEFT RIGHT ARROW")
     (?Å . "ANGSTROM SIGN")
     (?‰ . "PER MILLE SIGN")
     (?♯ . "MUSIC SHARP SIGN")
     (?♭ . "MUSIC FLAT SIGN")
     (?♪ . "EIGHTH NOTE")
     (?† . "DAGGER")
     (?‡ . "DOUBLE DAGGER")
     (?¶ . "PILCROW SIGN")
     (?♮ . "MUSIC NATURAL SIGN")
     (?♫ . "BEAMED EIGHTH NOTES")
     (?♬ . "BEAMED SIXTEENTH NOTES")
     (?♩ . "QUARTER NOTE")
     (?◯ . "LARGE CIRCLE")
     (?▷ . "WHITE RIGHT-POINTING TRIANGLE")
     (?▶ . "BLACK RIGHT-POINTING TRIANGLE")
     (?◁ . "WHITE LEFT-POINTING TRIANGLE")
     (?◀ . "BLACK LEFT-POINTING TRIANGLE")
     (?↗ . "NORTH EAST ARROW")
     (?↘ . "SOUTH EAST ARROW")
     (?↖ . "NORTH WEST ARROW")
     (?↙ . "SOUTH WEST ARROW")
     (?⇄ . "RIGHTWARDS ARROW OVER LEFTWARDS ARROW")
     (?⇨ . "RIGHTWARDS WHITE ARROW")
     (?⇦ . "LEFTWARDS WHITE ARROW")
     (?⇧ . "UPWARDS WHITE ARROW")
     (?⇩ . "DOWNWARDS WHITE ARROW")
     (?⤴ . "RIGHTWARD ARROW WITH CURVE UPWARD") ; tentative
     (?⤵ . "RIGHTWARD ARROW WITH CURVE DOWNWARD") ; tentative
     (?０ . "DIGIT ZERO")
     (?１ . "DIGIT ONE")
     (?２ . "DIGIT TWO")
     (?３ . "DIGIT THREE")
     (?４ . "DIGIT FOUR")
     (?５ . "DIGIT FIVE")
     (?６ . "DIGIT SIX")
     (?７ . "DIGIT SEVEN")
     (?８ . "DIGIT EIGHT")
     (?９ . "DIGIT NINE")
     (?⦿ . "CIRCLED BULLET") ; tentative
     (?◉ . "FISHEYE")
     (?〽 . "PART-ALTERNATION MARK") ; tentative
     (?﹆ . "WHITE SESAME DOT") ; tentative
     (?﹅ . "SESAME DOT") ; tentative
     (?◦ . "WHITE BULLET")
     (?• . "BULLET")
     (?Ａ . "LATIN CAPITAL LETTER A")
     (?Ｂ . "LATIN CAPITAL LETTER B")
     (?Ｃ . "LATIN CAPITAL LETTER C")
     (?Ｄ . "LATIN CAPITAL LETTER D")
     (?Ｅ . "LATIN CAPITAL LETTER E")
     (?Ｆ . "LATIN CAPITAL LETTER F")
     (?Ｇ . "LATIN CAPITAL LETTER G")
     (?Ｈ . "LATIN CAPITAL LETTER H")
     (?Ｉ . "LATIN CAPITAL LETTER I")
     (?Ｊ . "LATIN CAPITAL LETTER J")
     (?Ｋ . "LATIN CAPITAL LETTER K")
     (?Ｌ . "LATIN CAPITAL LETTER L")
     (?Ｍ . "LATIN CAPITAL LETTER M")
     (?Ｎ . "LATIN CAPITAL LETTER N")
     (?Ｏ . "LATIN CAPITAL LETTER O")
     (?Ｐ . "LATIN CAPITAL LETTER P")
     (?Ｑ . "LATIN CAPITAL LETTER Q")
     (?Ｒ . "LATIN CAPITAL LETTER R")
     (?Ｓ . "LATIN CAPITAL LETTER S")
     (?Ｔ . "LATIN CAPITAL LETTER T")
     (?Ｕ . "LATIN CAPITAL LETTER U")
     (?Ｖ . "LATIN CAPITAL LETTER V")
     (?Ｗ . "LATIN CAPITAL LETTER W")
     (?Ｘ . "LATIN CAPITAL LETTER X")
     (?Ｙ . "LATIN CAPITAL LETTER Y")
     (?Ｚ . "LATIN CAPITAL LETTER Z")
     (?∓ . "MINUS-OR-PLUS SIGN")
     (?ℵ . "ALEF SYMBOL")
     (?ℏ . "PLANCK CONSTANT OVER TWO PI")
     (?㏋ . "SQUARE HP")
     (?ℓ . "SCRIPT SMALL L")
     (?℧ . "INVERTED OHM SIGN")
     (?ａ . "LATIN SMALL LETTER A")
     (?ｂ . "LATIN SMALL LETTER B")
     (?ｃ . "LATIN SMALL LETTER C")
     (?ｄ . "LATIN SMALL LETTER D")
     (?ｅ . "LATIN SMALL LETTER E")
     (?ｆ . "LATIN SMALL LETTER F")
     (?ｇ . "LATIN SMALL LETTER G")
     (?ｈ . "LATIN SMALL LETTER H")
     (?ｉ . "LATIN SMALL LETTER I")
     (?ｊ . "LATIN SMALL LETTER J")
     (?ｋ . "LATIN SMALL LETTER K")
     (?ｌ . "LATIN SMALL LETTER L")
     (?ｍ . "LATIN SMALL LETTER M")
     (?ｎ . "LATIN SMALL LETTER N")
     (?ｏ . "LATIN SMALL LETTER O")
     (?ｐ . "LATIN SMALL LETTER P")
     (?ｑ . "LATIN SMALL LETTER Q")
     (?ｒ . "LATIN SMALL LETTER R")
     (?ｓ . "LATIN SMALL LETTER S")
     (?ｔ . "LATIN SMALL LETTER T")
     (?ｕ . "LATIN SMALL LETTER U")
     (?ｖ . "LATIN SMALL LETTER V")
     (?ｗ . "LATIN SMALL LETTER W")
     (?ｘ . "LATIN SMALL LETTER X")
     (?ｙ . "LATIN SMALL LETTER Y")
     (?ｚ . "LATIN SMALL LETTER Z")
     (?゠ . "DOUBLE HYPHEN") ; tentative
     (?– . "EN DASH")
     (?⧺ . "DOUBLE PLUS") ; tentative
     (?⧻ . "TRIPLE PLUS") ; tentative
     (?ぁ . "HIRAGANA LETTER SMALL A")
     (?あ . "HIRAGANA LETTER A")
     (?ぃ . "HIRAGANA LETTER SMALL I")
     (?い . "HIRAGANA LETTER I")
     (?ぅ . "HIRAGANA LETTER SMALL U")
     (?う . "HIRAGANA LETTER U")
     (?ぇ . "HIRAGANA LETTER SMALL E")
     (?え . "HIRAGANA LETTER E")
     (?ぉ . "HIRAGANA LETTER SMALL O")
     (?お . "HIRAGANA LETTER O")
     (?か . "HIRAGANA LETTER KA")
     (?が . "HIRAGANA LETTER GA")
     (?き . "HIRAGANA LETTER KI")
     (?ぎ . "HIRAGANA LETTER GI")
     (?く . "HIRAGANA LETTER KU")
     (?ぐ . "HIRAGANA LETTER GU")
     (?け . "HIRAGANA LETTER KE")
     (?げ . "HIRAGANA LETTER GE")
     (?こ . "HIRAGANA LETTER KO")
     (?ご . "HIRAGANA LETTER GO")
     (?さ . "HIRAGANA LETTER SA")
     (?ざ . "HIRAGANA LETTER ZA")
     (?し . "HIRAGANA LETTER SI")
     (?じ . "HIRAGANA LETTER ZI")
     (?す . "HIRAGANA LETTER SU")
     (?ず . "HIRAGANA LETTER ZU")
     (?せ . "HIRAGANA LETTER SE")
     (?ぜ . "HIRAGANA LETTER ZE")
     (?そ . "HIRAGANA LETTER SO")
     (?ぞ . "HIRAGANA LETTER ZO")
     (?た . "HIRAGANA LETTER TA")
     (?だ . "HIRAGANA LETTER DA")
     (?ち . "HIRAGANA LETTER TI")
     (?ぢ . "HIRAGANA LETTER DI")
     (?っ . "HIRAGANA LETTER SMALL TU")
     (?つ . "HIRAGANA LETTER TU")
     (?づ . "HIRAGANA LETTER DU")
     (?て . "HIRAGANA LETTER TE")
     (?で . "HIRAGANA LETTER DE")
     (?と . "HIRAGANA LETTER TO")
     (?ど . "HIRAGANA LETTER DO")
     (?な . "HIRAGANA LETTER NA")
     (?に . "HIRAGANA LETTER NI")
     (?ぬ . "HIRAGANA LETTER NU")
     (?ね . "HIRAGANA LETTER NE")
     (?の . "HIRAGANA LETTER NO")
     (?は . "HIRAGANA LETTER HA")
     (?ば . "HIRAGANA LETTER BA")
     (?ぱ . "HIRAGANA LETTER PA")
     (?ひ . "HIRAGANA LETTER HI")
     (?び . "HIRAGANA LETTER BI")
     (?ぴ . "HIRAGANA LETTER PI")
     (?ふ . "HIRAGANA LETTER HU")
     (?ぶ . "HIRAGANA LETTER BU")
     (?ぷ . "HIRAGANA LETTER PU")
     (?へ . "HIRAGANA LETTER HE")
     (?べ . "HIRAGANA LETTER BE")
     (?ぺ . "HIRAGANA LETTER PE")
     (?ほ . "HIRAGANA LETTER HO")
     (?ぼ . "HIRAGANA LETTER BO")
     (?ぽ . "HIRAGANA LETTER PO")
     (?ま . "HIRAGANA LETTER MA")
     (?み . "HIRAGANA LETTER MI")
     (?む . "HIRAGANA LETTER MU")
     (?め . "HIRAGANA LETTER ME")
     (?も . "HIRAGANA LETTER MO")
     (?ゃ . "HIRAGANA LETTER SMALL YA")
     (?や . "HIRAGANA LETTER YA")
     (?ゅ . "HIRAGANA LETTER SMALL YU")
     (?ゆ . "HIRAGANA LETTER YU")
     (?ょ . "HIRAGANA LETTER SMALL YO")
     (?よ . "HIRAGANA LETTER YO")
     (?ら . "HIRAGANA LETTER RA")
     (?り . "HIRAGANA LETTER RI")
     (?る . "HIRAGANA LETTER RU")
     (?れ . "HIRAGANA LETTER RE")
     (?ろ . "HIRAGANA LETTER RO")
     (?ゎ . "HIRAGANA LETTER SMALL WA")
     (?わ . "HIRAGANA LETTER WA")
     (?ゐ . "HIRAGANA LETTER WI")
     (?ゑ . "HIRAGANA LETTER WE")
     (?を . "HIRAGANA LETTER WO")
     (?ん . "HIRAGANA LETTER N")
     (?ゔ . "HIRAGANA LETTER VU")
     (?ゕ . "HIRAGANA LETTER SMALL KA") ; tentative
     (?ゖ . "HIRAGANA LETTER SMALL KE") ; tentative
     (?か゚ . "HIRAGANA LETTER BIDAKUON NGA") ; tentative
     (?き゚ . "HIRAGANA LETTER BIDAKUON NGI") ; tentative
     (?く゚ . "HIRAGANA LETTER BIDAKUON NGU") ; tentative
     (?け゚ . "HIRAGANA LETTER BIDAKUON NGE") ; tentative
     (?こ゚ . "HIRAGANA LETTER BIDAKUON NGO") ; tentative
     (?ァ . "KATAKANA LETTER SMALL A")
     (?ア . "KATAKANA LETTER A")
     (?ィ . "KATAKANA LETTER SMALL I")
     (?イ . "KATAKANA LETTER I")
     (?ゥ . "KATAKANA LETTER SMALL U")
     (?ウ . "KATAKANA LETTER U")
     (?ェ . "KATAKANA LETTER SMALL E")
     (?エ . "KATAKANA LETTER E")
     (?ォ . "KATAKANA LETTER SMALL O")
     (?オ . "KATAKANA LETTER O")
     (?カ . "KATAKANA LETTER KA")
     (?ガ . "KATAKANA LETTER GA")
     (?キ . "KATAKANA LETTER KI")
     (?ギ . "KATAKANA LETTER GI")
     (?ク . "KATAKANA LETTER KU")
     (?グ . "KATAKANA LETTER GU")
     (?ケ . "KATAKANA LETTER KE")
     (?ゲ . "KATAKANA LETTER GE")
     (?コ . "KATAKANA LETTER KO")
     (?ゴ . "KATAKANA LETTER GO")
     (?サ . "KATAKANA LETTER SA")
     (?ザ . "KATAKANA LETTER ZA")
     (?シ . "KATAKANA LETTER SI")
     (?ジ . "KATAKANA LETTER ZI")
     (?ス . "KATAKANA LETTER SU")
     (?ズ . "KATAKANA LETTER ZU")
     (?セ . "KATAKANA LETTER SE")
     (?ゼ . "KATAKANA LETTER ZE")
     (?ソ . "KATAKANA LETTER SO")
     (?ゾ . "KATAKANA LETTER ZO")
     (?タ . "KATAKANA LETTER TA")
     (?ダ . "KATAKANA LETTER DA")
     (?チ . "KATAKANA LETTER TI")
     (?ヂ . "KATAKANA LETTER DI")
     (?ッ . "KATAKANA LETTER SMALL TU")
     (?ツ . "KATAKANA LETTER TU")
     (?ヅ . "KATAKANA LETTER DU")
     (?テ . "KATAKANA LETTER TE")
     (?デ . "KATAKANA LETTER DE")
     (?ト . "KATAKANA LETTER TO")
     (?ド . "KATAKANA LETTER DO")
     (?ナ . "KATAKANA LETTER NA")
     (?ニ . "KATAKANA LETTER NI")
     (?ヌ . "KATAKANA LETTER NU")
     (?ネ . "KATAKANA LETTER NE")
     (?ノ . "KATAKANA LETTER NO")
     (?ハ . "KATAKANA LETTER HA")
     (?バ . "KATAKANA LETTER BA")
     (?パ . "KATAKANA LETTER PA")
     (?ヒ . "KATAKANA LETTER HI")
     (?ビ . "KATAKANA LETTER BI")
     (?ピ . "KATAKANA LETTER PI")
     (?フ . "KATAKANA LETTER HU")
     (?ブ . "KATAKANA LETTER BU")
     (?プ . "KATAKANA LETTER PU")
     (?ヘ . "KATAKANA LETTER HE")
     (?ベ . "KATAKANA LETTER BE")
     (?ペ . "KATAKANA LETTER PE")
     (?ホ . "KATAKANA LETTER HO")
     (?ボ . "KATAKANA LETTER BO")
     (?ポ . "KATAKANA LETTER PO")
     (?マ . "KATAKANA LETTER MA")
     (?ミ . "KATAKANA LETTER MI")
     (?ム . "KATAKANA LETTER MU")
     (?メ . "KATAKANA LETTER ME")
     (?モ . "KATAKANA LETTER MO")
     (?ャ . "KATAKANA LETTER SMALL YA")
     (?ヤ . "KATAKANA LETTER YA")
     (?ュ . "KATAKANA LETTER SMALL YU")
     (?ユ . "KATAKANA LETTER YU")
     (?ョ . "KATAKANA LETTER SMALL YO")
     (?ヨ . "KATAKANA LETTER YO")
     (?ラ . "KATAKANA LETTER RA")
     (?リ . "KATAKANA LETTER RI")
     (?ル . "KATAKANA LETTER RU")
     (?レ . "KATAKANA LETTER RE")
     (?ロ . "KATAKANA LETTER RO")
     (?ヮ . "KATAKANA LETTER SMALL WA")
     (?ワ . "KATAKANA LETTER WA")
     (?ヰ . "KATAKANA LETTER WI")
     (?ヱ . "KATAKANA LETTER WE")
     (?ヲ . "KATAKANA LETTER WO")
     (?ン . "KATAKANA LETTER N")
     (?ヴ . "KATAKANA LETTER VU")
     (?ヵ . "KATAKANA LETTER SMALL KA")
     (?ヶ . "KATAKANA LETTER SMALL KE")
     (?カ゚ . "KATAKANA LETTER BIDAKUON NGA") ; tentative
     (?キ゚ . "KATAKANA LETTER BIDAKUON NGI") ; tentative
     (?ク゚ . "KATAKANA LETTER BIDAKUON NGU") ; tentative
     (?ケ゚ . "KATAKANA LETTER BIDAKUON NGE") ; tentative
     (?コ゚ . "KATAKANA LETTER BIDAKUON NGO") ; tentative
     (?セ゚ . "KATAKANA LETTER AINU CE") ; tentative
     (?ツ゚ . "KATAKANA LETTER AINU TU (TU)") ; tentative
     (?ト゚ . "KATAKANA LETTER AINU TO (TU)") ; tentative
     (?Α . "GREEK CAPITAL LETTER ALPHA")
     (?Β . "GREEK CAPITAL LETTER BETA")
     (?Γ . "GREEK CAPITAL LETTER GAMMA")
     (?Δ . "GREEK CAPITAL LETTER DELTA")
     (?Ε . "GREEK CAPITAL LETTER EPSILON")
     (?Ζ . "GREEK CAPITAL LETTER ZETA")
     (?Η . "GREEK CAPITAL LETTER ETA")
     (?Θ . "GREEK CAPITAL LETTER THETA")
     (?Ι . "GREEK CAPITAL LETTER IOTA")
     (?Κ . "GREEK CAPITAL LETTER KAPPA")
     (?Λ . "GREEK CAPITAL LETTER LAMBDA")
     (?Μ . "GREEK CAPITAL LETTER MU")
     (?Ν . "GREEK CAPITAL LETTER NU")
     (?Ξ . "GREEK CAPITAL LETTER XI")
     (?Ο . "GREEK CAPITAL LETTER OMICRON")
     (?Π . "GREEK CAPITAL LETTER PI")
     (?Ρ . "GREEK CAPITAL LETTER RHO")
     (?Σ . "GREEK CAPITAL LETTER SIGMA")
     (?Τ . "GREEK CAPITAL LETTER TAU")
     (?Υ . "GREEK CAPITAL LETTER UPSILON")
     (?Φ . "GREEK CAPITAL LETTER PHI")
     (?Χ . "GREEK CAPITAL LETTER CHI")
     (?Ψ . "GREEK CAPITAL LETTER PSI")
     (?Ω . "GREEK CAPITAL LETTER OMEGA")
     (?♤ . "WHITE SPADE SUIT")
     (?♠ . "BLACK SPADE SUIT")
     (?♢ . "WHITE DIAMOND SUIT")
     (?♦ . "BLACK DIAMOND SUIT")
     (?♡ . "WHITE HEART SUIT")
     (?♥ . "BLACK HEART SUIT")
     (?♧ . "WHITE CLUB SUIT")
     (?♣ . "BLACK CLUB SUIT")
     (?α . "GREEK SMALL LETTER ALPHA")
     (?β . "GREEK SMALL LETTER BETA")
     (?γ . "GREEK SMALL LETTER GAMMA")
     (?δ . "GREEK SMALL LETTER DELTA")
     (?ε . "GREEK SMALL LETTER EPSILON")
     (?ζ . "GREEK SMALL LETTER ZETA")
     (?η . "GREEK SMALL LETTER ETA")
     (?θ . "GREEK SMALL LETTER THETA")
     (?ι . "GREEK SMALL LETTER IOTA")
     (?κ . "GREEK SMALL LETTER KAPPA")
     (?λ . "GREEK SMALL LETTER LAMBDA")
     (?μ . "GREEK SMALL LETTER MU")
     (?ν . "GREEK SMALL LETTER NU")
     (?ξ . "GREEK SMALL LETTER XI")
     (?ο . "GREEK SMALL LETTER OMICRON")
     (?π . "GREEK SMALL LETTER PI")
     (?ρ . "GREEK SMALL LETTER RHO")
     (?σ . "GREEK SMALL LETTER SIGMA")
     (?τ . "GREEK SMALL LETTER TAU")
     (?υ . "GREEK SMALL LETTER UPSILON")
     (?φ . "GREEK SMALL LETTER PHI")
     (?χ . "GREEK SMALL LETTER CHI")
     (?ψ . "GREEK SMALL LETTER PSI")
     (?ω . "GREEK SMALL LETTER OMEGA")
     (?ς . "GREEK SMALL LETTER FINAL SIGMA")
     (?⓵ . "DOUBLE CIRCLED DIGIT ONE") ; tentative
     (?⓶ . "DOUBLE CIRCLED DIGIT TWO") ; tentative
     (?⓷ . "DOUBLE CIRCLED DIGIT THREE") ; tentative
     (?⓸ . "DOUBLE CIRCLED DIGIT FOUR") ; tentative
     (?⓹ . "DOUBLE CIRCLED DIGIT FIVE") ; tentative
     (?⓺ . "DOUBLE CIRCLED DIGIT SIX") ; tentative
     (?⓻ . "DOUBLE CIRCLED DIGIT SEVEN") ; tentative
     (?⓼ . "DOUBLE CIRCLED DIGIT EIGHT") ; tentative
     (?⓽ . "DOUBLE CIRCLED DIGIT NINE") ; tentative
     (?⓾ . "DOUBLE CIRCLED NUMBER TEN") ; tentative
     (?☖ . "WHITE SHOGI PIECE") ; tentative
     (?☗ . "BLACK SHOGI PIECE") ; tentative
     (?〠 . "POSTAL MARK FACE")
     (?☎ . "BLACK TELEPHONE")
     (?☀ . "BLACK SUN WITH RAYS")
     (?☁ . "CLOUD")
     (?☂ . "UMBRELLA")
     (?☃ . "SNOWMAN")
     (?♨ . "HOT SPRINGS")
     (?▱ . "WHITE PARALLELOGRAM")
     (?ㇰ . "KATAKANA LETTER AINU K") ; tentative
     (?ㇱ . "KATAKANA LETTER AINU SI (S)") ; tentative
     (?ㇲ . "KATAKANA LETTER AINU SU (S)") ; tentative
     (?ㇳ . "KATAKANA LETTER AINU T") ; tentative
     (?ㇴ . "KATAKANA LETTER AINU N") ; tentative
     (?ㇵ . "KATAKANA LETTER AINU AX") ; tentative
     (?ㇶ . "KATAKANA LETTER AINU IX") ; tentative
     (?ㇷ . "KATAKANA LETTER AINU UX") ; tentative
     (?ㇸ . "KATAKANA LETTER AINU EX") ; tentative
     (?ㇹ . "KATAKANA LETTER AINU OX") ; tentative
     (?ㇷ゚ . "KATAKANA LETTER AINU P") ; tentative
     (?ㇺ . "KATAKANA LETTER AINU M") ; tentative
     (?ㇻ . "KATAKANA LETTER AINU AR") ; tentative
     (?ㇼ . "KATAKANA LETTER AINU IR") ; tentative
     (?ㇽ . "KATAKANA LETTER AINU UR") ; tentative
     (?ㇾ . "KATAKANA LETTER AINU ER") ; tentative
     (?ㇿ . "KATAKANA LETTER AINU OR") ; tentative
     (?А . "CYRILLIC CAPITAL LETTER A")
     (?Б . "CYRILLIC CAPITAL LETTER BE")
     (?В . "CYRILLIC CAPITAL LETTER VE")
     (?Г . "CYRILLIC CAPITAL LETTER GHE")
     (?Д . "CYRILLIC CAPITAL LETTER DE")
     (?Е . "CYRILLIC CAPITAL LETTER IE")
     (?Ё . "CYRILLIC CAPITAL LETTER IO")
     (?Ж . "CYRILLIC CAPITAL LETTER ZHE")
     (?З . "CYRILLIC CAPITAL LETTER ZE")
     (?И . "CYRILLIC CAPITAL LETTER I")
     (?Й . "CYRILLIC CAPITAL LETTER SHORT I")
     (?К . "CYRILLIC CAPITAL LETTER KA")
     (?Л . "CYRILLIC CAPITAL LETTER EL")
     (?М . "CYRILLIC CAPITAL LETTER EM")
     (?Н . "CYRILLIC CAPITAL LETTER EN")
     (?О . "CYRILLIC CAPITAL LETTER O")
     (?П . "CYRILLIC CAPITAL LETTER PE")
     (?Р . "CYRILLIC CAPITAL LETTER ER")
     (?С . "CYRILLIC CAPITAL LETTER ES")
     (?Т . "CYRILLIC CAPITAL LETTER TE")
     (?У . "CYRILLIC CAPITAL LETTER U")
     (?Ф . "CYRILLIC CAPITAL LETTER EF")
     (?Х . "CYRILLIC CAPITAL LETTER HA")
     (?Ц . "CYRILLIC CAPITAL LETTER TSE")
     (?Ч . "CYRILLIC CAPITAL LETTER CHE")
     (?Ш . "CYRILLIC CAPITAL LETTER SHA")
     (?Щ . "CYRILLIC CAPITAL LETTER SHCHA")
     (?Ъ . "CYRILLIC CAPITAL LETTER HARD SIGN")
     (?Ы . "CYRILLIC CAPITAL LETTER YERU")
     (?Ь . "CYRILLIC CAPITAL LETTER SOFT SIGN")
     (?Э . "CYRILLIC CAPITAL LETTER E")
     (?Ю . "CYRILLIC CAPITAL LETTER YU")
     (?Я . "CYRILLIC CAPITAL LETTER YA")
     (?⎾ . "DENTIST SYMBOL LIGHT VERTICAL AND TOP RIGHT") ; tentative
     (?⎿ . "DENTIST SYMBOL LIGHT VERTICAL AND BOTTOM RIGHT") ; tentative
     (?⏀ . "DENTIST SYMBOL LIGHT VERTICAL WITH CIRCLE") ; tentative
     (?⏁ . "DENTIST SYMBOL LIGHT DOWN AND HORIZONTAL WITH CIRCLE") ; tentative
     (?⏂ . "DENTIST SYMBOL LIGHT UP AND HORIZONTAL WITH CIRCLE") ; tentative
     (?⏃ . "DENTIST SYMBOL LIGHT VERTICAL WITH TRIANGLE") ; tentative
     (?⏄ . "DENTIST SYMBOL LIGHT DOWN AND HORIZONTAL WITH TRIANGLE") ; tentative
     (?⏅ . "DENTIST SYMBOL LIGHT UP AND HORIZONTAL WITH TRIANGLE") ; tentative
     (?⏆ . "DENTIST SYMBOL LIGHT VERTICAL WITH WAVE") ; tentative
     (?⏇ . "DENTIST SYMBOL LIGHT DOWN AND HORIZONTAL WITH WAVE") ; tentative
     (?⏈ . "DENTIST SYMBOL LIGHT UP AND HORIZONTAL WITH WAVE") ; tentative
     (?⏉ . "DENTIST SYMBOL LIGHT DOWN AND HORIZONTAL") ; tentative
     (?⏊ . "DENTIST SYMBOL LIGHT UP AND HORIZONTAL") ; tentative
     (?⏋ . "DENTIST SYMBOL LIGHT VERTICAL AND TOP LEFT") ; tentative
     (?⏌ . "DENTIST SYMBOL LIGHT VERTICAL AND BOTTOM LEFT") ; tentative
     (?а . "CYRILLIC SMALL LETTER A")
     (?б . "CYRILLIC SMALL LETTER BE")
     (?в . "CYRILLIC SMALL LETTER VE")
     (?г . "CYRILLIC SMALL LETTER GHE")
     (?д . "CYRILLIC SMALL LETTER DE")
     (?е . "CYRILLIC SMALL LETTER IE")
     (?ё . "CYRILLIC SMALL LETTER IO")
     (?ж . "CYRILLIC SMALL LETTER ZHE")
     (?з . "CYRILLIC SMALL LETTER ZE")
     (?и . "CYRILLIC SMALL LETTER I")
     (?й . "CYRILLIC SMALL LETTER SHORT I")
     (?к . "CYRILLIC SMALL LETTER KA")
     (?л . "CYRILLIC SMALL LETTER EL")
     (?м . "CYRILLIC SMALL LETTER EM")
     (?н . "CYRILLIC SMALL LETTER EN")
     (?о . "CYRILLIC SMALL LETTER O")
     (?п . "CYRILLIC SMALL LETTER PE")
     (?р . "CYRILLIC SMALL LETTER ER")
     (?с . "CYRILLIC SMALL LETTER ES")
     (?т . "CYRILLIC SMALL LETTER TE")
     (?у . "CYRILLIC SMALL LETTER U")
     (?ф . "CYRILLIC SMALL LETTER EF")
     (?х . "CYRILLIC SMALL LETTER HA")
     (?ц . "CYRILLIC SMALL LETTER TSE")
     (?ч . "CYRILLIC SMALL LETTER CHE")
     (?ш . "CYRILLIC SMALL LETTER SHA")
     (?щ . "CYRILLIC SMALL LETTER SHCHA")
     (?ъ . "CYRILLIC SMALL LETTER HARD SIGN")
     (?ы . "CYRILLIC SMALL LETTER YERU")
     (?ь . "CYRILLIC SMALL LETTER SOFT SIGN")
     (?э . "CYRILLIC SMALL LETTER E")
     (?ю . "CYRILLIC SMALL LETTER YU")
     (?я . "CYRILLIC SMALL LETTER YA")
     (?ヷ . "KATAKANA LETTER VA")
     (?ヸ . "KATAKANA LETTER VI")
     (?ヹ . "KATAKANA LETTER VE")
     (?ヺ . "KATAKANA LETTER VO")
     (?⋚ . "LESS-THAN EQUAL TO OR GREATER-THAN")
     (?⋛ . "GREATER-THAN EQUAL TO OR LESS-THAN")
     (?⅓ . "VULGAR FRACTION ONE THIRD")
     (?⅔ . "VULGAR FRACTION TWO THIRDS")
     (?⅕ . "VULGAR FRACTION ONE FIFTH")
     (?✓ . "CHECK MARK")
     (?⌘ . "PLACE OF INTEREST SIGN")
     (?␣ . "OPEN BOX")
     (?⏎ . "RETURN SIGN") ; tentative
     (?─ . "BOX DRAWINGS LIGHT HORIZONTAL")
     (?│ . "BOX DRAWINGS LIGHT VERTICAL")
     (?┌ . "BOX DRAWINGS LIGHT DOWN AND RIGHT")
     (?┐ . "BOX DRAWINGS LIGHT DOWN AND LEFT")
     (?┘ . "BOX DRAWINGS LIGHT UP AND LEFT")
     (?└ . "BOX DRAWINGS LIGHT UP AND RIGHT")
     (?├ . "BOX DRAWINGS LIGHT VERTICAL AND RIGHT")
     (?┬ . "BOX DRAWINGS LIGHT DOWN AND HORIZONTAL")
     (?┤ . "BOX DRAWINGS LIGHT VERTICAL AND LEFT")
     (?┴ . "BOX DRAWINGS LIGHT UP AND HORIZONTAL")
     (?┼ . "BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL")
     (?━ . "BOX DRAWINGS HEAVY HORIZONTAL")
     (?┃ . "BOX DRAWINGS HEAVY VERTICAL")
     (?┏ . "BOX DRAWINGS HEAVY DOWN AND RIGHT")
     (?┓ . "BOX DRAWINGS HEAVY DOWN AND LEFT")
     (?┛ . "BOX DRAWINGS HEAVY UP AND LEFT")
     (?┗ . "BOX DRAWINGS HEAVY UP AND RIGHT")
     (?┣ . "BOX DRAWINGS HEAVY VERTICAL AND RIGHT")
     (?┳ . "BOX DRAWINGS HEAVY DOWN AND HORIZONTAL")
     (?┫ . "BOX DRAWINGS HEAVY VERTICAL AND LEFT")
     (?┻ . "BOX DRAWINGS HEAVY UP AND HORIZONTAL")
     (?╋ . "BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL")
     (?┠ . "BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT")
     (?┯ . "BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY")
     (?┨ . "BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT")
     (?┷ . "BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY")
     (?┿ . "BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY")
     (?┝ . "BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY")
     (?┰ . "BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT")
     (?┥ . "BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY")
     (?┸ . "BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT")
     (?╂ . "BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT")
     (?㉑ . "CIRCLED NUMBER TWENTY ONE") ; tentative
     (?㉒ . "CIRCLED NUMBER TWENTY TWO") ; tentative
     (?㉓ . "CIRCLED NUMBER TWENTY THREE") ; tentative
     (?㉔ . "CIRCLED NUMBER TWENTY FOUR") ; tentative
     (?㉕ . "CIRCLED NUMBER TWENTY FIVE") ; tentative
     (?㉖ . "CIRCLED NUMBER TWENTY SIX") ; tentative
     (?㉗ . "CIRCLED NUMBER TWENTY SEVEN") ; tentative
     (?㉘ . "CIRCLED NUMBER TWENTY EIGHT") ; tentative
     (?㉙ . "CIRCLED NUMBER TWENTY NINE") ; tentative
     (?㉚ . "CIRCLED NUMBER THIRTY") ; tentative
     (?㉛ . "CIRCLED NUMBER THIRTY ONE") ; tentative
     (?㉜ . "CIRCLED NUMBER THIRTY TWO") ; tentative
     (?㉝ . "CIRCLED NUMBER THIRTY THREE") ; tentative
     (?㉞ . "CIRCLED NUMBER THIRTY FOUR") ; tentative
     (?㉟ . "CIRCLED NUMBER THIRTY FIVE") ; tentative
     (?㊱ . "CIRCLED NUMBER THIRTY SIX") ; tentative
     (?㊲ . "CIRCLED NUMBER THIRTY SEVEN") ; tentative
     (?㊳ . "CIRCLED NUMBER THIRTY EIGHT") ; tentative
     (?㊴ . "CIRCLED NUMBER THIRTY NINE") ; tentative
     (?㊵ . "CIRCLED NUMBER FORTY") ; tentative
     (?㊶ . "CIRCLED NUMBER FORTY ONE") ; tentative
     (?㊷ . "CIRCLED NUMBER FORTY TWO") ; tentative
     (?㊸ . "CIRCLED NUMBER FORTY THREE") ; tentative
     (?㊹ . "CIRCLED NUMBER FORTY FOUR") ; tentative
     (?㊺ . "CIRCLED NUMBER FORTY FIVE") ; tentative
     (?㊻ . "CIRCLED NUMBER FORTY SIX") ; tentative
     (?㊼ . "CIRCLED NUMBER FORTY SEVEN") ; tentative
     (?㊽ . "CIRCLED NUMBER FORTY EIGHT") ; tentative
     (?㊾ . "CIRCLED NUMBER FORTY NINE") ; tentative
     (?㊿ . "CIRCLED NUMBER FIFTY") ; tentative
     (?◐ . "CIRCLE WITH LEFT HALF BLACK")
     (?◑ . "CIRCLE WITH RIGHT HALF BLACK")
     (?◒ . "CIRCLE WITH LOWER HALF BLACK")
     (?◓ . "CIRCLE WITH UPPER HALF BLACK")
     (?‼ . "DOUBLE EXCLAMATION MARK")
     (?⁇ . "DOUBLE QUESTION MARK") ; tentative
     (?⁈ . "QUESTION EXCLAMATION MARK")
     (?⁉ . "EXCLAMATION QUESTION MARK")
     (?Ǎ . "LATIN CAPITAL LETTER A WITH CARON")
     (?ǎ . "LATIN SMALL LETTER A WITH CARON")
     (?ǐ . "LATIN SMALL LETTER I WITH CARON")
     (?Ḿ . "LATIN CAPITAL LETTER M WITH ACUTE")
     (?ḿ . "LATIN SMALL LETTER M WITH ACUTE")
     (?Ǹ . "LATIN CAPITAL LETTER N WITH GRAVE")
     (?ǹ . "LATIN SMALL LETTER N WITH GRAVE")
     (?Ǒ . "LATIN CAPITAL LETTER O WITH CARON")
     (?ǒ . "LATIN SMALL LETTER O WITH CARON")
     (?ǔ . "LATIN SMALL LETTER U WITH CARON")
     (?ǖ . "LATIN SMALL LETTER U WITH DIAERESIS AND MACRON")
     (?ǘ . "LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE")
     (?ǚ . "LATIN SMALL LETTER U WITH DIAERESIS AND CARON")
     (?ǜ . "LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE")
     (?€ . "EURO SIGN")
     (?  . "NO-BREAK SPACE")
     (?¡ . "INVERTED EXCLAMATION MARK")
     (?¤ . "CURRENCY SIGN")
     (?¦ . "BROKEN BAR")
     (?© . "COPYRIGHT SIGN")
     (?ª . "FEMININE ORDINAL INDICATOR")
     (?« . "LEFT-POINTING DOUBLE ANGLE QUOTATION MARK")
     (?­ . "SOFT HYPHEN")
     (?® . "REGISTERED SIGN")
     (?¯ . "MACRON")
     (?² . "SUPERSCRIPT TWO")
     (?³ . "SUPERSCRIPT THREE")
     (?· . "MIDDLE DOT")
     (?¸ . "CEDILLA")
     (?¹ . "SUPERSCRIPT ONE")
     (?º . "MASCULINE ORDINAL INDICATOR")
     (?» . "RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK")
     (?¼ . "VULGAR FRACTION ONE QUARTER")
     (?½ . "VULGAR FRACTION ONE HALF")
     (?¾ . "VULGAR FRACTION THREE QUARTERS")
     (?¿ . "INVERTED QUESTION MARK")
     (?À . "LATIN CAPITAL LETTER A WITH GRAVE")
     (?Á . "LATIN CAPITAL LETTER A WITH ACUTE")
     (?Â . "LATIN CAPITAL LETTER A WITH CIRCUMFLEX")
     (?Ã . "LATIN CAPITAL LETTER A WITH TILDE")
     (?Ä . "LATIN CAPITAL LETTER A WITH DIAERESIS")
     (?Å . "LATIN CAPITAL LETTER A WITH RING ABOVE")
     (?Æ . "LATIN CAPITAL LETTER AE")
     (?Ç . "LATIN CAPITAL LETTER C WITH CEDILLA")
     (?È . "LATIN CAPITAL LETTER E WITH GRAVE")
     (?É . "LATIN CAPITAL LETTER E WITH ACUTE")
     (?Ê . "LATIN CAPITAL LETTER E WITH CIRCUMFLEX")
     (?Ë . "LATIN CAPITAL LETTER E WITH DIAERESIS")
     (?Ì . "LATIN CAPITAL LETTER I WITH GRAVE")
     (?Í . "LATIN CAPITAL LETTER I WITH ACUTE")
     (?Î . "LATIN CAPITAL LETTER I WITH CIRCUMFLEX")
     (?Ï . "LATIN CAPITAL LETTER I WITH DIAERESIS")
     (?Ð . "LATIN CAPITAL LETTER ETH (Icelandic)")
     (?Ñ . "LATIN CAPITAL LETTER N WITH TILDE")
     (?Ò . "LATIN CAPITAL LETTER O WITH GRAVE")
     (?Ó . "LATIN CAPITAL LETTER O WITH ACUTE")
     (?Ô . "LATIN CAPITAL LETTER O WITH CIRCUMFLEX")
     (?Õ . "LATIN CAPITAL LETTER O WITH TILDE")
     (?Ö . "LATIN CAPITAL LETTER O WITH DIAERESIS")
     (?Ø . "LATIN CAPITAL LETTER O WITH STROKE")
     (?Ù . "LATIN CAPITAL LETTER U WITH GRAVE")
     (?Ú . "LATIN CAPITAL LETTER U WITH ACUTE")
     (?Û . "LATIN CAPITAL LETTER U WITH CIRCUMFLEX")
     (?Ü . "LATIN CAPITAL LETTER U WITH DIAERESIS")
     (?Ý . "LATIN CAPITAL LETTER Y WITH ACUTE")
     (?Þ . "LATIN CAPITAL LETTER THORN (Icelandic)")
     (?ß . "LATIN SMALL LETTER SHARP S (German)")
     (?à . "LATIN SMALL LETTER A WITH GRAVE")
     (?á . "LATIN SMALL LETTER A WITH ACUTE")
     (?â . "LATIN SMALL LETTER A WITH CIRCUMFLEX")
     (?ã . "LATIN SMALL LETTER A WITH TILDE")
     (?ä . "LATIN SMALL LETTER A WITH DIAERESIS")
     (?å . "LATIN SMALL LETTER A WITH RING ABOVE")
     (?æ . "LATIN SMALL LETTER AE")
     (?ç . "LATIN SMALL LETTER C WITH CEDILLA")
     (?è . "LATIN SMALL LETTER E WITH GRAVE")
     (?é . "LATIN SMALL LETTER E WITH ACUTE")
     (?ê . "LATIN SMALL LETTER E WITH CIRCUMFLEX")
     (?ë . "LATIN SMALL LETTER E WITH DIAERESIS")
     (?ì . "LATIN SMALL LETTER I WITH GRAVE")
     (?í . "LATIN SMALL LETTER I WITH ACUTE")
     (?î . "LATIN SMALL LETTER I WITH CIRCUMFLEX")
     (?ï . "LATIN SMALL LETTER I WITH DIAERESIS")
     (?ð . "LATIN SMALL LETTER ETH (Icelandic)")
     (?ñ . "LATIN SMALL LETTER N WITH TILDE")
     (?ò . "LATIN SMALL LETTER O WITH GRAVE")
     (?ó . "LATIN SMALL LETTER O WITH ACUTE")
     (?ô . "LATIN SMALL LETTER O WITH CIRCUMFLEX")
     (?õ . "LATIN SMALL LETTER O WITH TILDE")
     (?ö . "LATIN SMALL LETTER O WITH DIAERESIS")
     (?ø . "LATIN SMALL LETTER O WITH STROKE")
     (?ù . "LATIN SMALL LETTER U WITH GRAVE")
     (?ú . "LATIN SMALL LETTER U WITH ACUTE")
     (?û . "LATIN SMALL LETTER U WITH CIRCUMFLEX")
     (?ü . "LATIN SMALL LETTER U WITH DIAERESIS")
     (?ý . "LATIN SMALL LETTER Y WITH ACUTE")
     (?þ . "LATIN SMALL LETTER THORN (Icelandic)")
     (?ÿ . "LATIN SMALL LETTER Y WITH DIAERESIS")
     (?Ā . "LATIN CAPITAL LETTER A WITH MACRON")
     (?Ī . "LATIN CAPITAL LETTER I WITH MACRON")
     (?Ū . "LATIN CAPITAL LETTER U WITH MACRON")
     (?Ē . "LATIN CAPITAL LETTER E WITH MACRON")
     (?Ō . "LATIN CAPITAL LETTER O WITH MACRON")
     (?ā . "LATIN SMALL LETTER A WITH MACRON")
     (?ī . "LATIN SMALL LETTER I WITH MACRON")
     (?ū . "LATIN SMALL LETTER U WITH MACRON")
     (?ē . "LATIN SMALL LETTER E WITH MACRON")
     (?ō . "LATIN SMALL LETTER O WITH MACRON")
     (?Ą . "LATIN CAPITAL LETTER A WITH OGONEK")
     (?˘ . "BREVE")
     (?Ł . "LATIN CAPITAL LETTER L WITH STROKE")
     (?Ľ . "LATIN CAPITAL LETTER L WITH CARON")
     (?Ś . "LATIN CAPITAL LETTER S WITH ACUTE")
     (?Š . "LATIN CAPITAL LETTER S WITH CARON")
     (?Ş . "LATIN CAPITAL LETTER S WITH CEDILLA")
     (?Ť . "LATIN CAPITAL LETTER T WITH CARON")
     (?Ź . "LATIN CAPITAL LETTER Z WITH ACUTE")
     (?Ž . "LATIN CAPITAL LETTER Z WITH CARON")
     (?Ż . "LATIN CAPITAL LETTER Z WITH DOT ABOVE")
     (?ą . "LATIN SMALL LETTER A WITH OGONEK")
     (?˛ . "OGONEK")
     (?ł . "LATIN SMALL LETTER L WITH STROKE")
     (?ľ . "LATIN SMALL LETTER L WITH CARON")
     (?ś . "LATIN SMALL LETTER S WITH ACUTE")
     (?ˇ . "CARON (Mandarin Chinese third tone)")
     (?š . "LATIN SMALL LETTER S WITH CARON")
     (?ş . "LATIN SMALL LETTER S WITH CEDILLA")
     (?ť . "LATIN SMALL LETTER T WITH CARON")
     (?ź . "LATIN SMALL LETTER Z WITH ACUTE")
     (?˝ . "DOUBLE ACUTE ACCENT")
     (?ž . "LATIN SMALL LETTER Z WITH CARON")
     (?ż . "LATIN SMALL LETTER Z WITH DOT ABOVE")
     (?Ŕ . "LATIN CAPITAL LETTER R WITH ACUTE")
     (?Ă . "LATIN CAPITAL LETTER A WITH BREVE")
     (?Ĺ . "LATIN CAPITAL LETTER L WITH ACUTE")
     (?Ć . "LATIN CAPITAL LETTER C WITH ACUTE")
     (?Č . "LATIN CAPITAL LETTER C WITH CARON")
     (?Ę . "LATIN CAPITAL LETTER E WITH OGONEK")
     (?Ě . "LATIN CAPITAL LETTER E WITH CARON")
     (?Ď . "LATIN CAPITAL LETTER D WITH CARON")
     (?Ń . "LATIN CAPITAL LETTER N WITH ACUTE")
     (?Ň . "LATIN CAPITAL LETTER N WITH CARON")
     (?Ő . "LATIN CAPITAL LETTER O WITH DOUBLE ACUTE")
     (?Ř . "LATIN CAPITAL LETTER R WITH CARON")
     (?Ů . "LATIN CAPITAL LETTER U WITH RING ABOVE")
     (?Ű . "LATIN CAPITAL LETTER U WITH DOUBLE ACUTE")
     (?Ţ . "LATIN CAPITAL LETTER T WITH CEDILLA")
     (?ŕ . "LATIN SMALL LETTER R WITH ACUTE")
     (?ă . "LATIN SMALL LETTER A WITH BREVE")
     (?ĺ . "LATIN SMALL LETTER L WITH ACUTE")
     (?ć . "LATIN SMALL LETTER C WITH ACUTE")
     (?č . "LATIN SMALL LETTER C WITH CARON")
     (?ę . "LATIN SMALL LETTER E WITH OGONEK")
     (?ě . "LATIN SMALL LETTER E WITH CARON")
     (?ď . "LATIN SMALL LETTER D WITH CARON")
     (?đ . "LATIN SMALL LETTER D WITH STROKE")
     (?ń . "LATIN SMALL LETTER N WITH ACUTE")
     (?ň . "LATIN SMALL LETTER N WITH CARON")
     (?ő . "LATIN SMALL LETTER O WITH DOUBLE ACUTE")
     (?ř . "LATIN SMALL LETTER R WITH CARON")
     (?ů . "LATIN SMALL LETTER U WITH RING ABOVE")
     (?ű . "LATIN SMALL LETTER U WITH DOUBLE ACUTE")
     (?ţ . "LATIN SMALL LETTER T WITH CEDILLA")
     (?˙ . "DOT ABOVE (Mandarin Chinese light tone)")
     (?Ĉ . "LATIN CAPITAL LETTER C WITH CIRCUMFLEX")
     (?Ĝ . "LATIN CAPITAL LETTER G WITH CIRCUMFLEX")
     (?Ĥ . "LATIN CAPITAL LETTER H WITH CIRCUMFLEX")
     (?Ĵ . "LATIN CAPITAL LETTER J WITH CIRCUMFLEX")
     (?Ŝ . "LATIN CAPITAL LETTER S WITH CIRCUMFLEX")
     (?Ŭ . "LATIN CAPITAL LETTER U WITH BREVE")
     (?ĉ . "LATIN SMALL LETTER C WITH CIRCUMFLEX")
     (?ĝ . "LATIN SMALL LETTER G WITH CIRCUMFLEX")
     (?ĥ . "LATIN SMALL LETTER H WITH CIRCUMFLEX")
     (?ĵ . "LATIN SMALL LETTER J WITH CIRCUMFLEX")
     (?ŝ . "LATIN SMALL LETTER S WITH CIRCUMFLEX")
     (?ŭ . "LATIN SMALL LETTER U WITH BREVE")
     (?ɱ . "LATIN SMALL LETTER M WITH HOOK")
     (?ʋ . "LATIN SMALL LETTER V WITH HOOK")
     (?ɾ . "LATIN SMALL LETTER R WITH FISHHOOK")
     (?ʃ . "LATIN SMALL LETTER ESH")
     (?ʒ . "LATIN SMALL LETTER EZH")
     (?ɬ . "LATIN SMALL LETTER L WITH BELT")
     (?ɮ . "LATIN SMALL LETTER LEZH")
     (?ɹ . "LATIN SMALL LETTER TURNED R")
     (?ʈ . "LATIN SMALL LETTER T WITH RETROFLEX HOOK")
     (?ɖ . "LATIN SMALL LETTER D WITH TAIL")
     (?ɳ . "LATIN SMALL LETTER N WITH RETROFLEX HOOK")
     (?ɽ . "LATIN SMALL LETTER R WITH TAIL")
     (?ʂ . "LATIN SMALL LETTER S WITH HOOK")
     (?ʐ . "LATIN SMALL LETTER Z WITH RETROFLEX HOOK")
     (?ɻ . "LATIN SMALL LETTER TURNED R WITH HOOK")
     (?ɭ . "LATIN SMALL LETTER L WITH RETROFLEX HOOK")
     (?ɟ . "LATIN SMALL LETTER DOTLESS J WITH STROKE")
     (?ɲ . "LATIN SMALL LETTER N WITH LEFT HOOK")
     (?ʝ . "LATIN SMALL LETTER J WITH CROSSED-TAIL")
     (?ʎ . "LATIN SMALL LETTER TURNED Y")
     (?ɡ . "LATIN SMALL LETTER SCRIPT G")
     (?ŋ . "LATIN SMALL LETTER ENG (Sami)")
     (?ɰ . "LATIN SMALL LETTER TURNED M WITH LONG LEG")
     (?ʁ . "LATIN LETTER SMALL CAPITAL INVERTED R")
     (?ħ . "LATIN SMALL LETTER H WITH STROKE")
     (?ʕ . "LATIN LETTER PHARYNGEAL VOICED FRICATIVE")
     (?ʔ . "LATIN LETTER GLOTTAL STOP")
     (?ɦ . "LATIN SMALL LETTER H WITH HOOK")
     (?ʘ . "LATIN LETTER BILABIAL CLICK")
     (?ǂ . "LATIN LETTER ALVEOLAR CLICK")
     (?ɓ . "LATIN SMALL LETTER B WITH HOOK")
     (?ɗ . "LATIN SMALL LETTER D WITH HOOK")
     (?ʄ . "LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK")
     (?ɠ . "LATIN SMALL LETTER G WITH HOOK")
     (?Ɠ . "LATIN CAPITAL LETTER G WITH HOOK")
     (?œ . "LATIN SMALL LIGATURE OE")
     (?Œ . "LATIN CAPITAL LIGATURE OE")
     (?ɨ . "LATIN SMALL LETTER I WITH STROKE")
     (?ʉ . "LATIN SMALL LETTER U BAR")
     (?ɘ . "LATIN SMALL LETTER REVERSED E")
     (?ɵ . "LATIN SMALL LETTER BARRED O")
     (?ə . "LATIN SMALL LETTER SCHWA")
     (?ɜ . "LATIN SMALL LETTER REVERSED OPEN E")
     (?ɞ . "LATIN SMALL LETTER CLOSED REVERSED OPEN E")
     (?ɐ . "LATIN SMALL LETTER TURNED A")
     (?ɯ . "LATIN SMALL LETTER TURNED M")
     (?ʊ . "LATIN SMALL LETTER UPSILON")
     (?ɤ . "LATIN SMALL LETTER RAMS HORN")
     (?ʌ . "LATIN SMALL LETTER TURNED V")
     (?ɔ . "LATIN SMALL LETTER OPEN O")
     (?ɑ . "LATIN SMALL LETTER ALPHA")
     (?ɒ . "LATIN SMALL LETTER TURNED ALPHA")
     (?ʍ . "LATIN SMALL LETTER TURNED W")
     (?ɥ . "LATIN SMALL LETTER TURNED H")
     (?ʢ . "LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE")
     (?ʡ . "LATIN LETTER GLOTTAL STOP WITH STROKE")
     (?ɕ . "LATIN SMALL LETTER C WITH CURL")
     (?ʑ . "LATIN SMALL LETTER Z WITH CURL")
     (?ɺ . "LATIN SMALL LETTER TURNED R WITH LONG LEG")
     (?ɧ . "LATIN SMALL LETTER HENG WITH HOOK")
     (?ɚ . "LATIN SMALL LETTER SCHWA WITH HOOK")
     (?æ̀ . "LATIN SMALL LETTER AE WITH GRAVE") ; tentative
     (?ǽ . "LATIN SMALL LETTER AE WITH ACUTE")
     (?ὰ . "GREEK SMALL LETTER ALPHA WITH VARIA")
     (?ά . "GREEK SMALL LETTER ALPHA WITH OXIA")
     (?ɔ̀ . "LATIN SMALL LETTER OPEN O WITH GRAVE") ; tentative
     (?ɔ́ . "LATIN SMALL LETTER OPEN O WITH ACUTE") ; tentative
     (?ʌ̀ . "LATIN SMALL LETTER TURNED V WITH GRAVE") ; tentative
     (?ʌ́ . "LATIN SMALL LETTER TURNED V WITH ACUTE") ; tentative
     (?ə̀ . "LATIN SMALL LETTER SCHWA WITH GRAVE") ; tentative
     (?ə́ . "LATIN SMALL LETTER SCHWA WITH ACUTE") ; tentative
     (?ɚ̀ . "LATIN SMALL LETTER HOOKED SCHWA WITH GRAVE") ; tentative
     (?ɚ́ . "LATIN SMALL LETTER HOOKED SCHWA WITH ACUTE") ; tentative
     (?ὲ . "GREEK SMALL LETTER EPSILON WITH VARIA")
     (?έ . "GREEK SMALL LETTER EPSILON WITH OXIA")
     (?͡ . "COMBINING DOUBLE INVERTED BREVE")
     (?ˈ . "MODIFIER LETTER VERTICAL LINE")
     (?ˌ . "MODIFIER LETTER LOW VERTICAL LINE")
     (?ː . "MODIFIER LETTER TRIANGULAR COLON")
     (?ˑ . "MODIFIER LETTER HALF TRIANGULAR COLON")
     (?̆ . "COMBINING BREVE (Vrachy)")
     (?‿ . "UNDERTIE (Enotikon)")
     (?̋ . "COMBINING DOUBLE ACUTE ACCENT")
     (?́ . "COMBINING ACUTE ACCENT (Oxia)")
     (?̄ . "COMBINING MACRON")
     (?̀ . "COMBINING GRAVE ACCENT (Varia)")
     (?̏ . "COMBINING DOUBLE GRAVE ACCENT")
     (?̌ . "COMBINING CARON")
     (?̂ . "COMBINING CIRCUMFLEX ACCENT")
     (?˥ . "MODIFIER LETTER EXTRA-HIGH TONE BAR")
     (?˦ . "MODIFIER LETTER HIGH TONE BAR")
     (?˧ . "MODIFIER LETTER MID TONE BAR")
     (?˨ . "MODIFIER LETTER LOW TONE BAR")
     (?˩ . "MODIFIER LETTER EXTRA-LOW TONE BAR")
     (?˩˥ . "RISING SYMBOL") ; tentative
     (?˥˩ . "FALLING SYMBOL") ; tentative
     (?̥ . "COMBINING RING BELOW")
     (?̬ . "COMBINING CARON BELOW")
     (?̹ . "COMBINING RIGHT HALF RING BELOW")
     (?̜ . "COMBINING LEFT HALF RING BELOW")
     (?̟ . "COMBINING PLUS SIGN BELOW")
     (?̠ . "COMBINING MINUS SIGN BELOW")
     (?̈ . "COMBINING DIAERESIS (Dialytika)")
     (?̽ . "COMBINING X ABOVE")
     (?̩ . "COMBINING VERTICAL LINE BELOW")
     (?̯ . "COMBINING INVERTED BREVE BELOW")
     (?˞ . "MODIFIER LETTER RHOTIC HOOK")
     (?̤ . "COMBINING DIAERESIS BELOW")
     (?̰ . "COMBINING TILDE BELOW")
     (?̼ . "COMBINING SEAGULL BELOW")
     (?̴ . "COMBINING TILDE OVERLAY")
     (?̝ . "COMBINING UP TACK BELOW")
     (?̞ . "COMBINING DOWN TACK BELOW")
     (?̘ . "COMBINING LEFT TACK BELOW")
     (?̙ . "COMBINING RIGHT TACK BELOW")
     (?̪ . "COMBINING BRIDGE BELOW")
     (?̺ . "COMBINING INVERTED BRIDGE BELOW")
     (?̻ . "COMBINING SQUARE BELOW")
     (?̃ . "COMBINING TILDE")
     (?̚ . "COMBINING LEFT ANGLE ABOVE")
     (?❶ . "DINGBAT NEGATIVE CIRCLED DIGIT ONE")
     (?❷ . "DINGBAT NEGATIVE CIRCLED DIGIT TWO")
     (?❸ . "DINGBAT NEGATIVE CIRCLED DIGIT THREE")
     (?❹ . "DINGBAT NEGATIVE CIRCLED DIGIT FOUR")
     (?❺ . "DINGBAT NEGATIVE CIRCLED DIGIT FIVE")
     (?❻ . "DINGBAT NEGATIVE CIRCLED DIGIT SIX")
     (?❼ . "DINGBAT NEGATIVE CIRCLED DIGIT SEVEN")
     (?❽ . "DINGBAT NEGATIVE CIRCLED DIGIT EIGHT")
     (?❾ . "DINGBAT NEGATIVE CIRCLED DIGIT NINE")
     (?❿ . "DINGBAT NEGATIVE CIRCLED NUMBER TEN")
     (?⓫ . "NEGATIVE CIRCLED NUMBER ELEVEN") ; tentative
     (?⓬ . "NEGATIVE CIRCLED NUMBER TWELVE") ; tentative
     (?⓭ . "NEGATIVE CIRCLED NUMBER THIRTEEN") ; tentative
     (?⓮ . "NEGATIVE CIRCLED NUMBER FOURTEEN") ; tentative
     (?⓯ . "NEGATIVE CIRCLED NUMBER FIFTEEN") ; tentative
     (?⓰ . "NEGATIVE CIRCLED NUMBER SIXTEEN") ; tentative
     (?⓱ . "NEGATIVE CIRCLED NUMBER SEVENTEEN") ; tentative
     (?⓲ . "NEGATIVE CIRCLED NUMBER EIGHTEEN") ; tentative
     (?⓳ . "NEGATIVE CIRCLED NUMBER NINETEEN") ; tentative
     (?⓴ . "NEGATIVE CIRCLED NUMBER TWENTY") ; tentative
     (?ⅰ . "SMALL ROMAN NUMERAL ONE")
     (?ⅱ . "SMALL ROMAN NUMERAL TWO")
     (?ⅲ . "SMALL ROMAN NUMERAL THREE")
     (?ⅳ . "SMALL ROMAN NUMERAL FOUR")
     (?ⅴ . "SMALL ROMAN NUMERAL FIVE")
     (?ⅵ . "SMALL ROMAN NUMERAL SIX")
     (?ⅶ . "SMALL ROMAN NUMERAL SEVEN")
     (?ⅷ . "SMALL ROMAN NUMERAL EIGHT")
     (?ⅸ . "SMALL ROMAN NUMERAL NINE")
     (?ⅹ . "SMALL ROMAN NUMERAL TEN")
     (?ⅺ . "SMALL ROMAN NUMERAL ELEVEN")
     (?ⅻ . "SMALL ROMAN NUMERAL TWELVE")
     (?ⓐ . "CIRCLED LATIN SMALL LETTER A")
     (?ⓑ . "CIRCLED LATIN SMALL LETTER B")
     (?ⓒ . "CIRCLED LATIN SMALL LETTER C")
     (?ⓓ . "CIRCLED LATIN SMALL LETTER D")
     (?ⓔ . "CIRCLED LATIN SMALL LETTER E")
     (?ⓕ . "CIRCLED LATIN SMALL LETTER F")
     (?ⓖ . "CIRCLED LATIN SMALL LETTER G")
     (?ⓗ . "CIRCLED LATIN SMALL LETTER H")
     (?ⓘ . "CIRCLED LATIN SMALL LETTER I")
     (?ⓙ . "CIRCLED LATIN SMALL LETTER J")
     (?ⓚ . "CIRCLED LATIN SMALL LETTER K")
     (?ⓛ . "CIRCLED LATIN SMALL LETTER L")
     (?ⓜ . "CIRCLED LATIN SMALL LETTER M")
     (?ⓝ . "CIRCLED LATIN SMALL LETTER N")
     (?ⓞ . "CIRCLED LATIN SMALL LETTER O")
     (?ⓟ . "CIRCLED LATIN SMALL LETTER P")
     (?ⓠ . "CIRCLED LATIN SMALL LETTER Q")
     (?ⓡ . "CIRCLED LATIN SMALL LETTER R")
     (?ⓢ . "CIRCLED LATIN SMALL LETTER S")
     (?ⓣ . "CIRCLED LATIN SMALL LETTER T")
     (?ⓤ . "CIRCLED LATIN SMALL LETTER U")
     (?ⓥ . "CIRCLED LATIN SMALL LETTER V")
     (?ⓦ . "CIRCLED LATIN SMALL LETTER W")
     (?ⓧ . "CIRCLED LATIN SMALL LETTER X")
     (?ⓨ . "CIRCLED LATIN SMALL LETTER Y")
     (?ⓩ . "CIRCLED LATIN SMALL LETTER Z")
     (?㋐ . "CIRCLED KATAKANA A")
     (?㋑ . "CIRCLED KATAKANA I")
     (?㋒ . "CIRCLED KATAKANA U")
     (?㋓ . "CIRCLED KATAKANA E")
     (?㋔ . "CIRCLED KATAKANA O")
     (?㋕ . "CIRCLED KATAKANA KA")
     (?㋖ . "CIRCLED KATAKANA KI")
     (?㋗ . "CIRCLED KATAKANA KU")
     (?㋘ . "CIRCLED KATAKANA KE")
     (?㋙ . "CIRCLED KATAKANA KO")
     (?㋚ . "CIRCLED KATAKANA SA")
     (?㋛ . "CIRCLED KATAKANA SI")
     (?㋜ . "CIRCLED KATAKANA SU")
     (?㋝ . "CIRCLED KATAKANA SE")
     (?㋞ . "CIRCLED KATAKANA SO")
     (?㋟ . "CIRCLED KATAKANA TA")
     (?㋠ . "CIRCLED KATAKANA TI")
     (?㋡ . "CIRCLED KATAKANA TU")
     (?㋢ . "CIRCLED KATAKANA TE")
     (?㋣ . "CIRCLED KATAKANA TO")
     (?㋺ . "CIRCLED KATAKANA RO")
     (?㋩ . "CIRCLED KATAKANA HA")
     (?㋥ . "CIRCLED KATAKANA NI")
     (?㋭ . "CIRCLED KATAKANA HO")
     (?㋬ . "CIRCLED KATAKANA HE")
     (?⁑ . "DOUBLE ASTERISK") ; tentative
     (?⁂ . "ASTERISM")
     (?① . "CIRCLED DIGIT ONE")
     (?② . "CIRCLED DIGIT TWO")
     (?③ . "CIRCLED DIGIT THREE")
     (?④ . "CIRCLED DIGIT FOUR")
     (?⑤ . "CIRCLED DIGIT FIVE")
     (?⑥ . "CIRCLED DIGIT SIX")
     (?⑦ . "CIRCLED DIGIT SEVEN")
     (?⑧ . "CIRCLED DIGIT EIGHT")
     (?⑨ . "CIRCLED DIGIT NINE")
     (?⑩ . "CIRCLED NUMBER TEN")
     (?⑪ . "CIRCLED NUMBER ELEVEN")
     (?⑫ . "CIRCLED NUMBER TWELVE")
     (?⑬ . "CIRCLED NUMBER THIRTEEN")
     (?⑭ . "CIRCLED NUMBER FOURTEEN")
     (?⑮ . "CIRCLED NUMBER FIFTEEN")
     (?⑯ . "CIRCLED NUMBER SIXTEEN")
     (?⑰ . "CIRCLED NUMBER SEVENTEEN")
     (?⑱ . "CIRCLED NUMBER EIGHTEEN")
     (?⑲ . "CIRCLED NUMBER NINETEEN")
     (?⑳ . "CIRCLED NUMBER TWENTY")
     (?Ⅰ . "ROMAN NUMERAL ONE")
     (?Ⅱ . "ROMAN NUMERAL TWO")
     (?Ⅲ . "ROMAN NUMERAL THREE")
     (?Ⅳ . "ROMAN NUMERAL FOUR")
     (?Ⅴ . "ROMAN NUMERAL FIVE")
     (?Ⅵ . "ROMAN NUMERAL SIX")
     (?Ⅶ . "ROMAN NUMERAL SEVEN")
     (?Ⅷ . "ROMAN NUMERAL EIGHT")
     (?Ⅸ . "ROMAN NUMERAL NINE")
     (?Ⅹ . "ROMAN NUMERAL TEN")
     (?Ⅺ . "ROMAN NUMERAL ELEVEN")
     (?㍉ . "SQUARE MIRI")
     (?㌔ . "SQUARE KIRO")
     (?㌢ . "SQUARE SENTI")
     (?㍍ . "SQUARE MEETORU")
     (?㌘ . "SQUARE GURAMU")
     (?㌧ . "SQUARE TON")
     (?㌃ . "SQUARE AARU")
     (?㌶ . "SQUARE HEKUTAARU")
     (?㍑ . "SQUARE RITTORU")
     (?㍗ . "SQUARE WATTO")
     (?㌍ . "SQUARE KARORII")
     (?㌦ . "SQUARE DORU")
     (?㌣ . "SQUARE SENTO")
     (?㌫ . "SQUARE PAASENTO")
     (?㍊ . "SQUARE MIRIBAARU")
     (?㌻ . "SQUARE PEEZI")
     (?㎜ . "SQUARE MM")
     (?㎝ . "SQUARE CM")
     (?㎞ . "SQUARE KM")
     (?㎎ . "SQUARE MG")
     (?㎏ . "SQUARE KG")
     (?㏄ . "SQUARE CC")
     (?㎡ . "SQUARE M SQUARED")
     (?Ⅻ . "ROMAN NUMERAL TWELVE")
     (?㍻ . "SQUARE ERA NAME HEISEI")
     (?〝 . "REVERSED DOUBLE PRIME QUOTATION MARK")
     (?〟 . "LOW DOUBLE PRIME QUOTATION MARK")
     (?№ . "NUMERO SIGN")
     (?㏍ . "SQUARE KK")
     (?℡ . "TELEPHONE SIGN")
     (?㊤ . "CIRCLED IDEOGRAPH HIGH")
     (?㊥ . "CIRCLED IDEOGRAPH CENTRE")
     (?㊦ . "CIRCLED IDEOGRAPH LOW")
     (?㊧ . "CIRCLED IDEOGRAPH LEFT")
     (?㊨ . "CIRCLED IDEOGRAPH RIGHT")
     (?㈱ . "PARENTHESIZED IDEOGRAPH STOCK")
     (?㈲ . "PARENTHESIZED IDEOGRAPH HAVE")
     (?㈹ . "PARENTHESIZED IDEOGRAPH REPRESENT")
     (?㍾ . "SQUARE ERA NAME MEIZI")
     (?㍽ . "SQUARE ERA NAME TAISYOU")
     (?㍼ . "SQUARE ERA NAME SYOUWA")
     (?∮ . "CONTOUR INTEGRAL")
     (?∟ . "RIGHT ANGLE")
     (?⊿ . "RIGHT TRIANGLE")
     (?❖ . "BLACK DIAMOND MINUS WHITE X")
     (?☞ . "WHITE RIGHT POINTING INDEX"))))
 (while jisx0213-charnames
   (put-char-code-property (caar jisx0213-charnames)
                           'ucs-character-name
                           (cdar jisx0213-charnames))
   (setq jisx0213-charnames (cdr jisx0213-charnames))))

(defun sort-char-by-charname (charlist)
  (sort charlist 
        '(lambda (x y) (string<
                        (get-char-code-property x 'ucs-character-name)
                        (get-char-code-property y 'ucs-character-name)))))

(provide 'x0213-char)
